---
output:
  word_document: default
  html_document: default
---

\newpage
# Introduction

This is the third and final research document stemming from a Framework process focused on Scallop Fishing Areas (SFAs) 25, 26, and 27B. The first research document  focused on data inputs [@keyserFrameworkDevelopmentScallop2020] while the second document developed new assessment models for SFAs 25A and 26A [@keithFrameworkDevelopmentScallop2020].  The SFA 26 management unit also includes 26B (Browns Bank South) and 26C (German Bank), whereas SFA 27 includes both 27A (Georges Bank 'a') and 27B (Georges Bank 'b'), and SFA 25, known as the Eastern Scotian Shelf is split into SFA 25A, which includes 25A-Sab (Sable Bank), 25A-Mid (Middle Bank), and 25B [Banquereau, see Table 1 in @keyserFrameworkDevelopmentScallop2020].

A history of the survey and fisheries in SFAs 25, 26, and 27B can be found in @keyserFrameworkDevelopmentScallop2020. __Scallop growth and the selectivity of the fishery varies by area, as such the size categories of scallop varies by area. In both SFA 25A and SFA 26A scallop defined as fully-recruited (FR) are $\ge$ 90 mm in size, recruit scallop are defined as being 75-89 mm in size. In SFA 26C recruit scallop are defined as being between 95-104 mm, while fully-recruited scallop are $\ge$ 105 mm. Finally, in SFA 27B, recruit scallop are defined as scallop that are 85-94 mm in size, while fully-recruited scallop are $\ge$ 95 mm [@keyserFrameworkDevelopmentScallop2020].__

The primary fishing area within SFA 26 is SFA 26A (Browns Bank North). In SFA 25, SFA 25A-Sab (Sable Bank) has been the most consistently fished area, the Middle Bank component of this area is excluded from these analyses due to the limited fishing activity in this portion of SFA 25; hereafter SFA 25A-Sab will be referred to as SFA 25A [@keyserFrameworkDevelopmentScallop2020]. A Bayesian State-Space delay difference model (BSSM) has been adopted for SFA 25A, while a new Spatially Explicit Stock Assessment Model (SEAM) has been adopted for SFA 26A [@keithFrameworkDevelopmentScallop2020]. In addition, to minimize prediction bias, the productivity parameters used to project biomass into future years differed between these two areas; however in both areas the projections used the same non-spatial version of the delay difference model [@keithFrameworkDevelopmentScallop2020]. In SFA 25A, for one-year ahead projections the previous year's natural mortality, recruitment, and recruit growth are used and the fully-recruited growth term is set to one (i.e., the projections assume no full-recruited growth). In SFA 26A, for one-year ahead projections, the previous year's natural mortality, recruitment, recruit growth, and fully-recruited growth are used [@keithFrameworkDevelopmentScallop2020]. The simulations used herein are based upon the productivity parameters and the non-spatial delay difference model used for the one-year ahead projections.

This research document focuses on the development of limit reference points (LRPs) for SFAs 25A, 26A, 26C, and 27B. Options for the LRPs are developed based on the survey biomass indices, while for the two areas with approved assessment models (SFA 25A and SFA 26A), additional LRPs are developed using the results of  Maximum Sustainable yield (MSY) simulations. In addition to the LRPs, candidate target removal reference (RR~tar~)  and upper stock reference points (USRs) are provided from the MSY simulations.  Harvest decision rule (HDR) simulations demonstrate how these simulation techniques can be used, in conjunction with pre-defined management objectives, to inform setting candidate limit removal reference (RR~lim~) and target reference points (TRPs). This document discusses the concepts of RR~lim~ and RR~tar~. Herein, RR~lim~ refers to an exploitation rate that should not be exceeded for the stock, whereas RR~tar~ refers to an exploitation rate that the fishery can maintain, on average, over the long-term. The RR~lim~  should always be greater than the RR~tar~.

In summary, the objectives of this document are:

- To propose and adopt limit reference points for SFAs 25A, 26A, 26C, and 27B; and,
- To provide guidance on upper stock reference points, target reference points, removal reference points, and harvest decision rules.

# Methods

### Background

The LRPs used throughout this document were derived from estimates of the unfished biomass (B~0~) or the biomass at maximum sustainable yield [B~MSY~, @marentetteCrossJurisdictionalReviewInternational2020; @dfoScienceAdvicePrecautionary2021; @dfoScienceAdviceGuidance2023]. LRPs typically use 20% of the estimated B~0~ (B~0(20)~), 30% of B~MSY~ (B~MSY(30)~), or 40% of B~MSY~ [B~MSY(40)~, @dfoFisheryDecisionmakingFramework2009; @dfoScienceAdvicePrecautionary2021; @dfoScienceAdviceGuidance2023]. For the USR a similar convention is used, herein two USRs are provided for guidance: 40% of B~0~ (B~0(40)~) or 80% of B~MSY~ [B~MSY(80)~, @dfoFisheryDecisionmakingFramework2009; @marentetteCrossJurisdictionalReviewInternational2020]. In addition to the biomass reference points, guidance on candidate limit (RR~lim~) and target (RR~tar~) removal references are provided. For the index based reference points, the biomass indices use the survey index (tonnes) scaled to the survey area and corrected for gear catchability and the removal references are provided as relative indices. The catchability (_q_) was set at 0.33 for all areas, this is similar to the estimates from both the SFA 25A and SFA 26A models [@keithFrameworkDevelopmentScallop2020].  For consistency between the methods, all analyses used data from 1994 to 2022 inclusive [@keyserFrameworkDevelopmentScallop2020; @keithFrameworkDevelopmentScallop2020].

## Index Based Methods

LRPs and USRs were developed using the survey biomass index time series in four areas (SFA 25A, SFA 26A, SFA 26C, SFA 27B) that are covered by annual surveys. For SFA 26C, a liner was added to the gear in 2008, to increase the catchability of smaller scallop, so the analyses for this area were limited to 2008 onward as changes in the gear can affect selectivity. See @keyserFrameworkDevelopmentScallop2020 for more details on the methods underlying the development of the survey biomass indices. The survey biomass indices used to develop the reference points are not corrected for the catchability of the survey gear and the values are not directly comparable to the model based estimates. The survey in SFA 26C is not a statrafied survey, thus the area used to estimate the the fully-recruited survey biomass index is based on the total area of the survey domain (`r ger.area.round` km^2^).

Survey index based reference points were developed using: 1) the highest three-year geometric mean survey biomass index as a proxy for the stocks carrying capacity or unfished biomass B~0~ and 2) the geometric mean of the time series as a proxy for the biomass at maximum sustainable yield (B~MSY~). A three-year geometric mean approach was adopted since observation error results in uncertainty around any single year survey biomass estimate and it is challenging to quantify the magnitude of this uncertainty for index based methods. For the three-year geometric mean, the most recent three-year with data is used as the indicator of stock status for a given year; this approach aligns with practices done elsewhere for ascertaining stock status using survey biomass indices [c.f., @dfoMaritimesResearchVessel2024]. In addition, these areas tended to be fished annually, making it possible to utilize the relative exploitation rate index to explore the development of both a (RR~lim~) and a (RR~tar~). See @keyserFrameworkDevelopmentScallop2020 for more details on the methods underlying the development of the relative exploitation rate index and survey biomass index. 

### Relative Removal Reference 

The four areas noted above tend to be fished annually, making it possible to utilize the relative exploitation rate index to explore the development of both RR~lim~ and RR~tar~. See @keyserFrameworkDevelopmentScallop2020 for more details on the methods underlying the development of the relative exploitation rate index.  

A semi-quantitative method (GEM - Generalized Exploitation Method) that compared the change in the relative survey biomass index ($\Delta$_B~r~_) to the relative exploitation rate (_E~r~_) was used to provide guidance on a candidate RR~lim~ for the index based methods [@jonsenGeorgesBankScallop2009; @sameotoAssessingProductivityScallop2024]. GEM assumes a linear relationship between the change in the survey index biomass and the relative exploitation rate:


\begin{align}
\Delta B_{r_i} \sim N(0,\sigma^2_{i}) \\
E(\Delta B_{r_i}) = \mu_{i} \\
\mu_{i} =  E_{r_i}\\ 
\end{align}


where $\Delta$_B~r~_ is the expected value of _mu_ and is assumed to be normally distributed with a variance of $\sigma$^2^; _i_ represented each observation. A significantly negative slope provides evidence that the fishery has influenced the biomass in the region, and the x-intercept provides an estimate of the relative exploitation rate above which the biomass tends to decline.

A second method was developed to estimate a RR~tar~ for the index based methods. First, the standard deviation of the survey index biomass was calculated using a five-year moving window. For years in which there was no survey data in an area, the survey biomass index was estimated as the mean of the previous and following years' indices [@dfoStockStatusUpdate2022a;@dfoStockStatusUpdate2022c]. The five-year period in which the survey biomass index had the lowest standard deviation was selected and the median relative exploitation rate during this period was estimated. This value was provided as an index based candidate RR~tar~.

## MSY Simulations

The MSY simulations are undertaken for SFA 25A and SFA 26A using the productivity parameters from the respective stock assessment models for each area.  The MSY simulations use the modelled productivity parameters adopted for the one-year ahead projections for the respective areas [@keithFrameworkDevelopmentScallop2020].

The underlying model for the projection simulations is based on the non-spatial delay difference model used in @keithFrameworkDevelopmentScallop2020.

$$
B_{fr,t} = e^{-m_{fr,t}} g_{fr,t} (B_{fr,(t-1)} - C_{t-1}) + e^{-m_{r,t}} g_{r,t} R_{t-1}
$$

Fully-recruited biomass is _B~fr~_, natural mortality is _m_, growth is _g_, landings are _C_, the recruit biomass is _R_, and the _t_ index represents the annual time step, which goes from 1 to the number of years in the simulation.  Where applicable, fully-recruited scallops are given the subscript _fr_, while recruits have the subscript _r_. Recruit sized scallop were defined as 75-89 mm (shell height), and fully-recruited scallop were defined as being $\ge$ 90 mm [@keyserFrameworkDevelopmentScallop2020]. In SFA 25A, the fully-recruited growth term (_g~fr,t~_) parameter is set to one for the simulations, while in SFA 26A the recruit natural mortality (_m~r~_) is the same as the fully-recruited natural mortality [_m~fr~_, @keithFrameworkDevelopmentScallop2020]. 

### Density Dependence

Declines in  productivity with increasing adult biomass (i.e., negative density dependence) is thought to be a primary means of population regulation and underpins much of fisheries science [@hilbornQuantitativeFisheriesStock1992]. The relationship between the productivity parameters and the adult biomass (hereafter referred to as spawning stock biomass or _SSB_) are incorporated into the population dynamics.  Here, it is assumed that the SSB includes both recruit and fully-recruited scallop, as a result, we ignore the potential contribution of scallop with a shell height of < 75 mm on recruitment. The contribution to recruitment is expected to be minor for scallop under 75 mm in size [@parsonsIntraannualLongtermPatterns1992; @mcgarveySpatialParentAgeAnalysis1993]. Evidence for density dependence in the productivity parameters was explored using both quantitative and qualitative methods.

The quantitative method assumed a linear relationship between the productivity parameter and SSB. The linear model structure was:

\begin{align}
P_i = N(\mu_i,\sigma^2) \\
E(P_i) =\mu_i \\
\mu_i = \alpha + \beta \times SSB
\end{align}

where _P~i~_ was the productivity parameter, $\sigma$_^2^_ is the variance,_$\mu$_~i~_ is the expected value of the productivity parameter, $\alpha$ is the intercept and $\beta$ is the slope.  This was the model used to evaluate density dependence for both the growth and natural mortality productivity terms.

To evaluate density dependence of recruitment, recruitment on a 'per-capita' basis was used as the metric of productivity. The results of the von Bertalanffy analyses suggests that recruit sized scallop in SFA 25A are approximately `r sab.rec.age` years old, while in SFA 26A faster growth results in most recruit size scallop being approximately `r bbn.rec.age` years old [@keyserFrameworkDevelopmentScallop2020]. The recruits(_R_) in each SFA were thus offset by `r bbn.rec.age` (SFA 26A) or `r sab.rec.age` (SFA 25A) years respectively, to align with the _SSB_ than produced them (e.g., recruits in SFA 25A in 2022 were assumed to be 4 years old, thus these scallop were 'born' in 2018, and thus were aligned with the _SSB_ in 2018). The biomass of _R_ was then divided by the _SSB_ in the year the recruits were 'born', giving a recruit per spawner metric (RPS). When RPS is log transformed and compared to _SSB_ the relationship is a linearization of the Ricker stock-recruit relationship:

$$
R_t = \alpha (SSB_t)e^{-\beta (SSB_t)}
$$

This can be linearized as:

$$
log(\frac{R_t}{SSB_t}) = \alpha - \beta \times SSB_t
$$

thus simplifying to the linear regression formula above with _P = log_($\frac{R_t}{SSB_t})$.

This quantitative linear method was initially used to identify evidence for a density dependent relationship (e.g., the blue line with shaded 95% confidence interval in Figure \@ref(fig:sab-rps-ssb-fig)).  If a density dependent relationship was identified, the linear regression (with uncertainty) was used to account for density dependence in the MSY simulations. However, the predictions from the linear regressions were not used in the MSY simulations because 1) the relationship was rarely linear and 2) these linear models could not account for the observed variability in the data and resulted in the parameter estimates (this was particularly problematic for recruitment) having far less variability than observed in the respective stock assessment time series for the productivity parameter. Robust regression techniques were explored to better account for the observed variability, but these techniques did not overcome this challenge.

For this reason, a qualitative visual method was developed to identify the SSB at which a discontinuous non-linear change in a productivity parameter was observed (e.g., the red dashed vertical line in Figure \@ref(fig:sab-rps-ssb-fig)). This qualitative method is referred to hereafter as the _breakpoint_ method. Details of how the breakpoints were incorporated into the MSY simulations are described below in the _Simulation Procedure_ section.


### Correlation

Autocorrelation in each historically modelled productivity parameter, and cross-correlation between these parameters, were incorporated into the population dynamics for the MSY and HDR simulations. The strength of autocorrelation in these historically modelled productivity parameter was estimated using standard autocorrelation techniques [i.e., the _acf_, _pacf_, and _ccf_ functions from the _stats_ package in R version 4.2.2, @rcoreteamLanguageEnvironmentStatistical2023]. The correlation in RPS was explored on the log scale, while growth and natural mortality were on the natural scale. Where there was evidence for non-stationarity in the respective productivity parameter (e.g., a decline in the parameter estimate over time), the autocorrelation was tested using detrended data (using the residuals from a linear model fit to the productivity time series). There was no evidence of autocorrelation in the growth and most natural mortality parameters; thus no auto-correlation was modeled for these parameters. The exception was a marginally significant relationship for the fully-recruited natural mortality term for lag 2 in SFA 25A.

### Simulation Procedure

In the subsequent text, the 'modelled parameters' refers to parameter estimates from the stock assessment models, these form the basis for our understanding of the historical productivity of each modelled area.  The MSY simulations utilize the historical productivity relationships to develop future projections for each stock. In the MSY simulations a single time series projection consists of a user defined number of years, which we refer to as a 'realization'. A 'scenario' combines the results from multiple realizations with a given set of rules (e.g., if a scenario of `r n_sims` realizations is run with no fishery removals, the results of this would be referred to as a 'no fishing scenario'). The MSY simulations are the result of multiple exploitation rate scenarios using the historical productivity patterns obtained from the stock assessment models.

The MSY simulations build off previous MSY simulation methods developed for scallop stocks in the Maritimes Region, with the current MSY simulations more completely accounting for the variability and correlation between the productivity than previously possible [e.g., @smithFrameworkAssessmentSFA2015]. More fully characterizing the productivity dynamics aligns with recommended 'best practices' for the development of reference points [@marentetteSpecificationPrecautionaryApproach2021; @marentetteCrossJurisdictionalReviewInternational2020], moreover, these techniques enable the exploration of the impact of more complex harvest strategies on the stock dynamics (see the HDR Simulations section for more details).

The MSY simulations consisted of time series projections of `r n_y` years with `r n_sims` realizations for each scenario. The scenarios were based on exploitation rates; these exploitation rate scenarios varied the exploitation rate between 0 and `r max(bbn.exp.scenario)` in steps of `r bbn.exp.scenario[2]`.  There was no variability over time in the exploitation rate for a given scenario, e.g., the exploitation rate scenario of 0.1 removed 10% of _B~fr~_ in every simulated year.  The summaries and reference points were calculated using the final `r last.yrs` years of the projected time series.  The results of the density dependence and correlation analyses were used to determine how the productivity parameters would be sampled for these MSY simulations. 

The following procedure was applied in cases in which there was no evidence of either density dependence or correlation in the historic modelled productivity parameters. For each productivity parameter, a time series projection with `r n_y` years of parameter values was developed for each of the `r n_sims` realizations and for each exploitation rate scenario. These time series projections were developed by sampling from a log-normal distribution with the mean (the median for natural mortality as the mean resulted in the simulations having multiple years with fully-recruited natural mortality rates in excess of 90%) and standard deviation taken from the modelled productivity parameter estimates. The log-normal distribution was used to ensure the productivity parameters remained positive while providing variability in the productivity parameters similar to those historically observed.

When density dependence was observed (i.e., the _breakpoint_ method was used) without correlation, the productivity parameter time series projections were dependent on the SSB estimates and were calculated for each year in each of the projected time series. When a single breakpoint was identified and the simulated SSB for a year was below the breakpoint, the mean (median for _m_) and standard deviation of the historically modelled productivity parameter below the breakpoint were used to sample from a log-normal distribution to obtain a value for the projected productivity parameter for that year. Conversely, when the data were above the breakpoint the same procedure was followed using only data from above the breakpoint SSB. Similarly, if multiple breakpoints were observed (e.g., RPS in SFA 25A), this methodology was followed, using the historical productivity parameters from within the appropriate SSB category.

When correlation was observed in the historically modelled productivity parameters without density dependence, the productivity parameter time series projection used the historical time series auto-correlation with the mean (median for _m_) and standard deviation of the time series projection set based on the historical productivity parameter. Auto-correlation was incorporated using an auto-regressive integrated moving average (ARIMA) framework [i.e., using the _arima.sim_ function from the _stats_ package, and the _rmvnorm_ function from the _mvtnorm_ package, R version 4.2.2, @rcoreteamLanguageEnvironmentStatistical2023], using the first two auto-regressive components. 

Where correlation and density dependence were both found in a historical productivity parameter(s), both of these characteristics were incorporated into the productivity parameter time series projections. The first step was to develop the productivity parameter time series projection with the auto and cross correlation structure observed in the historical productivity parameter time series using the above ARIMA methods.  Additionally, the mean (median for _m_) and standard deviation of the projected time series was set based on the historical productivity parameter estimates from below the _breakpoint_ SSB (historically there are more years in which the stock was below the breakpoint). The second step was to update the productivity parameter estimate in the time series projection in years that SSB was above the _breakpoint_. In this step, the productivity parameter estimate for the year was replaced by a sample from a log-normal distribution with a mean and standard deviation estimated from the historical productivity parameter above the _breakpoint_. This procedure somewhat weakened the strength of the correlation in the time series projections, but resulted in time series in which the general correlation structure and density dependence relationships of the original productivity time series were retained (see the Results section).

Cross-correlation was only observed between the RPS and fully-recruited natural mortality productivity parameters, this cross-correlation may be related to the challenges that have been observed with delay difference models independently estimating values of both parameters [e.g., @mcdonaldExplicitIncorporationSpatial2021]. The cross-correlation analysis was used to identify the peak correlation at time lags of less than five years between these two parameters using the historical productivity of RPS and fully-recruited natural mortality.  The time series projections were developed using an ARIMA framework to simulate RPS and natural mortality time series to retain the characteristics of the observed RPS and natural mortality time series. Density dependence in RPS was incorporated into the time series projection as described in the previous paragraph.

<!-- Didn't need to do this.... However, when the simulation estimated a SSB above the highest observed value, the net productivity of the system was forced to be negative.  This was achieved by setting the growth terms to vary around one, the RPS was set to vary around 10% of the lowest RPS value, and the natural mortality varied around two times the highest observed natural mortality estimate, in each of these cases the standard deviation was set to 0.1 and samples were simulated using a log normal distribution. This effectively induced a carrying capacity into the population dynamics below the maximum observed SSB, while respecting the observed population dynamics when the population was at low SSB. -->

Finally, to constrain the MSY simulations from reaching unrealistically high biomass estimates, whenever the SSB exceeded the maximum observed SSB in the historical modelled time series, the fully-recruited growth parameter was set to 1 and sampled from a log-normal distribution with a standard deviation of 0.1.

### Model Derived Indices

B~MSY~ and B~0~ were estimated from the MSY simulation results. B~0~ was calculated as median biomass of the final `r last.yrs` years from the simulations in which the exploitation rate was set to 0.  B~MSY~  was calculated as the median biomass of the final `r last.yrs` years of the simulations using the exploitation rate that resulted in the average yield from the fishery being maximized (MSY) using the final `r last.yrs` years of simulated data. The exploitation rate at B~MSY~ was the long-term target exploitation rate and this can be used to inform the setting of the RR~tar~.

As with the index based methods, the criteria for the proposed LRPs and suggested USRs were based on B~0~ and B~MSY~. Proposed LRPs were set at 20% of B~0~ (B~0(20)~) and 30% (B~MSY(30)~) and 40% (B~MSY(40)~)  of B~MSY~, while candidate USRs at 40% of B~0~ (B~0(40)~) and at 80% of B~MSY~ (B~MSY(80)~) were provided. An additional benefit of using stochastic simulations is the ability to identify the percentage of the years in which the stocks were in the critical (below the LRP), cautious (between the LRP and USR), and healthy zones (above the USR). Using the final `r last.yrs` years of data, B~0(20)~ as the LRP, and B~0(40)~ as the USR, the proportion of the time each of the simulations were in these zones from the scenario in which fishing at the exploitation rate that resulted in the biomass being at B~MSY~.

## HDR Simulations 

The stochastic simulations developed herein can be used to explore scenarios that utilize more complex harvest strategies than explored in the above MSY simulations (where the exploitation rate for each scenario is fixed through time). For the HDR simulations, the productivity parameters are simulated as per the above procedures, but instead of using a fixed exploitation rate for a scenario, it can be varied as a function of the current simulated biomass. In addition, HDR scenarios can be developed that link the exploitation rates to the reference points and explore how varying the exploitation rates at each of the reference points (often referred to as _control points_) will impact the stock dynamics over the long-term.

While these HDR simulations are not required for setting the LRP, an exploration of different HDR scenarios provide additional understanding of the impact of implementing different USRs and RR~tar~. Additionally, these HDR simulations enable the exploration of additional reference points, such as the development of a biomass based target reference point (TRP) and a limit removal reference (RR~lim~) [@dfoFisheryDecisionmakingFramework2009; @marentetteCrossJurisdictionalReviewInternational2020]. The TRP is a value above the USR and is determined by productivity objectives or other biological considerations [@marentetteCrossJurisdictionalReviewInternational2020; @dfoScienceAdvicePrecautionary2021; @dfoScienceAdviceGuidance2023].

There are innumerable HDR scenarios that could be tested but scenarios should be designed to address management objectives. The HDR simulations have the potential to inform alternative harvesting strategies that could support both conservation and socioeconomic objectives. The code to explore the impact of various HDR scenarios on the stock is publicly available [@keithOffshoreScallopHarvest2025]. Defining HDRs is not the purview of Science and there are no established HDRs for the SFAs evaluated here; however, we present a HDR scenario for each of SFA 25A and SFA 26A to demonstrate the utility of this approach.

For the HDR scenarios, the management objectives were to a) maintain the stock near the TRP, b) increase the long term average removals from the fishery, and c) reduce the percentage of the years that the stock was below the LRP. The HDR scenario results for objectives b) and c) were compared to the results from the MSY simulations scenario in which the exploitation rate resulted in the population being at B~MSY~. In each HDR scenario, the TRP was set at the B~MSY~ estimate, the LRP was set at B~MSY(40)~, and the USR was set at B~MSY(80)~. The mean exploitation rate was set as described below, a log-normal distribution with standard deviation of `r bbn.exp.sd` was used to allow for some variability in the exploitation rate. These results summarize the final `r last.yrs` years of the `r n_sims` realizations and, similarly to the MSY simulations, the percentage of the years in which the results are observed to be below the LRP, above the USR, above the TRP, or between these reference points was calculated.

In SFA 25A, the HDR scenario set the exploitation rate to a) a RR~lim~ of `r sab.trp.exp` when when _B~fr~_ was above the TRP (`r sab.trp.bmsy` tonnes), b)  `r sab.usr.exp` when _B~fr~_ was above the USR (`r sab.usr.bmsy` tonnes) but below the TRP, c) decline linearly from `r sab.usr.exp` at the USR, to 0 at the LRP (`r sab.lrp.4.bmsy` tonnes) when _B~fr~_ was below the USR but above the LRP , d) 0 when _B~fr~_ was below the LRP. Similarly, in SFA 26A, the HDR scenario set the exploitation rate to a) an an RR~lim~ of `r bbn.trp.exp` when _B~fr~_ was above the TRP (`r bbn.trp.bmsy`  tonnes), b) `r bbn.usr.exp` when _B~fr~_ was above the USR (`r bbn.usr.bmsy` tonnes) and below the TRP, c) decline linearly from `r bbn.usr.exp` at the USR, to 0 at the LRP (`r bbn.lrp.4.bmsy` tonnes) when  _B~fr~_ was below the USR but above the LRP, d) 0 when _B~fr~_ was below the LRP.

# Results

## Productivity and Density Dependence

### SFA 25A

There was clear evidence for negative density dependence in recruitment, RPS increased as biomass declined (Figure \@ref(fig:sab-rps-ssb-fig)). The general relationship followed the expectation of a Ricker model (Figure \@ref(fig:sab-rps-ssb-fig)), but as noted above, the _breakpoint_ method was preferred for use in the MSY simulations. The breakpoint used was `r sab.rps.bp2` tonnes (Figure \@ref(fig:sab-rps-ssb-fig)). A second potential _breakpoint_ was identified at `r sab.rps.bp1` tonnes, however simulation testing using this additional breakpoint lead to the stock consistently producing relatively large recruit biomass whenever the stock biomass was below `r sab.rps.bp1` tonnes. This resulted in the simulations using this _breakpoint_ supporting exploitation rates that were two to three times higher than has ever been observed in SFA 25A. As a result this additional breakpoint was not incorporated into the simulations. There was no evidence for density dependence in the growth or natural mortality parameters (Figures \@ref(fig:sab-g-ssb-fig) and \@ref(fig:sab-m-ssb-fig)). There were also no discontinuous breaks in the relationships between growth or natural mortality as SSB increased (Figures \@ref(fig:sab-g-ssb-fig) and \@ref(fig:sab-m-ssb-fig)). Therefore, no density dependence was incorporated into the MSY or HDR simulations for the growth or natural mortality parameters.

There was evidence of autocorrelation in the RPS time series, with a significant positive correlation (`r sab.rps.cor.1`) at a one year lag (Figure  \@ref(fig:sab-pacf-rps-fig)). There was no evidence of correlation in the growth parameters (Figure \@ref(fig:sab-pacf-g-fig)). A weakly significant negative correlation (`r sab.m.cor.2`) was observed at a two year lag for the fully-recruited mortality and this was incorporated into the simulations, while there was no correlation in the recruit mortality time series (Figure \@ref(fig:sab-pacf-m-fig)). Finally, the cross-correlation between RPS (offset to the year the recruits are observed in the time series) and fully-recruited natural mortality was evaluated and a weak but significant correlation was observed in the relationship, the highest correlations were observed between lags of -1 to 1 years, with the peak at `r sab.m.rps.lag` (r = `r sab.m.rps.cor`, Figure \@ref(fig:sab-ccf-m-rps-fig)). This suggests that relatively large (small) recruit biomass events (given the SSB that produced the recruits) were observed during periods of high (low) natural mortality. To account for this effect, the simulations included the correlation between fully-recruited natural mortality and RPS at the peak lag.

The annual survey biomass index estimates were highly correlated (r = `r sab.cor.q.bm`) to the model biomass estimates, although there were several years in which the survey biomass index was noticeably different than the resultant model biomass estimate (e.g., 1995, 2010, and 2022) and most of the data fell near the 1:1 line (Figure \@ref(fig:sab-bm-vs-index-fig)). This indicated that the survey biomass index was generally a reasonable proxy for the model biomass, but the two metrics will differ when comparing individual years (Figure \@ref(fig:sab-bm-vs-index-fig)).

### SFA 26A

There was clear evidence for negative density dependence in recruitment, RPS increased as biomass declined (Figure \@ref(fig:bbn-rps-ssb-fig)). The general relationship followed the expectation of a Ricker model (Figure \@ref(fig:bbn-rps-ssb-fig)), but as noted above, the _breakpoint_ method was preferred for use in the MSY simulations. A single breakpoint was identified, when the SSB was above `r bbn.rps.bp` tonnes RPS tended to be the lowest observed in the time series, while there was no evidence for a trend in RPS with changes in SSB below this value (Figure \@ref(fig:bbn-rps-ssb-fig)). There was little evidence for density dependence in the growth or natural mortality parameters (Figures \@ref(fig:bbn-g-ssb-fig) and \@ref(fig:bbn-m-ssb-fig)). There were also no discontinuous breaks in the relationships between growth and SSB (Figure \@ref(fig:bbn-g-ssb-fig)), although we note that low values of natural mortality were not observed when the SSB was above approximately `r bbn.m.bp` tonnes (Figure \@ref(fig:bbn-m-ssb-fig)). As a result, no density dependence was incorporated into the MSY or HDR simulations for growth or natural mortality.

There was evidence of autocorrelation in the RPS time series, with a significant positive correlation (`r bbn.rps.cor.1`) at a one year lag and a significant negative correlation at a two year lag (`r bbn.rps.cor.2`, Figure \@ref(fig:bbn-pacf-rps-fig)). There was no significant correlation in the growth or natural mortality time series (Figures \@ref(fig:bbn-pacf-g-fig) and \@ref(fig:bbn-pacf-m-fig)). Finally, the cross-correlation between RPS (offset to the year the recruits are observed in the time series) and fully-recruited natural mortality was evaluated, a significant correlation was observed in the relationship, the highest correlations were observed between lags of 0 to 2 years, with the peak at a lag of `r bbn.m.rps.lag` year (r = `r bbn.m.rps.cor`, Figure \@ref(fig:bbn-ccf-m-rps-fig)). This suggests that relatively large (small) recruit biomass events (given the SSB that produced the recruits) were observed during periods of high (low) natural mortality. To account for this effect, the simulations included the correlation between fully-recruited natural mortality and RPS at the peak lag.

The annual survey biomass index estimates were correlated (r = `r bbn.cor.q.bm`) to the model biomass estimates, although the survey biomass index does not follow the model biomass estimates as closely as observed in SFA 25A (Figure \@ref(fig:bbn-bm-vs-index-fig)). In several of the early years in the time series (i.e., 1994-1998), the model biomass estimate is notably higher than the survey biomass index. This may be related to the initial conditions required for SEAM [@keithFrameworkDevelopmentScallop2020]. In general, these results indicated that the survey biomass index is a reasonable proxy for the model biomass, especially in more recent years, but that differences between the two metrics in a particular year can be substantial (Figure \@ref(fig:bbn-bm-vs-index-fig)).

## Reference Points

### Survey Biomass Indices

Three survey biomass index based LRPs were developed for each area (Table \@ref(tab:survey-index-rp-table)).  In SFA 25A the three LRPs were, `r LRP.med.3.25a` tonnes (B~MSY(30)~) , `r LRP.med.4.25a` tonnes (B~MSY(40)~), and `r LRP.max.2.25a` tonnes (B~0(20)~; Figure \@ref(fig:rp-bmi-fit)). In SFA 26A the three LRPs were `r LRP.med.3.26a` tonnes (B~MSY(30)~), `r LRP.med.4.26a` tonnes (B~MSY(40)~), and `r LRP.max.2.26a` tonnes (B~0(20)~; Figure \@ref(fig:rp-bmi-fit)). In SFA 26C the three LRPs were, `r LRP.med.3.26c` tonnes (B~MSY(30)~), `r LRP.med.4.26c` tonnes (B~MSY(40)~), and `r LRP.max.2.26c` tonnes (B~0(20)~; Figure \@ref(fig:rp-bmi-fit)). In SFA 27B the three LRPs were, `r LRP.med.3.27b` tonnes (B~MSY(30)~), `r LRP.med.4.27b` tonnes (B~MSY(40)~), and `r LRP.max.2.27b` tonnes (B~0(20)~; Figure \@ref(fig:rp-bmi-fit)).

Two survey biomass index based candidate USRs were developed in each area (Table \@ref(tab:survey-index-rp-table)). In SFA 25A the two USRs were, `r USR.med.8.25a` tonnes (B~MSY(80)~) and `r USR.max.4.25a` tonnes (B~0(40)~; Figure \@ref(fig:rp-bmi-fit)). In SFA 26A the two USRs were, `r USR.med.8.26a` tonnes (B~MSY(80)~) and  `r USR.max.4.26a` tonnes (B~0(40)~; Figure \@ref(fig:rp-bmi-fit)). In SFA 26C the two USRs were, `r USR.med.8.26c` tonnes (B~MSY(80)~) and `r USR.max.4.26c` tonnes (B~0(40)~; Figure \@ref(fig:rp-bmi-fit). In SFA 27B the two USRs were, `r USR.med.8.27b` tonnes (B~MSY(80)~) and `r USR.max.4.27b` tonnes (B~0(40)~; Figure \@ref(fig:rp-bmi-fit)).

Phase plots using the relative removal and survey biomass indices indicated that the relative exploitation rate did not have a clear relationship to the survey biomass index in any of the areas (Figure \@ref(fig:kobe-bmi-fig)). GEM was unable to identify a relationship between the change in biomass indices and relative exploitation rate in SFA 25A, 26C, or 27B that would facilitate the development of a RR~lim~ in these areas (Figure \@ref(fig:gem-bmi-fig)). In SFA 26A, the change in the biomass index tended to decline as the relative exploitation rate increased which facilitated the development of a candidate RR~lim~ using the relative indices, the GEM suggested a candidate RR~lim~ of approximately `r rr.rf.26a` (top right panel, Figure \@ref(fig:gem-bmi-fig) and Table \@ref(tab:survey-index-rp-table)).

A candidate relative RR~tar~ was identified in each of the areas as the median relative exploitation rate of the five-year period with the least variability in the survey biomass index (Table \@ref(tab:survey-index-rp-table)). In SFA 25A, the candidate relative RR~tar~ was `r target.rr.25a.index` based on the relative exploitation rate between `r min(low.25a.yrs)` and `r max(low.25a.yrs)`. In SFA 26A, the candidate relative RR~tar~ was `r target.rr.26a.index` based on the relative exploitation rate between  `r min(low.26a.yrs)` and `r max(low.26a.yrs)`. In SFA 26C, the candidate relative RR~tar~ was `r target.rr.26c.index` based on the relative exploitation rate between `r min(low.26c.yrs)` and `r max(low.26c.yrs)`. In SFA 27B, the candidate relative RR~tar~ was `r target.rr.27b.index` based on the relative exploitation rate between `r min(low.27b.yrs)` and `r max(low.27b.yrs)`.

### MSY Simulations

In SFA 25A, the MSY simulation time series projections of the productivity parameters had similar characteristics to historically modelled time series. The time series projections from the MSY scenario in which the exploitation rate was set to `r sab.rr` were compared to the historically modelled time series. The recruit growth and natural mortality parameters from the simulations had minimal auto-correlation (Figure \@ref(fig:sab-sim-acfs-fig)). The simulated RPS time series retained the lag 1 correlation without any notable lag 2 correlation (mean simulation estimates were `r sab.cor.sim.summary$rps.ar1` and `r sab.cor.sim.summary$rps.ar2` respectively, Figure \@ref(fig:sab-sim-acfs-fig)). The fully-recruited natural mortality retained the lag 2 correlation without any notable lag 1 correlation (mean simulation estimate were `r sab.cor.sim.summary$m.acf.ar2` and `r sab.cor.sim.summary$m.acf.ar1` respectively, Figure \@ref(fig:sab-sim-acfs-fig)).  In addition, the peak correlation between natural mortality and RPS was also present in the simulated data at lag 1, however as with the RPS and natural mortality auto-correlation, this value was somewhat lower in the simulations (the mean simulation estimate was `r sab.cor.sim.summary$rps.m.cor`, Figure \@ref(fig:sab-sim-ccf-fig)). The density dependence observed in the RPS data was retained in the simulations, with recruitment being consistently low when the SSB exceeded the SFA 25A _breakpoint_ (`r sab.rps.bp2` tonnes) and the RPS values below the _breakpoint_ were similar to the underlying observed RPS values, no density dependence was observed in the other simulated productivity parameters (Figure \@ref(fig:sab-sim-dd-fig)).

In SFA 25A, the MSY simulation results indicated that the median biomass stabilized at approximately `r sab.b0` tonnes when the exploitation rate was 0 (Figure \@ref(fig:sab-mn-bm-sim-fig)). This is hereafter considered the _unfished biomass_ (B~0~) for SFA 25A . The exploitation rate that maximized the removals in the long term was `r sab.rr` (Figure \@ref(fig:sab-mn-fmsy-sim-fig)); this was considered a candidate RR~tar~ for SFA 25A based on the historically observed productivity regime. The median biomass at this RR~tar~ was `r sab.bmsy` tonnes and this was considered the biomass at maximum sustainable yield (B~MSY~; Figure \@ref(fig:sab-mn-bmsy-sim-fig)). The median annual removals at B~MSY~ were `r sab.c.at.msy` tonnes (Figure \@ref(fig:sab-mn-fmsy-sim-fig)).

Based on these values, three MSY simulation based LRPs were proposed for SFA 25A, `r sab.lrp.3.bmsy` tonnes (B~MSY(30)~), `r sab.lrp.4.bmsy` tonnes (B~MSY(40)~), and `r sab.lrp.b0` tonnes (B~0(20)~; Figure \@ref(fig:sab-mod-rps-fig) and Table \@ref(tab:model-rp-table)). Two MSY simulation candidate USRs were provided for SFA 25A, `r sab.usr.bmsy` tonnes (B~MSY(80)~) and `r sab.usr.b0` tonnes (B~0(40)~; Figure \@ref(fig:sab-mod-rps-fig) and Table \@ref(tab:model-rp-table)). Using the MSY scenario with the exploitation rate of `r sab.rr`, and with a LRP set at B~MSY(40)~ and a USR of B~MSY(80)~ as examples, the simulations for SFA 25A resulted in the population being above the USR (i.e., in the "Healthy Zone") in `r sab.prop.yrs.healthy`% of the simulated years, below the LRP (i.e., in the "Critical Zone") in `r sab.prop.yrs.critical`% of the simulated years, and between the LRP and USR (i.e., in the "Cautious Zone") in `r sab.prop.yrs.cautious`% of the simulated years (Figure \@ref(fig:sab-mod-reals-rps-fig)).

In SFA 26A, the MSY simulation time series projections of the productivity parameters had similar characteristics to historically modelled productivity time series. The time series projections from the MSY scenario in which the exploitation rate was set to `r bbn.rr` were compared to the historically modelled productivity time series. The growth and natural mortality parameters from the simulations had minimal auto-correlation (Figure \@ref(fig:bbn-sim-acfs-fig)). The simulated RPS time series retained both a lag 1 and lag 2 correlation (mean simulation estimates were `r bbn.cor.sim.summary$rps.ar1` and `r bbn.cor.sim.summary$rps.ar2` respectively; this correlation was somewhat weaker than the observed RPS time series, Figure \@ref(fig:bbn-sim-acfs-fig)).  In addition, the peak correlation between natural mortality and RPS was also present in the simulated data at lag -1, however as with the RPS and natural mortality auto-correlation, this value was somewhat lower in the simulations (the mean simulation estimate was `r bbn.cor.sim.summary$rps.m.cor`, Figure \@ref(fig:bbn-sim-ccf-fig)).  The density dependence of RPS was retained, with it being consistently low when the SSB exceeded the SFA 26A _breakpoint_ (`r bbn.rps.bp` tonnes) and the value of RPS below the breakpoint being similar to the underlying observed RPS values, no density dependence was observed in the other simulated productivity parameters (Figure \@ref(fig:bbn-sim-dd-fig)).

In SFA 26A, the MSY simulation results indicated that the median biomass stabilized at approximately `r bbn.b0` tonnes when the exploitation rate was 0 (Figure \@ref(fig:bbn-mn-bm-sim-fig)). This is hereafter considered the _unfished biomass_ (B~0~) for SFA 26A. The exploitation rate that maximized the removals in the long term was `r bbn.rr` (Figure \@ref(fig:bbn-mn-fmsy-sim-fig)), this was considered a candidate RR~tar~ for SFA 26A based on the historically observed productivity regime.  The median biomass at the RR~tar~ was `r bbn.bmsy` tonnes and this was considered the biomass as maximum sustainable yield (B~MSY~; Figure \@ref(fig:bbn-mn-bmsy-sim-fig)). The median annual removals at B~MSY~ were `r bbn.c.at.msy` tonnes (Figure \@ref(fig:bbn-mn-fmsy-sim-fig)).

Based on these values three MSY simulation based LRPs are proposed for SFA 26A, `r bbn.lrp.3.bmsy` tonnes (B~MSY(30)~), `r bbn.lrp.4.bmsy` tonnes (B~MSY(40)~), and `r bbn.lrp.b0` tonnes (B~0(20)~; Figure \@ref(fig:bbn-mod-rps-fig) and Table \@ref(tab:model-rp-table)). Two MSY simulation candidate USRs are provided for SFA 26A, `r bbn.usr.bmsy` tonnes (B~MSY(80)~) and `r bbn.usr.b0` tonnes (B~0(40)~; Figure \@ref(fig:bbn-mod-rps-fig) and Table \@ref(tab:model-rp-table)). Using the MSY scenario with the exploitation rate of `r bbn.rr`, and with a LRP set at B~MSY(40)~ and a USR of B~MSY(80)~ as examples, the simulations for SFA 26A resulted in the population being above the USR (i.e., in the "Healthy Zone") in `r bbn.prop.yrs.healthy`% of the simulated years, below the LRP (i.e., in the "Critical Zone") in `r bbn.prop.yrs.critical`% of the simulated years, and between the LRP and USR (i.e., in the "Cautious Zone") in `r bbn.prop.yrs.cautious`% of the simulated years (Figure \@ref(fig:bbn-mod-reals-rps-fig)).

## HDR Simulations

For the SFA 25A HDR scenario, the median biomass (`r sab.med.bm.hcr` tonnes) fluctuated around the TRP (Figure \@ref(fig:sab-mn-bm-hcr-fig)).  The average removals were `r sab.mn.catch.hcr` tonnes, while the median removals were `r sab.med.catch.hcr` tonnes (Figure \@ref(fig:sab-mn-c-hcr-fig)). The stock was below the LRP in `r sab.prop.yrs.bl.lrp.hcr`% of the simulated years, in the cautious zone in `r sab.prop.yrs.cautious.hcr`% of the simulated years, between the USR and the TRP in `r sab.prop.yrs.healthy.hcr`% of the simulated years, and above the TRP in `r sab.prop.yrs.above.trp.hcr`% of the simulated years (Figure \@ref(fig:sab-real-bm-hcr-fig)). This results in a bifurcation of the landings, for example, while the stock is above the USR but below the TRP, landings generally ranged from `r sab.min.healthy.zone.catch.hcr` to `r sab.max.healthy.zone.catch.hcr` tonnes, while above the TRP the landings were usually greater than `r sab.min.trp.catch.hcr` tonnes, and occasionally were more than double this (Figure \@ref(fig:sab-real-c-hcr-fig)).

For the SFA 26A HDR scenario, the median biomass (`r bbn.med.bm.hcr` tonnes) fluctuated around the TRP (Figure \@ref(fig:bbn-mn-bm-hcr-fig)). The mean removals were `r bbn.mn.catch.hcr` tonnes, while the median removals were `r bbn.med.catch.hcr` tonnes (Figure \@ref(fig:bbn-mn-c-hcr-fig)). The stock was below the LRP in `r bbn.prop.yrs.bl.lrp.hcr`% of the simulated years, it was in the cautious zone in `r bbn.prop.yrs.cautious.hcr`% of the simulated years, it was between the USR and the TRP in `r bbn.prop.yrs.healthy.hcr`% of the simulated years, and was above the TRP in `r bbn.prop.yrs.above.trp.hcr`% of the simulated years (Figure \@ref(fig:bbn-real-bm-hcr-fig)). This results in a bifurcation of the landings, for example, while the stock is above the USR but below the TRP, landings generally ranged from `r bbn.min.healthy.zone.catch.hcr` to `r bbn.max.healthy.zone.catch.hcr` tonnes, while above the TRP the landings were usually greater than `r bbn.min.trp.catch.hcr` tonnes, and occasionally were more than double this (Figure \@ref(fig:bbn-real-c-hcr-fig)).

# Conclusions

__Information to guide the development of USRs, TRPs, and RRs has been provided for each of the four areas (SFAs 25A, 26A, 26C, and 27B). For all areas, the the B~MSY~ reference points were preferred given the challenges of estimating B~0~ for stocks with an active fishery. In areas with both model based and index based reference points (SFA 25A and SFA 26A), the model based reference points were deemed to be more informative. In both modeled areas B~MSY(40)~ was preferred as the LRP as it most closely aligned with the principles of the precautionary approach. For the modeled areas, the exploration of the HDR scenarios in this document were example based; further development of this approach could take into account established or potential future management objectives. __

__For the areas with only index based reference points (SFAs 26C and 27B) B~MSY(30)~ was recommended as the LRP. This LRP was chosen because the index based reference points were more precautionary in nature (closer to the minimum observed value in the time series) than the corresponding model based reference points in areas where both sets of reference points were available. The index based methods developed to identify potential RRs were unable to disentangle  environmental and fishery impacts on the stock and were not recommended to be used to determine the RR for the index based areas.__ Finally, it is not recommended to implement both USRs and TRPs for the survey index based RPs as the potential for increased removals and a decrease in the probability of being below the LRP result from the additional HDRs being set around the TRP; development of these HDRs would be challenging given the data constraints associated with the survey index based based RPs. 

<!-- For SFA 25A, three survey index based LRPs were proposed, `r LRP.max.2.25a` tonnes (B~0(20)~), `r LRP.med.3.25a` tonnes (B~MSY(30)~), and `r LRP.med.4.25a` tonnes (B~MSY(40)~). Using the survey index based methods in SFA 25A, guidance for two USRs were provided, `r USR.max.4.25a` tonnes (B~0(40)~) and `r USR.med.8.25a` tonnes (B~MSY(80)~). There was no consistent relationship observed between biomass change and the relative exploitation rate, and thus the GEM method was unable to provide guidance for a RR~lim~. A candidate relative RR~tar~ value of `r target.rr.25a.index` was identified using the median relative exploitation rate during the five-year period with the least biomass variability observed in the survey biomass index; during these five years, growth and natural mortality were typical for the area, while recruitment was below average [@keithEvaluatingSocioeconomicConservation2020; @keyserFrameworkDevelopmentScallop2020]. -->

The MSY simulations identified three candidate model based LRPs for SFA 25A, `r sab.lrp.b0` tonnes (B~0(20)~),  `r sab.lrp.3.bmsy` tonnes (B~MSY(30)~), and `r sab.lrp.4.bmsy` tonnes (B~MSY(40)~). These simulations were also used to identify two candidate model based USRs,  `r sab.usr.b0` tonnes (B~0(40)~) and `r sab.usr.bmsy` tonnes (B~MSY(80)~), along with a candidate RR~tar~ of `r sab.rr`.  __The B~MSY(40)~ (`r sab.lrp.4.bmsy` tonnes) LRP was adopted for SFA 25A.__

<!-- For SFA 26A, three survey index based LRPs  were proposed, `r LRP.max.2.26a` tonnes (B~0(20)~),  `r LRP.med.3.26a` tonnes (B~MSY(30)~), and `r LRP.med.4.26a` tonnes (B~MSY(40)~). Using the survey index based methods in SFA 25A, guidance for two USRs were provided, `r USR.max.4.26a` tonnes (B~0(40)~) and `r USR.med.8.26a` tonnes (B~MSY(80)~). The GEM was able to identify a candidate relative RR~lim~ of `r rr.rf.26a`. In addition, a RR~tar~ value of `r target.rr.26a.index` was identified using the median relative exploitation rate during the five-year period with the least biomass variability observed in the survey biomass index; during these five years, growth was typical for the area, while recruitment and natural mortality were below average [@keithEvaluatingSocioeconomicConservation2020; @keyserFrameworkDevelopmentScallop2020].  -->

The MSY simulations identified three candidate model based LRPs for SFA 26A, `r bbn.lrp.b0` tonnes (20% of B~0~),  `r bbn.lrp.3.bmsy` tonnes (30% of B~MSY~), and `r bbn.lrp.4.bmsy` tonnes (B~MSY(40)~). These simulations were also used to identify two candidate model based USRs,  `r bbn.usr.b0` tonnes (B~0(40)~) and `r bbn.usr.bmsy` tonnes (B~MSY(80)~), along with a candidate RR~tar~ of `r bbn.rr`. __The B~MSY(40)~ (`r bbn.lrp.4.bmsy` tonnes) LRP was adopted for SFA 26A.__

For SFA 26C, three survey index based LRPs were proposed, `r LRP.max.2.26c` tonnes (B~0(20)~), `r LRP.med.3.26c` tonnes (B~MSY(30)~), and `r LRP.med.4.26c` tonnes (B~MSY(40)~). Using the survey index based methods in SFA 26C, guidance for two USRs were provided, `r USR.max.4.26c` tonnes (B~0(40)~) and `r USR.med.8.26c` tonnes (B~MSY(80)~). There was no consistent relationship observed between biomass change and the relative exploitation rate, and thus the GEM method was unable to provide guidance for a RR~lim~. A candidate RR~tar~ value of `r target.rr.26c.index` was identified using the median relative exploitation rate during the five-year period with the least biomass variability observed in the survey biomass index; during these five years growth and recruitment were typical for the area, although we note this is the shortest time series available in this analysis [ @keyserFrameworkDevelopmentScallop2020]. __The B~MSY(30)~ (`r LRP.med.3.26c` tonnes) LRP was adopted for SFA 26C.__

For SFA 27B, three survey index based LRPs were proposed, `r LRP.max.2.27b` tonnes (B~0(20)~), `r LRP.med.3.27b` tonnes (B~MSY(30)~), and `r LRP.med.4.27b` tonnes (B~MSY(40)~). Using the survey index based methods in SFA 27B, guidance for two USRs were provided, `r USR.max.4.27b` tonnes (B~0(40)~) and `r USR.med.8.27b` tonnes (B~MSY(80)~). There was no consistent relationship observed between biomass change and the relative exploitation rate, and thus the GEM method was unable to provide guidance for a RR~lim~. A candidate RR~tar~ value of `r target.rr.27b.index` was identified using the median relative exploitation rate during the five-year period with the least biomass variability observed in the survey biomass index; during these five years growth was typical for the area, while recruitment was above average [@keyserFrameworkDevelopmentScallop2020]. __The B~MSY(30)~ (`r LRP.med.3.27b` tonnes) LRP was adopted for SFA 27B.__

In case the model biomass estimates are unavailable for a model based area, the utility of using the survey biomass indices as a proxy for the stock status was also explored for the two modelled areas. In SFA 25A, the survey biomass index is highly correlated to the model biomass estimate, so the survey biomass can be used to infer stock status. In SFA 26A, while the survey index is somewhat correlated to the model biomass estimate, the differences between the two metrics can be substantial and caution is recommended if attempting to the survey biomass index as a proxy for the biomass.

The HDR scenarios were used to highlight how this approach can be used to identify candidate RR~lim~ and TRPs for the modelled areas. In both areas, the HDR scenario used reduced the probability of the stock declining below the LRP and increased the long-term average harvest levels when compared to the MSY simulation scenario that resulted in B~MSY~. This adaptive strategy accomplished this by reducing the exploitation rate in the "Healthy Zone" below the exploitation rate at B~MSY~ (which is commonly used as either the RR~lim~ or RR~tar~), while allowing removals to exceed the exploitation rate at B~MSY~ when the biomass was above the TRP.  Within the context of the DFO precautionary approach the RR~lim~ identified in these HDR simulations could serve as the maximum allowable exploitation rate which would only be applicable when the stock is above its TRP [@dfoScienceAdvicePrecautionary2021; @dfoScienceAdviceGuidance2023]. The HDR scenarios lead to much higher inter-annual variability in removals, with relatively large removals occurring approximately 50% of the time but relatively low removals in the near term as the biomass increases towards the TRP. However, the maximum removals that would be recommended when the stocks are above the USR but below the TRP are higher than the removals in recent years in SFA 25A, and similar to the recent removals in SFA 26A. Finally, more complex HDRs could be explored, such as allowing the RR~lim~ to be a function of the biomass whenever the biomass is above a TRP.

The models in SFA 25A and 26A should be subject to re-evaluation to ensure they continue to capture the population dynamics of the areas, and to monitor for changes in the productivity of each stock. It is challenging to predict when the models should next be re-evaluated as this is a function of ecological, social, and economic factors which cannot be forecast. __It is recommended to monitor the growth, _RPS_, natural mortality, and process error components of the models. A long-term directional bias in the growth, _RPS_, natural mortality, or process error would indicate a shift in the productivity of the stock. This would indicate the need for additional research to understand the processes driving the changes and may enable the development of models that attempt to account for the changes in productivity. Such a productivity shift would also impact the reference points for the area and would require additional simulation testing.__

__The methods used here relied on fishery-independent metrics (i.e., model output or survey indices).__ While reference points can be developed using fishery-dependent data, fishery-dependent methods would not be appropriate for these areas because of the rapid increase in fishery efficiency over the last two decades and the adoption of larger more powerful vessels over the last 30 years [@keithEvaluatingSocioeconomicConservation2020; @keyserFrameworkDevelopmentScallop2020]. Fishery dependent methods generally rely on using some measure of catch per unit effort (CPUE), with the underlying assumption that CPUE is proportional to the biomass of the population [@hilbornQuantitativeFisheriesStock1992]. However, when changes in fishing efficiency are driven by technological or behavioral changes, CPUE is not proportional to the population biomass, and this assumption is invalid. Using fishery-dependent methods in this context would result in a biased understanding of stock status that would result in biased science advice. 

# Research Recommendations

__There is substantial spatial and temporal (both intra- and inter-annual) variability in both growth and condition of scallop. Additional research to enhance our understanding of this variability, its causes, and the impact on the fishery and our understanding of stock status was a primary recommendation from this process. Research has begun to start to quantify this variability for Georges Bank using available port sampling data and new ageing data (see Keyser et al. in Prep for details of the Port Sampling data), however additional research will be necessary to better capture the impacts of this variability across the offshore areas.__


__For areas using index based reference points, challenges with identifying appropriate RR using the methods developed herein were noted. A general recommendation was to explore alternative methods to define the RR for the index based areas and to explore additional methods to estimate biomass based reference points (e.g., Yield per Recruit modelling) in these areas. A major challenges with the RR methods used was the inability of the methods to disentangle the importance of environmental and fishery effects on population change, future methods should attempt to overcome this limitation.__

__Understanding connectivity between these populations and with adjacent populations in other jurisdictions would enhance our understanding of the population dynamics, especially with respect to recruitment variability.  Knowledge of connectivity of sea scallop stocks within the Northwest Atlantic is an active area of research [@wyngaardenIdentifyingPatternsDispersal2017; @chenImpactLarvalBehaviors2021; @economouAssessingSpatialStructure2024]. Continued research into this  will enable the development of more advanced stock-recruitment models and enhance our understanding of the population dynamics of these stocks.__

<!-- and to monitor the survey biomass index annually to provide guidance on stock status and setting TACs. This course of action is recommend because of the strong correlation between the survey biomass index and the model results, the limited removals from the area, and the lack of a clear relationship between the exploitation rate and changes in the biomass in SFA 25A.  The could be achieved using a four-step process, 1) use the three-year geometric mean survey biomass index and the index based reference points to determine the stock status, 2) once developed, use the model based HDRs to determine the appropriate exploitation rate given stock status, 3) Divide the three-year geometric mean survey biomass index by the model catchability (`r sab.q`) to get an estimate of the total biomass, 4) multiply this q-corrected survey biomass by the exploitation rate to provide a TAC recommendation. If the three-year geometric mean survey biomass index falls below the LRP there would be no removals in the upcoming year and this would trigger a request for DFO Science to re-run the SFA 25A model and provide updated results. -->

<!-- For SFA 26A, it is recommended to continue with annual updates using a model based LRP, the recommended LRP for this are is `r bbn.lrp.b0` tonnes (20% of B~0~). We also recommend incorporating a secondary index based LRP and USR for this area. The development of these secondary reference points has two primary benefits, 1) it can help provide guidance during the setting of interim TAC's before the model is run, 2) it can be used in lieu of the model results if there are challenges with running the model in a given year. If a secondary index based LRP is adopted we recommend it to be `r LRP.med.3.26a` tonnes (30% of B~MSY~). This value was chosen because the ratio of this LRP to the biomass index is more similar to the same ratio using the model LRP and biomass estimates than the other index based LRPs. As suggested in other areas, the index based RPs should be compared the geometric mean biomass for the last three-years with data. -->

<!-- For SFA 26C, it is recommended to use the index based LRP of `r LRP.max.2.26c` tonnes (20% of B~0~). The LRP should be compared to the geometric mean biomass for the last three-years with data. The available data do not contain a great deal of information to help inform the setting of an index based Removal Reference Point, however, we do suggest the relative exploitation rate should not exceed the maximum observed relative exploitation rate in the area -->

<!-- For SFA 27B, it is recommended to use the index based LRP of `r LRP.max.2.27b` tonnes (20% of B~0~). The LRP should be compared to the geometric mean biomass for the last three-years with data. The available data do not contain a great deal of information to help inform setting an index based Removal Reference Point, however, we do suggest the relative exploitation rate should not exceed the maximum observed relative exploitation rate in the area. While it was not directly addressed within this Framework, the utility of incorporating SFA 27B into the next iteration of models developed within SFA 27 should be a research priority ahead of the next Framework for SFA 27. -->
