
```{r bbn-productivity-analysis,include=F}

# Setup...
#years <- 1994:2022
# SEAMly version
bbn.prod.dat <- data.frame(Year = years,
                        B = bbn.mod$report$totB[-length(bbn.mod$report$totB)],
                        R = bbn.mod$report$totR[-length(bbn.mod$report$totR)], # 
                        #R = bbn.mod$report$totR, # 
                        SSB = bbn.mod$report$totB[-length(bbn.mod$report$totB)] + bbn.mod$report$totR[-length(bbn.mod$report$totR)],
                        m = bbn.mod$report$mean_m[-length(bbn.mod$report$mean_m)],
                        g = c(bbn.mod$obj$env$data$g[-length(bbn.mod$obj$env$data$g)]),
                        gR = c(bbn.mod$obj$env$data$gR[-length(bbn.mod$obj$env$data$gR)]))
bbn.pd.2 <- bbn.prod.dat # For a figure later
# Make all things 2020 an NA
bbn.prod.dat[bbn.prod.dat$Year == 2020,-1] <- NA


# Now we can get common Recruitment data R3 assumes recruits are 3 year olds, r4 are 4 year olds etc.
bbn.rec.age <- 3
bbn.prod.dat$R3 <- c(bbn.prod.dat$R[(bbn.rec.age+1):nrow(bbn.prod.dat)],rep(NA,bbn.rec.age))
# Assume Scallop reach recruit size at age 3, will need to check that.
bbn.prod.dat$RPS3 <- bbn.prod.dat$R3/bbn.prod.dat$SSB 





# OK, so we see recruits are probably 3-4 years old based on that von B, 
# This really does a bang up job of showing the dampened cycles of the recruitment patters, most interesting.
p.rps.ts <- ggplot(bbn.prod.dat, aes(x=Year,y=RPS3))  + geom_point() + 
                                                    xlab("'Birth' year") + ylab("Recruits per Spawner (kg\u00B9\u22C5kg\u207B\u00B9)") +
                                                    geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 7))+
                                                    scale_y_log10() +  
                                                    scale_x_continuous(breaks = c(seq(1980,2080,by=5)))# Definitely a signal here
save_plot(paste0(bbn.plot.loc,"RPS_ts.png"),p.rps.ts,base_height =6,base_width = 10)                                               
                       
# Density dependence, clear trend with increasing RPS as SSB declines.
# Breakpoints are
bbn.rps.bp <- 11500
#sab.rps.bp2 <- 7000
p.rps.ssb <- ggplot(bbn.prod.dat,aes(y=RPS3,x=SSB)) + geom_text(aes(label = substr(Year,3,4)),size=3) + 
                                                  xlab("SSB (tonnes)") + ylab("Recruits per Spawner (kg\u00B9\u22C5kg\u207B\u00B9)") +
                                                  geom_smooth(method = 'lm') +
                                                  scale_y_log10() + 
                                                  geom_vline(xintercept = bbn.rps.bp,size=0.5,color='firebrick2',linetype='dashed')  + 
                                                  scale_x_continuous(breaks = c(seq(1000,20000,by=1500)))# Definitely a signal here
save_plot(paste0(bbn.plot.loc,"RPS_vs_SSB.png"),p.rps.ssb,base_height =6,base_width = 10)                                               
                       
# It is DK's opinion that you need to look at recruitment from a 'per capita' perspective to actually understand recruitment density dependence. But you should also look at Recruits against SSB
# amd when you do that, the most parsimonous model will ALMOST always be a flat line, but worth noting that DOES MEAN there is density dependence in here, because you are getting just as
# many recruits when the population abundance is low, so a smaller SSB is able to punch out as many recruits as a high SSB, but it DOES NOT MEAN that a traditional SR model will get you anywhere useful.
p.rec.ssb <- ggplot(bbn.prod.dat,aes(y=R3,x=SSB)) + geom_text(aes(label = substr(Year,3,4)),size=3)  +
                                                xlab("SSB (tonnes)") + ylab("Recruits (tonnes)") +
                                                geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +scale_y_log10() +
                                                geom_vline(xintercept = 11500,size=0.5,color='firebrick2',linetype='dashed')  + 
                                                scale_x_continuous(breaks = c(seq(1000,20000,by=1500)))
save_plot(paste0(bbn.plot.loc,"Rec_vs_SSB.png"),p.rec.ssb,base_height =6,base_width = 10)                                               


# Next is there any evidence of Density dependence with growth?
# Maybe a tiny bit, we don't see really high growth at high biomass, but otherwise they look similar.
# I think arguing that growth is never 'great' above 11500 (both g and gR) is a fair takeaway.
p.g.ssb <- ggplot(bbn.prod.dat,aes(y=g,x=SSB)) + geom_text(aes(label = substr(Year,3,4))) +
                                             xlab("") + ylab("Growth (Fully Recruited)") +
                                             geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +
                                             #geom_vline(xintercept = 11500,size=0.5,color='firebrick2',linetype='dashed')  + 
                                             scale_x_continuous(breaks = c(seq(1000,20000,by=1500),labels = NA))

p.gR.ssb <- ggplot(bbn.prod.dat,aes(y=gR,x=SSB)) + geom_text(aes(label = substr(Year,3,4))) +
                                             xlab("SSB (tonnes)") + ylab("Growth (Recruits)") +
                                             geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +
                                             #geom_vline(xintercept = 11500,size=0.5,color='firebrick2',linetype='dashed')  + 
                                             scale_x_continuous(breaks = c(seq(1000,20000,by=1500)))

p.gs.ssb <-  cowplot::plot_grid(p.g.ssb,p.gR.ssb,nrow=2)

save_plot(paste0(bbn.plot.loc,"Growth_vs_SSB.png"),p.gs.ssb,base_height =12,base_width = 10)                                               

#So natural mortality is never 'low' when the biomass is above either 11500 or 13000 tonnes, depending on your point of view.
# I think here using 13000 makes more sense as the high m's make a lot of sense temporally.
bbn.m.bp <- 13000
p.m.ssb <- ggplot(bbn.prod.dat,aes(y=m,x=SSB)) + geom_text(aes(label = substr(Year,3,4)))+ 
                                             xlab("SSB (tonnes)") + ylab("Natural Mortality (instantaneous)") +
                                             geom_smooth(method = 'lm') +
                                             #geom_vline(xintercept = bbn.m.bp,size=0.5,color='firebrick2',linetype='dashed')  + 
                                             scale_x_continuous(breaks = c(seq(1000,20000,by=1500)))

save_plot(paste0(bbn.plot.loc,"M_vs_SSB.png"),p.m.ssb,base_height =6,base_width = 10)                



# So there is the Density dependence analysis, For M and Growth using breakpoints makes the most sense, probably won't have a huge effect on anything 
# as there isn't a whole lot of change with SSB.  For recruits I think the bp analysis makes the most sense, but one could argue for a linear model log(R/S) ~ SSB, but my personal hot take is the linear model will not give you the large recruitment events which have only been observed
# when biomass is low... but not too low.

# Step 2.... Correlation
# Next thing you should consider is whether there are correlations in your productivity parameters, first look to autocorrelated time series
# Then you want to look for cross-correlations between mortality, recruitment, and growth, for example maybe growth is low in years when M is high
# This will matter to your simulations, so investigate it.
# First let's look for acf in our time series...
# Starting with recruitment we see there is a strong autocorrlation in the total number of recruits
p.rec.acf <- ggAcf(na.omit(bbn.prod.dat$R),lag.max = 10) + ggtitle("")+ ylab("ACF Recruits")
save_plot(paste0(bbn.plot.loc,"ACF_Rec.png"),p.rec.acf,base_height =6,base_width = 10)                

# But is this simply due to the underlying trend in R over time... no because there is no trend and it also doesn't make any difference.
rec.mod <- lm(R ~ I(Year-1993),data=bbn.prod.dat)
summary(rec.mod)
# It is not as the correlation holds
#acf(rec.mod$residuals)

# So probably better to look at per capita recruitment and see if that is a better acf'er...
# And here we do see the 1 year correlation remains, so we probably should consider some autocorrelation in the 
# RPS if possible.
p.rps.acf <- ggAcf(na.omit(log(bbn.prod.dat$RPS3)),lag.max = 10) + ggtitle("") + ylab("ACF log(RPS)")
save_plot(paste0(bbn.plot.loc,"ACF_RPS.png"),p.rps.acf,base_height =6,base_width = 10)                



# pacf shows us that we could approximate the RPS time series as an AR2, though interesting that lag 2 is significantly negative, I think that suggest a high frequency cycling of Recruitment
# so highly correlated with the following year, then it flips 2 years out to be negative for a couple years... interesting.
p.rps.pacf <- ggPacf(na.omit(log(bbn.prod.dat$RPS3)),lag.max = 10) + ggtitle("") + ylab("PACF log(RPS)")
bbn.rps.cor.1 <- round(p.rps.pacf$data$Freq[1],digits=2)
bbn.rps.cor.2 <- round(p.rps.pacf$data$Freq[2],digits=2)


save_plot(paste0(bbn.plot.loc,"PACF_RPS.png"),p.rps.pacf,base_height =6,base_width = 10)                
# On the log scale we see there is no trend in the data, there is a weak trend on the normal scale, but going to go with the log scale
rps.mod <- lm(log(RPS3) ~ I(Year-1993),data=bbn.prod.dat)
summary(rps.mod) # Indeed there is...

# How about growth, nope nothing.
p.g.pacf <- ggPacf(bbn.prod.dat$g,lag.max = 10) + ggtitle("") + ylab("PACF Growth (FR)")# No autocorrelation in growth of FR
p.gR.pacf <- ggPacf(bbn.prod.dat$g,lag.max = 10) + ggtitle("") + ylab("PACF Growth (Recruits)")# No autocorrelation in growth of Rec
p.gs.pacf <-  cowplot::plot_grid(p.g.pacf,p.gR.pacf,nrow=2)

save_plot(paste0(bbn.plot.loc,"PACF_growths.png"),p.gs.pacf,base_height =12,base_width = 10)                

# Natural morality correlation? Nothing significant, but weak autocorrelation is there, but not significant so not including it.
p.m.acf <- ggAcf(bbn.prod.dat$m,lag.max = 10) + ggtitle("") + ylab("ACF Natural Mortality") + xlab("") + scale_x_continuous(breaks = 1:14,labels=NULL) 
p.m.pacf <- ggPacf(bbn.prod.dat$m,lag.max = 10) + ggtitle("") + ylab("PACF Natural Mortality")
bbn.m.cor.1 <- 0.01 # Give it a very small value
bbn.m.cor.2 <- 0.01 # Give it a very small value
save_plot(paste0(bbn.plot.loc,"PACF_m.png"),p.m.pacf,base_height =6,base_width = 10)                
# This would be the combo of the two, but I'll just show the PACF.
#p.m.acfs <-  cowplot::plot_grid(p.m.acf,p.m.pacf,nrow=2)


# So check if there is a linear trend, and there is...
mod.m <- lm(m~I(Year-1993),data=bbn.prod.dat)
summary(mod.m) # There is a significant trend in m over time, largely due to low m in the last few years, which appears to be part of the cycling we are seeing thus I'd argue the pacf and acf above are fine.
# # So do the m residuals have acf
# m.mod.out <-  data.frame(years = c(1994:2019,2021,2022),m.res = mod.m$residuals)
# # So the correlation in the residuals isn't significant, is absolutely still a signal there, but technically isn't significant.
# pacf(m.mod.out$m.res)
# ggplot(m.mod.out,aes(x=years,y=m.res))  + geom_text(aes(label = substr(years,3,4))) + geom_smooth(method = 'loess') + xlab("") + ylab("Natural Mortality (Residual)")



# I did explore some other 'offsets' but that's a big ol' rabbit hole...
# So next up lets look for evidence of correlation between your productivity parameters, specifically RPS and m
# If we offset the RPS to the year they are actually showing up, either the model is trying to kill more over everything when we have a lot of recruits, or there is a real 
# relationship there.
bbn.prod.dat$RPS3_offset <- c(rep(NA,3),bbn.prod.dat$RPS3[-((length(bbn.prod.dat$RPS3)-2):length(bbn.prod.dat$RPS3))])

p.rpsoff.m <- ggplot(bbn.prod.dat,aes(x=Year,y=RPS3_offset)) + geom_text(aes(label = substr(Year-5,3,4)))  + 
                                                           xlab("") +ylab("RPS (kg\u00B9\u22C5kg\u207B\u00B9) & Natural mortality (Inst)") +
                                                           geom_line(aes(y = m),color='firebrick2',size=1,linetype='dashed')
# There is clearly a correlation at a lag of 1 year
p.rps.m.ccf <- ggCcf(bbn.prod.dat$RPS3_offset,bbn.prod.dat$m,lag.max = 10) + ggtitle("") #Needs to be RPS first to align with the simulations
p.rps.m.ccf.combo <-  cowplot::plot_grid(p.rpsoff.m,p.rps.m.ccf,nrow=2)
# Peak cross correlation...
bbn.m.rps.lag <- p.rps.m.ccf$data$lag[which(abs(p.rps.m.ccf$data$Freq) == abs(max(p.rps.m.ccf$data$Freq)))]
bbn.m.rps.cor <- round(p.rps.m.ccf$data$Freq[p.rps.m.ccf$data$lag == bbn.m.rps.lag],digits=2)

save_plot(paste0(bbn.plot.loc,"CCF_ts_RPS_offset_m.png"),p.rps.m.ccf.combo,base_height =12,base_width = 10)                
      
# The final plot I want to show here is the correlation between the model estimate and the survey index.
# These will be aligned so don't need to get too fancy
med.q <- median(bbn.mod$report$qI)
mod.index.bm <- data.frame(year = bbn.prod.dat$Year,mod.bm = bbn.prod.dat$B,index.bm = surv.26a$I)
bbn.cor.q.bm <- signif(cor(mod.index.bm$mod.bm , mod.index.bm$index.bm,use= 'complete.obs'),digits=2)


p.bbn.mod.ind.bm <-ggplot(mod.index.bm) + geom_text(aes(x=index.bm,y=mod.bm,label = substr(year,3,4))) +
                                          scale_x_continuous(name="Survey Biomass Index (tonnes)") +
                                          scale_y_continuous(name="Model Biomass (tonnes)") +
                                          geom_abline(slope=1,intercept=0)
save_plot(paste0(bbn.plot.loc,"Model_vs_index_biomass.png"),p.bbn.mod.ind.bm,base_height =6,base_width = 10)   
```




```{r bbn-productivity-simulations,include=F}
# Set the seed so we can repeat these simulations!
set.seed(1)
g.strat <- list(type = "bp",bp = 1e99, strat = 'dist',cen.tend='mean')#, mn.mx = 1.05, sd.mx = 0.05) 
r.strat <- list(type = "cor",strat = 'dist', bp = bbn.rps.bp,rec.age=bbn.rec.age, cen.tend = 'mean',
                              ar1=bbn.rps.cor.1,ar2=bbn.rps.cor.2,rps.m.cor = bbn.m.rps.cor,rps.m.lag = bbn.m.rps.lag,
                              mn.at.max = min(bbn.prod.dat$RPS3,na.rm=T),sd.at.max = 0.1) 
m.strat <- list(type = "cor",strat = 'dist', bp = 1e99,ar1=bbn.m.cor.1,ar2=bbn.m.cor.2,cen.tend='median')  
mod.4.bbn = "SEAM"
bbn.exp.scenario <- seq(0,0.1,0.005)
#bbn.model.yrs <- years
bbn.max.SSB <- floor(max(bbn.prod.dat$SSB/100,na.rm=T)) * 100
# Run projection
if(run.sims == T)
{
bbn.res <- proj.mod(mods = list(seam.mod = bbn.mod),n_sim=n_sims,n_y = n_y,model=mod.4.bbn,model.yrs = bbn.model.yrs,
                plot_url = plot.bbn.rp.mod.loc, run = 'no_model_error', res_url = res.bbn.rp.mod.loc,save.results = T, 
                exp.scenario=bbn.exp.scenario, 
                g.mod =   list(type = g.strat$type,bp.strategy = g.strat$strat,bp= g.strat$bp,set.g = g.strat$set.g,cen.tend = g.strat$cen.tend),
                               #mn.at.max = g.strat$mn.at.max,sd.at.max =g.strat$sd.at.max), 
                rec.mod = list(type = r.strat$type,bp.strategy = r.strat$strat,bp= r.strat$bp, 
                               rec.age = r.strat$rec.age,rps.m.cor = r.strat$rps.m.cor,rps.m.lag = r.strat$rps.m.lag,cen.tend = r.strat$cen.tend,
                               ar1=r.strat$ar1,ar2=r.strat$ar2,
                               mn.at.max = r.strat$mn.at.max,sd.at.max =r.strat$sd.at.max), 
                m.mod =   list(type = m.strat$type,bp.strategy = m.strat$strat,bp= m.strat$bp, cen.tend = m.strat$cen.tend,#mn.at.max = m.strat$mn.mx,sd.at.max = m.strat$sd.mx,
                                ar1=m.strat$ar1,ar2=m.strat$ar2))#,
saveRDS(bbn.res,paste0(res.bbn.rp.mod.loc,"full_bmsy_sims_",min(bbn.model.yrs),"-",max(bbn.model.yrs)))
} # end if run.sims == T
if(run.sims == F) bbn.res <- readRDS(paste0(res.bbn.rp.mod.loc,"full_bmsy_sims_",min(bbn.model.yrs),"-",max(bbn.model.yrs)))

bbn.Exp.res <- bbn.res$Exp.res
# End RUNME
# Here are our reference point options
# Exp.res <- readRDS("D:/Framework/SFA_25_26_2024/RefPts/Results/BBn/R_75_FR_90/SEAM_1994_2022_vary_m_m0_0.2_qR_0.33_20_knots_g_original_vary_q=TRUE/RPs/SEAM_g_sv__1_dist_1_0.05_r_bp_dist_11500__0.00041_0.23_m_bp_dist_11500__0.184_0.1.Rds")
# summary(bbn.prod.dat$R)
# summary(c(Res$Rec[,1:10,1]))
# summary(bbn.prod.dat$m)
# summary(c(Res$mort[,1:5,1]))
# summary(c(Res$rps[,1:5,1]))
# summary(bbn.prod.dat$RPS3)
# 
# 
# plot(Res$rps[,1,1],Res$rps.cor.ts[,1,1])
# plot(Res$mort[,1,1],Res$m.cor.ts[,1,1])
# Res$B[,1,1]
# plot(Res$Rec[,1,1],type='l')
# plot(Res$mort[,1,1],type='l')
# ccf(Res$rps[,3,1],Res$mort[,3,1])
# pacf(Res$rps[,2,1])
# pacf(Res$rps[,1,1])
# 
# plot(Res$m.cor.ts[,10,1],Res$rps[,10,1])
# plot(bbn.prod.dat$RPS3,bbn.prod.dat$m)
# 
# plot(y=bbn.prod.dat$RPS3,x=bbn.prod.dat$SSB)
# plot(y=Res$rps[4:100,5,1], x=Res$B[1:97,5,1]+Res$R[1:97,5,1],type='p')

bbn.RPs <- bbn.Exp.res |>collapse::fsubset(year >= n_y-last.yrs) |> collapse::fgroup_by(F.scenario) |> collapse::fsummarize(med.B = median(B,na.rm=T),
                                                                                                       mn.B = median(B,na.rm=T),
                                                                                                       med.C = median(Catch,na.rm=T),
                                                                                                       mn.C = mean(Catch,na.rm=T))  

bbn.c.at.msy <- max(bbn.RPs$med.C)
#bbn.c.at.msy <- max(bbn.RPs$mn.C)
# Numbers for the paper
bbn.rr <- bbn.RPs$F.scenario[bbn.RPs$med.C == bbn.c.at.msy] 
bbn.bmsy <- round(bbn.RPs$med.B[bbn.RPs$med.C == bbn.c.at.msy],digits=-2)
bbn.b0 <- round(bbn.RPs$med.B[bbn.RPs$F.scenario==0],digits=-2)

# I could round this up to 200, but will leave it at 195...
bbn.c.at.msy <- round(bbn.c.at.msy,digits=0)
# So our LRP options
bbn.lrp.b0 <- 0.2 * bbn.b0
bbn.lrp.3.bmsy <- 0.3 * bbn.bmsy
bbn.lrp.4.bmsy <- 0.4 * bbn.bmsy
# USR and TRP 
bbn.usr.b0 <- 0.4 * bbn.b0
bbn.usr.bmsy <- 0.8 * bbn.bmsy
bbn.trp.bmsy <- bbn.bmsy
bbn.trp.b0 <- 0.8 * bbn.b0


bbn.res.at.rr.last.yrs <- bbn.Exp.res[bbn.Exp.res$F.scenario==bbn.rr & bbn.Exp.res$year > (n_y-last.yrs),]
# We can estimate the proportion of the time the stocks are in the critical, cautious, and healthy zones in the last 100 years of the simulations
bbn.prop.yrs.critical <- round(100*length(which(bbn.res.at.rr.last.yrs$B < bbn.lrp.4.bmsy))/n_sims/last.yrs,digits=1)
bbn.prop.yrs.cautious <- round(100*length(which(bbn.res.at.rr.last.yrs$B >= bbn.lrp.4.bmsy & bbn.res.at.rr.last.yrs$B < bbn.usr.bmsy))/n_sims/last.yrs,digits=1)
bbn.prop.yrs.healthy <- round(100*length(which(bbn.res.at.rr.last.yrs$B >= bbn.usr.bmsy))/n_sims/last.yrs,digits=1)

# How long does it take to 'rebuild'

sim.years <- sort(unique(bbn.Exp.res$year))
F.scenario <- sort(unique(bbn.Exp.res$F.scenario))

time.grid <- expand.grid(scenario = F.scenario,years = sim.years)
time.to <- data.frame(time.grid,Biomass = NA, T.msy = F,T.usr = F, T.lrp=F,T.trp = F)
for(i in sim.years)
{
B.now <- bbn.Exp.res %>% dplyr::filter(year %in% i) %>% collapse::fgroup_by(F.scenario) %>% collapse::fsummarize(med.B = median(B,na.rm=T))
time.to$Biomass[time.to$years == i] <- B.now$med.B
# This feels way clunky...
if(any(B.now$med.B >= bbn.bmsy)) 
{
  trues <- which(B.now$med.B >= bbn.bmsy)
  tmp <- time.to$T.msy[time.to$years == i]
  tmp[trues] <- T
  time.to$T.msy[time.to$years == i] <- tmp
}
if(any(B.now$med.B >= bbn.usr.bmsy))
{
  trues <- which(B.now$med.B >= bbn.usr.bmsy)
  tmp <- time.to$T.usr[time.to$years == i]
  tmp[trues] <- T
  time.to$T.usr[time.to$years == i] <- tmp
}
if(any(B.now$med.B >= bbn.lrp.4.bmsy))
{
  trues <- which(B.now$med.B >= bbn.lrp.4.bmsy)
  tmp <- time.to$T.lrp[time.to$years == i]
  tmp[trues] <- T
  time.to$T.lrp[time.to$years == i] <- tmp
}
if(any(B.now$med.B >= bbn.trp.bmsy))
{
  trues <- which(B.now$med.B >= bbn.trp.bmsy)
  tmp <- time.to$T.trp[time.to$years == i]
  tmp[trues] <- T
  time.to$T.trp[time.to$years == i] <- tmp
}
}

# If the stock is currently above the reference point you want these to =F, if it's below the reference point you want these to = T
bbn.res.T.msy <- time.to |> collapse::fsubset(T.msy == F) |> collapse::fgroup_by(scenario) |> collapse::fselect(scenario,years,Biomass,T.msy) 
bbn.res.T.usr <- time.to |> collapse::fsubset(T.usr == F) |> collapse::fgroup_by(scenario) |> collapse::fselect(scenario,years,Biomass,T.usr) 
bbn.res.T.lrp <- time.to |> collapse::fsubset(T.lrp == F) |> collapse::fgroup_by(scenario) |> collapse::fselect(scenario,years,Biomass,T.lrp) 
bbn.res.T.trp <- time.to |> collapse::fsubset(T.trp == T) |> collapse::fgroup_by(scenario) |> collapse::fselect(scenario,years,Biomass,T.trp) 
# So now summarize these...

bbn.T.msy <- bbn.res.T.msy %>% collapse::fgroup_by(scenario) %>% collapse::fsummarize(T.msy = min(years))
bbn.T.usr <- bbn.res.T.usr %>% collapse::fgroup_by(scenario) %>% collapse::fsummarize(T.usr = min(years))
bbn.T.lrp <- bbn.res.T.lrp %>% collapse::fgroup_by(scenario) %>% collapse::fsummarize(T.lrp = min(years)) # Hmm...
bbn.T.trp <- bbn.res.T.trp %>% collapse::fgroup_by(scenario) %>% collapse::fsummarize(T.trp = min(years)) # This tells me that TRP is really unachievable

# Figures from this...

# Show that the time series we're provided have similar characteristics to the input time series.
# Given the crazy high volume of these, I show the results for the BMSY scenario.
bbn.res.4.plts <- bbn.Exp.res |> collapse::fsubset(F.scenario == bbn.rr & Sim <= n_sims)

# Here are the growth time series.
bbn.rp.sim.g.plt <- ggplot(bbn.res.4.plts) + geom_line(aes(x=year,y=g,group=Sim),alpha=0.02)
bbn.rp.sim.gR.plt <- ggplot(bbn.res.4.plts) + geom_line(aes(x=year,y=gR,group=Sim),alpha=0.02)
bbn.rp.sim.m.plt <- ggplot(bbn.res.4.plts) + geom_line(aes(x=year,y=M,group=Sim),alpha=0.02) 

# Extract the lag 1 ACF for each of the productivity parameters... 
bbn.cor.res <- data.frame(g.cor = NA, gr.cor=NA,m.acf.ar1 = NA,m.acf.ar2 = NA,rps.ar1 = NA,rps.ar2 = NA,rps.m.cor = NA)
g.acf.all <- gr.acf.all <- m.acf.all <- rps.acf.all <- rps.m.ccf.all <- NULL
max.lag <- 10
for(i in 1:n_sims)
{
  rps.dat <- bbn.res$rps[,i,which(F.scenario == bbn.rr)]
  dat <- bbn.res.4.plts |> collapse::fsubset(Sim == i)
  g.acf.all[[i]] <- ggPacf(dat$g,lag.max = max.lag,plot=F)$acf
  m.acf.all[[i]] <- ggPacf(dat$M,lag.max = max.lag,plot=F)$acf
  gr.acf.all[[i]] <- ggPacf(dat$gR,lag.max = max.lag,plot=F)$acf
  rps.acf.all[[i]] <- ggPacf(rps.dat,lag.max = max.lag,plot=F)$acf
  rps.m.ccf.all[[i]] <- ggCcf(rps.dat,dat$M,lag.max = max.lag,plot=F)$acf
  g.acf <- g.acf.all[[i]][1]
  gr.acf <- gr.acf.all[[i]][1]
  m.acf.ar1 <- m.acf.all[[i]][1]
  m.acf.ar2 <- m.acf.all[[i]][2]
  rps.acf.ar1 <- rps.acf.all[[i]][1]
  rps.acf.ar2 <- rps.acf.all[[i]][2]
  rsp.m.ccf <-  rps.m.ccf.all[[i]][max.lag+bbn.m.rps.lag+1] # This gets the right lag almost magically.
  
  tmp <- data.frame(g.cor = g.acf, gr.cor=gr.acf,m.acf.ar1=m.acf.ar1,m.acf.ar2 =m.acf.ar2,rps.ar1 = rps.acf.ar1,rps.ar2 = rps.acf.ar2,rps.m.cor = rsp.m.ccf)
  bbn.cor.res[i,] <- tmp
}

g.sim.pacf <- data.frame(dat = colMeans(do.call('rbind',g.acf.all)),lag=1:max.lag)
gr.sim.pacf <- data.frame(dat = colMeans(do.call('rbind',gr.acf.all)),lag=1:max.lag)
m.sim.pacf <- data.frame(dat = colMeans(do.call('rbind',m.acf.all)),lag=1:max.lag)
rps.sim.pacf <- data.frame(dat = colMeans(do.call('rbind',rps.acf.all)),lag=1:max.lag)
rps.m.sim.ccf <- data.frame(dat = colMeans(do.call('rbind',rps.m.ccf.all)),lag=-max.lag:max.lag)

# So we retained the correlation structure for the most part, though it was generally weaker than what we observed in the time series.
bbn.cor.sim.summary <- data.frame(t(round(colMeans(as.matrix(bbn.cor.res)),digits=2)))

```




```{r special-bbn-prod-sims-figs,include =F}
# PACF plots for the productivity parameters from the simulations.
max.abs <- max(abs(bbn.cor.sim.summary),na.rm=T)
bbn.g.sim.cor.plt <- ggplot(g.sim.pacf,mapping=aes(x=lag,y=dat)) + geom_segment(mapping=aes(xend=lag,yend=0)) + geom_hline(yintercept=0) + 
                                              scale_y_continuous(name = "Mean PACF (fully-recruited growth)",limits = c(-max.abs,max.abs))+ 
                                              scale_x_continuous(name = "",breaks = 1:max.lag,labels = NULL)
bbn.gr.sim.cor.plt <-ggplot(gr.sim.pacf,mapping=aes(x=lag,y=dat)) + geom_segment(mapping=aes(xend=lag,yend=0)) + geom_hline(yintercept=0) + 
                                               scale_y_continuous(name = "Mean PACF (Recruit growth)",limits = c(-max.abs,max.abs))+ 
                                               scale_x_continuous(name = "",breaks = 1:max.lag,labels = NULL)

bbn.m.sim.cor.plt <-ggplot(m.sim.pacf,mapping=aes(x=lag,y=dat)) + geom_segment(mapping=aes(xend=lag,yend=0)) + geom_hline(yintercept=0) + 
                                              scale_y_continuous(name = "Mean PACF (Natural mortality)",limits = c(-max.abs,max.abs))+ 
                                              scale_x_continuous(name = "Lag",breaks = 1:max.lag)

bbn.rps.sim.cor.plt <-ggplot(rps.sim.pacf,mapping=aes(x=lag,y=dat)) + geom_segment(mapping=aes(xend=lag,yend=0)) + geom_hline(yintercept=0) + 
                                                scale_y_continuous(name = "Mean PACF (RPS)",limits = c(-max.abs,max.abs))+ 
                                                scale_x_continuous(name = "Lag",breaks = 1:max.lag)

bbn.sim.cors.plt <- plot_grid(bbn.g.sim.cor.plt,bbn.gr.sim.cor.plt,bbn.m.sim.cor.plt,bbn.rps.sim.cor.plt)
save_plot(bbn.sim.cors.plt,file = paste0(plot.bbn.rp.mod.loc,min(bbn.model.yrs),"-",max(bbn.model.yrs),"/PACF_sim_correlation.png"),base_height = 11,base_width=8.5)

# The cross correlations is it's own figure.
bbn.rps.m.sim.cor.plt <-ggplot(rps.m.sim.ccf,mapping=aes(x=lag,y=dat)) + geom_segment(mapping=aes(xend=lag,yend=0)) + geom_hline(yintercept=0) + 
                                                scale_y_continuous(name = "Mean CCF (M vs. RPS)",limits = c(-max.abs,max.abs))+ 
                                                scale_x_continuous(name = "Lag",breaks = -max.lag:max.lag)
save_plot(bbn.rps.m.sim.cor.plt,file = paste0(plot.bbn.rp.mod.loc,min(bbn.model.yrs),"-",max(bbn.model.yrs),"/CCF_sim_correlation.png"),base_height = 8.5,base_width=8.5)



# The density dependence from the simulations...
bbn.res.4.plts$SSB <- bbn.res.4.plts$B + bbn.res.4.plts$Rec


# To get the RPS offset right I need to loop-d-loo

for(i in 1:n_sims)
{
  tmp <- bbn.res.4.plts[bbn.res.4.plts$Sim == i,]
  tmp$rps.offset <- c(tmp$rps[(bbn.rec.age+1):nrow(tmp)],rep(NA,bbn.rec.age))
  bbn.res.4.plts$rps.offset[bbn.res.4.plts$Sim == i] <- tmp$rps.offset
}

# Set the alpha level for the lines on the figures showing the individual realizations.
if(n_sims <= 10) alphs <- 0.5
if(n_sims > 10) alphs <- 0.1
if(n_sims > 100) alphs <- 1/255

#Figures
bbn.prod.sum <- data.frame(mn.g.obs = mean(bbn.prod.dat$g,na.rm=T),mn.g.sim = mean(bbn.res.4.plts$g),
                           mn.gR.obs = mean(bbn.prod.dat$gR,na.rm=T),mn.gR.sim = mean(bbn.res.4.plts$gR),
                           med.m.obs = median(bbn.prod.dat$m,na.rm=T),med.m.sim = median(bbn.res.4.plts$M),
                           mn.rps.obs = mean(bbn.prod.dat$RPS3,na.rm=T),mn.rps.sim = mean(bbn.res.4.plts$rps))

bbn.g.sim.comp.plt <- ggplot(bbn.res.4.plts) + geom_point(aes(x=SSB/1000,y=g),alpha=alphs,shape=21,fill='black',stroke=NA)  +
                         geom_hline(yintercept = bbn.prod.sum$mn.g.obs,color='blue',linetype='dashed')+
                         geom_hline(yintercept = bbn.prod.sum$mn.g.sim,color='blue',linetype='solid')+
                         scale_x_continuous(name="",labels = NULL,limits=c(0,25)) +
                         scale_y_continuous(name=("Fully-recruited growth"))

bbn.gr.sim.comp.plt <- ggplot(bbn.res.4.plts) + geom_point(aes(x=SSB/1000,y=gR),alpha=alphs,shape=21,fill='black',stroke=NA) +
                         geom_hline(yintercept = bbn.prod.sum$mn.gR.obs,color='blue',linetype='dashed')+
                         geom_hline(yintercept = bbn.prod.sum$mn.gR.sim,color='blue',linetype='solid')+
                         scale_x_continuous(name="",labels = NULL,limits=c(0,25)) +
                         scale_y_continuous(name=("Recruit growth"))

# The really low RPS values are because of the correlation, they happen after most of the really large recruitment years, so are due to the large negative lag 2 rps, ha!
bbn.rps.sim.comp.plt <- ggplot(bbn.res.4.plts) + geom_point(aes(x=SSB/1000,y=rps.offset),alpha=alphs,shape=21,fill='black',stroke=NA) + 
                         geom_vline(xintercept = bbn.rps.bp/1000,color='firebrick2',linetype='solid') +
                         geom_hline(yintercept = bbn.prod.sum$mn.rps.obs,color='blue',linetype='dashed')+
                         geom_hline(yintercept = bbn.prod.sum$mn.rps.sim,color='blue',linetype='solid')+
                         scale_x_continuous(name="",limits=c(0,25)) +
                         scale_y_log10(name=("Recruits per Spawner (kg\u00B9\u22C5kg\u207B\u00B9)"))

bbn.m.sim.comp.plt <- ggplot(bbn.res.4.plts) + geom_point(aes(x=SSB/1000,y=M),alpha=alphs,shape=21,fill='black',stroke=NA) + 
                         #geom_vline(xintercept = bbn.max.SSB/1000,color='red',linetype='solid') +
                         geom_hline(yintercept = bbn.prod.sum$med.m.obs,color='blue',linetype='dashed')+
                         geom_hline(yintercept = bbn.prod.sum$med.m.sim,color='blue',linetype='solid')+
                         scale_x_continuous(name="",limits=c(0,25)) +
                         scale_y_continuous(name=("Natural mortality (instantaneous)"))

bbn.sim.comps.plt <- plot_grid(bbn.g.sim.comp.plt,bbn.gr.sim.comp.plt,bbn.rps.sim.comp.plt,bbn.m.sim.comp.plt)
bbn.sim.comps.plt2 <- add_sub(bbn.sim.comps.plt, "SSB (tonnes x 1000)",angle=0,y=1.4,x=0.55,size=24)

save_plot(bbn.sim.comps.plt2,file = paste0(plot.bbn.rp.mod.loc,min(bbn.model.yrs),"-",max(bbn.model.yrs),"/Sim_paramter_DD.png"),base_height = 11,base_width=8.5)

# Figure showing the model reference points and the biomass trends from the model.

bbn.mod.rp.plt <- ggplot(bbn.prod.dat) + geom_line(aes(x=Year,y=B/1000)) + 
                       geom_hline(yintercept = bbn.lrp.b0/1000,color='firebrick2',linetype='solid') +
                       geom_hline(yintercept = bbn.lrp.3.bmsy/1000,color='firebrick2',linetype = 'dotted') +
                       geom_hline(yintercept = bbn.lrp.4.bmsy/1000,color='firebrick2',linetype='dashed') +
                       geom_hline(yintercept = bbn.usr.b0/1000,color=u.colors[2],linetype = 'solid') +
                       geom_hline(yintercept = bbn.usr.bmsy/1000,color=u.colors[2],linetype='dashed') +
                       geom_hline(yintercept = bbn.bmsy/1000,color=u.colors[1],linetype='solid',size=1.5) +
                       scale_x_continuous('',breaks=seq(1990,2030,by=3)) +
                       scale_y_continuous('Fully-recruited Biomass (tonnes x 1000)',limits=c(0,NA)) 

save_plot(bbn.mod.rp.plt,file = paste0(plot.bbn.rp.mod.loc,min(bbn.model.yrs),"-",max(bbn.model.yrs),"/Sim_RPs.png"),base_height = 8.5,base_width=8.5)

bbn.med.B.4.plt <- bbn.res.4.plts |> collapse::fgroup_by(year) |> collapse::fsummarise(B.med = median(B,na.rm=T))

bbn.mod.real.plt <- ggplot(bbn.res.4.plts) + geom_line(aes(x=year,y=B/1000,group=Sim),alpha=alphs) + 
                       geom_line(data = bbn.med.B.4.plt,aes(x=year,y=B.med/1000),color='black',size=1.25) + 
                       #geom_hline(yintercept = bbn.lrp.b0/1000,color='firebrick2',linetype='solid',size=1.5) +
                       #geom_hline(yintercept = bbn.lrp.3.bmsy/1000,color='firebrick2',linetype = 'dotted') +
                       geom_hline(yintercept = bbn.lrp.4.bmsy/1000,color='firebrick2',linetype='dashed') +
                       #geom_hline(yintercept = bbn.usr.b0/1000,color=u.colors[2],linetype = 'solid',size=1.5) +
                       geom_hline(yintercept = bbn.usr.bmsy/1000,color=u.colors[2],linetype='dashed') +
                       #geom_hline(yintercept = bbn.bmsy/1000,color=u.colors[1],linetype='solid',size=1.5) +
                       scale_x_continuous('') +
                       scale_y_continuous('Fully-recruited Biomass (tonnes x 1000)') +
                       theme(legend.position = "none")

save_plot(bbn.mod.real.plt,file = paste0(plot.bbn.rp.mod.loc,min(bbn.model.yrs),"-",max(bbn.model.yrs),"/Sim_reals_w_RPS.png"),base_height = 8.5,base_width=8.5)




```

```{r bbn-sab-4-sar,include =F}

bbn.mod.rp.plt.4.sar <- ggplot(bbn.pd.2) + geom_line(aes(x=Year,y=B/1000)) + 
                       #geom_hline(yintercept = bbn.lrp.b0/1000,color='firebrick2',linetype='solid') +
                       #geom_hline(yintercept = bbn.lrp.3.bmsy/1000,color='firebrick2',linetype = 'dotted') +
                       geom_hline(yintercept = bbn.lrp.4.bmsy/1000,color='firebrick2',linetype='dashed') +
                       #geom_hline(yintercept = bbn.usr.b0/1000,color=u.colors[2],linetype = 'solid') +
                       #geom_hline(yintercept = bbn.usr.bmsy/1000,color=u.colors[2],linetype='dashed') +
                       #geom_hline(yintercept = bbn.bmsy/1000,color=u.colors[1],linetype='solid',size=1.5) +
                       scale_x_continuous('',breaks=seq(1990,2030,by=3)) +
                       scale_y_continuous('',limits=c(0,NA)) 

#save_plot(bbn.mod.rp.plt.4.sar,file = paste0(plot.bbn.rp.mod.loc,min(bbn.model.yrs),"-",max(bbn.model.yrs),"/Sim_RPs_4_SAR.png"),base_height = 8.5,base_width=8.5)


sab.mod.rp.plt.4.sar <- ggplot(sab.prod.dat) + geom_line(aes(x=Year,y=B/1000)) + 
                       #geom_hline(yintercept = sab.lrp.b0/1000,color='firebrick2',linetype='solid') +
                       #geom_hline(yintercept = sab.lrp.3.bmsy/1000,color='firebrick2',linetype = 'dotted') +
                       geom_hline(yintercept = sab.lrp.4.bmsy/1000,color='firebrick2',linetype='dashed') +
                       #geom_hline(yintercept = sab.usr.b0/1000,color=u.colors[2],linetype = 'solid') +
                       #geom_hline(yintercept = sab.usr.bmsy/1000,color=u.colors[2],linetype='dashed') +
                       #geom_hline(yintercept = sab.bmsy/1000,color=u.colors[1],linetype='solid',size=1.5) +
                       scale_x_continuous('',breaks=seq(1990,2030,by=3)) +
                       scale_y_continuous('Fully-recruited Biomass (tonnes x 1000)',limits = c(0,NA)) 

# Now combine the figures into one for the SAR

rp.fig.4.sar <- cowplot::plot_grid(sab.mod.rp.plt.4.sar,bbn.mod.rp.plt.4.sar,ncol=2,labels = c("SFA 25A","SFA 26A"),label_size=14,label_y=0.95,label_x=0.15)

save_plot(rp.fig.4.sar,file = paste0(rp.loc,"Figures/Sim_BBn_and_Sab_RP_4_SAR.png"),base_height = 8.5,base_width=16)
```



```{r bbn-hcr-sims,include =F}

# HCR specific settings
set.seed(3)
bbn.trp.exp <- 0.07
bbn.usr.exp <- 0.03
bbn.lrp.exp <- 0
bbn.exp.sd <- 0.1

hcr.strat <-list(TRP = bbn.trp.bmsy,TRP.exp = bbn.trp.exp,
                 USR = bbn.usr.bmsy, USR.exp = bbn.usr.exp, 
                 LRP = bbn.lrp.4.bmsy, LRP.exp = bbn.lrp.exp,exp.sd = bbn.exp.sd)
bbn.HCR <- paste0("T_",hcr.strat$TRP,"_",hcr.strat$TRP.exp,"_U_",hcr.strat$USR,"_",hcr.strat$USR.exp,"_L_",hcr.strat$LRP,"_",hcr.strat$LRP.exp)
bbn.hcr.plt.loc <- paste0(plot.bbn.rp.mod.loc,"HCR/",bbn.HCR,"/")
bbn.hcr.res.loc <- paste0(res.bbn.rp.mod.loc,"HCR/",bbn.HCR,".Rds")

# An HCR model
if(run.sims == T)
{
bbn.hcr <- proj.mod(mods = list(seam.mod = bbn.mod),n_sim=n_sims,n_y = n_y,model=mod.4.bbn, run = 'no_model_error',
                plot_url = plot.bbn.rp.mod.loc,  res_url = res.bbn.rp.mod.loc,save.results = T,
                g.mod =   list(type = g.strat$type,bp.strategy = g.strat$strat,bp= g.strat$bp,set.g = g.strat$set.g,cen.tend = g.strat$cen.tend),
                               #mn.at.max = g.strat$mn.at.max,sd.at.max =g.strat$sd.at.max), 
                rec.mod = list(type = r.strat$type,bp.strategy = r.strat$strat,bp= r.strat$bp, 
                               rec.age = r.strat$rec.age,rps.m.cor = r.strat$rps.m.cor,rps.m.lag = r.strat$rps.m.lag,cen.tend = r.strat$cen.tend,
                               ar1=r.strat$ar1,ar2=r.strat$ar2,
                               mn.at.max = r.strat$mn.at.max,sd.at.max =r.strat$sd.at.max), 
                m.mod =   list(type = m.strat$type,bp.strategy = m.strat$strat,bp= m.strat$bp, cen.tend = m.strat$cen.tend,#mn.at.max = m.strat$mn.mx,sd.at.max = m.strat$sd.mx,
                                ar1=m.strat$ar1,ar2=m.strat$ar2),
                HCR.sim = list(TRP = hcr.strat$TRP,TRP.exp = hcr.strat$TRP.exp, USR = hcr.strat$USR, USR.exp = hcr.strat$USR.exp,
                                    LRP = hcr.strat$LRP, LRP.exp = hcr.strat$LRP.exp,exp.sd = hcr.strat$exp.sd))
bbn.hcr <- bbn.hcr$Exp.res

}
if(run.sims == F) bbn.hcr <- readRDS(bbn.hcr.res.loc)

# For this I need to use the summarized object
bbn.hcr.last.yrs <- bbn.hcr[bbn.hcr$year > (n_y-last.yrs),]
bbn.mn.catch.hcr <- round(mean(bbn.hcr.last.yrs$Catch,na.rm=T),digits=0)
bbn.med.catch.hcr <- round(median(bbn.hcr.last.yrs$Catch,na.rm=T),digits=0)
bbn.med.bm.hcr <- round(median(bbn.hcr.last.yrs$B),digits=0)
bbn.mn.bm.hcr <- round(mean(bbn.hcr.last.yrs$B),digits=0)
bbn.prop.yrs.bl.lrp.hcr <- round(100*length(which(bbn.hcr.last.yrs$B < bbn.lrp.4.bmsy))/n_sims/last.yrs,digits=1)

bbn.prop.yrs.cautious.hcr <- round(100*length(which(bbn.hcr.last.yrs$B >= bbn.lrp.4.bmsy & bbn.hcr.last.yrs$B < bbn.usr.bmsy))/n_sims/last.yrs,digits=1)
bbn.prop.yrs.healthy.hcr <- round(100*length(which(bbn.hcr.last.yrs$B >= bbn.usr.bmsy & bbn.hcr.last.yrs$B < bbn.trp.bmsy))/n_sims/last.yrs,digits=1)
bbn.prop.yrs.above.trp.hcr <- round(100*length(which(bbn.hcr.last.yrs$B > bbn.trp.bmsy))/n_sims/last.yrs,digits=1)

bbn.min.healthy.zone.catch.hcr <- bbn.usr.bmsy*bbn.usr.exp
bbn.max.healthy.zone.catch.hcr <- bbn.trp.bmsy*bbn.usr.exp
bbn.min.trp.catch.hcr <- bbn.trp.bmsy*bbn.trp.exp
bbn.catch.quants.hcr <- quantile(bbn.hcr$Catch,na.rm=T,probs = seq(0,1,by=0.01))

```


