```{r indices-analysis,include=F,warning=F}
# Get the median, maximum, and maximum 3 year rolling mean, then get the LRP and USR from those
# SFA 25A
surv.25a <- survey.obj$Sab$model.dat
surv.25a <- surv.25a |> collapse::fsubset(year >=1994)
surv.25a <- rbind(surv.25a,c(2020,rep(NA,ncol(surv.25a)-1)))
surv.25a <- rbind(surv.25a,c(2015,rep(NA,ncol(surv.25a)-1)))
surv.25a <- surv.25a[order(surv.25a$year),] # get the years ordered correctly for the rolling mean
# q correct
surv.25a$I <- surv.25a$I/q.index
surv.25a$IR <- surv.25a$IR/q.index
gmean.25a <- exp(mean(log(surv.25a$I),na.rm=T))
max.25a <- max(surv.25a$I,na.rm=T)
# Geometric rolling mean
ma.three.mean.25a <- exp(c(na.omit(rollmean(log(na.omit(surv.25a$I)),3,'center'))))
max.three.25a <- max(ma.three.mean.25a,na.rm=T)
# Doing this with the last 3 years of data available, so if missing a survey we go back and use the information from the year before that

bm.last.3.25a <- round(ma.three.mean.25a[length(ma.three.mean.25a)],digits=0)
ratio.25a <- gmean.25a/max.three.25a
LRP.med.3.25a <- round(0.3*gmean.25a,digits = 0)
LRP.med.4.25a <- round(0.4*gmean.25a,digits = 0)
LRP.max.2.25a <- round(0.2*max.three.25a,digits = 0)
USR.med.8.25a <- round(0.8*gmean.25a,digits = 0)
USR.max.4.25a <- round(0.4*max.three.25a,digits = 0)

# SFA 26A
surv.26a <- survey.obj$BBn$model.dat
surv.26a <- rbind(surv.26a,c(2020,rep(NA,ncol(surv.26a)-1)))
surv.26a <- surv.26a |> collapse::fsubset(year >=1994)
surv.26a <- surv.26a[order(surv.26a$year),] # get the years ordered correctly for the rolling mean
# q correct
surv.26a$I <- surv.26a$I/q.index
surv.26a$IR <- surv.26a$IR/q.index
gmean.26a <- exp(mean(log(surv.26a$I),na.rm=T))
max.26a <- max(surv.26a$I,na.rm=T)
# Geometric rolling mean
ma.three.mean.26a <- exp(c(na.omit(rollmean(log(na.omit(surv.26a$I)),3,'center'))))
max.three.26a <- max(ma.three.mean.26a,na.rm=T)
# Current 3 year geometric mean biomass
bm.last.3.26a <- round(ma.three.mean.26a[length(ma.three.mean.26a)],digits=0)
ratio.26a <- gmean.26a/max.three.26a
LRP.med.3.26a <- round(0.3*gmean.26a,digits = 0)
LRP.med.4.26a <- round(0.4*gmean.26a,digits = 0)
LRP.max.2.26a <- round(0.2*max.three.26a,digits = 0)
USR.med.8.26a <- round(0.8*gmean.26a,digits = 0)
USR.max.4.26a <- round(0.4*max.three.26a,digits = 0)


# SFA 26C
surv.26c <- lined.survey.obj$model.dat # Has NA's for missing 2020 so good to use as is
surv.26c <- surv.26c |> collapse::fsubset(year >=1994)
# Q correct
surv.26c$I <- surv.26c$I/q.index
surv.26c$IR <- surv.26c$IR/q.index
gmean.26c <- exp(mean(log(surv.26c$I),na.rm=T))
max.26c <- max(surv.26c$I,na.rm=T)
# Geometric rolling mean
ma.three.mean.26c <- exp(na.omit(c(rollmean(log(na.omit(surv.26c$I)),3,'center'))))
max.three.26c <- max(ma.three.mean.26c,na.rm=T)
# Current 3 year geometric mean biomass
bm.last.3.26c <- round(ma.three.mean.26c[length(ma.three.mean.26c)],digits=0)
ratio.26c <- gmean.26c/max.three.26c
LRP.med.3.26c <- round(0.3*gmean.26c,digits = 0)
LRP.med.4.26c <- round(0.4*gmean.26c,digits = 0)
LRP.max.2.26c <- round(0.2*max.three.26c,digits = 0)
USR.med.8.26c <- round(0.8*gmean.26c,digits = 0)
USR.max.4.26c <- round(0.4*max.three.26c,digits = 0)

# SFA 27B
surv.27b <- survey.obj$GBb$model.dat # Need to add missing 2020 survey in here.
surv.27b <- rbind(surv.27b,c(2020,rep(NA,ncol(surv.27b)-1)))
surv.27b <- surv.27b |> collapse::fsubset(year >=1994)
surv.27b <- surv.27b[order(surv.27b$year),] # get the years ordered correctly for the rolling mean
# q corrected
surv.27b$I <- surv.27b$I/q.index
surv.27b$IR <- surv.27b$IR/q.index
gmean.27b <- exp(mean(log(surv.27b$I),na.rm=T))
max.27b <- max(surv.27b$I,na.rm=T)
ma.three.mean.27b <- exp(c(na.omit(rollmean(log(na.omit(surv.27b$I)),3,'center'))))
max.three.27b <- max(ma.three.mean.27b,na.rm=T)
# Current 3 year geometric mean biomass
bm.last.3.27b <- round(ma.three.mean.27b[length(ma.three.mean.27b)],digits=0)
ratio.27b <- gmean.27b/max.three.27b
LRP.med.3.27b <- round(0.3*gmean.27b,digits = 0)
LRP.med.4.27b <- round(0.4*gmean.27b,digits = 0)
LRP.max.2.27b <- round(0.2*max.three.27b,digits = 0)
USR.med.8.27b <- round(0.8*gmean.27b,digits = 0)
USR.max.4.27b <- round(0.4*max.three.27b,digits = 0)

# Old German data, curious what the median/max ratio was...
gmean.unlined.26c <- median(survey.obj$Ger$model.dat$I,na.rm=T)
max.unlined.26c <- max(survey.obj$Ger$model.dat$I,na.rm=T)
ma.three.mean.unlined.26c <- c(na.omit(rollmean(survey.obj$Ger$model.dat$I,3,'center')))
max.three.unlined.26c <- max(ma.three.mean.unlined.26c,na.rm=T)
ratio.unlined.26c <- gmean.unlined.26c/max.three.unlined.26c

# Next up getting the relative F's right

fish.dat <- fish.dat[!is.na(fish.dat$lon),]
fish.dat <- fish.dat[!is.na(fish.dat$lat),]
fish.dat <- fish.dat[!fish.dat$lon==0,]
fish.dat <- fish.dat[!fish.dat$lat==0,]
# bbn.fish_dk$month <- lubridate::month(bbn.fish_dk$date)
fish.dat$month <- lubridate::month(lubridate::ymd(fish.dat$date))
fish.dat$sfa[grep(x=fish.dat$sfa, "25")] <- 25
fish.dat$sfa[grep(x=fish.dat$sfa, "26")] <- 26
fish.dat$sfa[grep(x=fish.dat$sfa, "27")] <- 27
fish.dat$sfa[fish.dat$bank %in% c("Ban", "Sab","Mid")] <- 25
fish.dat$sfa[fish.dat$bank %in% c("BBn", "BBs", "Ger")] <- 26
fish.dat$sfa[fish.dat$bank %in% c("GBb")] <- 27

fish.dat$surv.year <- fish.dat$year 
fish.dat$surv.year[fish.dat$month %in% 1:5 & fish.dat$sfa %in% 25:26 ] <- fish.dat$year[fish.dat$month %in% 1:5 & fish.dat$sfa %in% 25:26]-1
fish.dat$surv.year[fish.dat$month %in% 1:8 & fish.dat$sfa %in% 27] <- fish.dat$year[fish.dat$month %in% 1:8 & fish.dat$sfa %in% 27]-1

strata <- github_spatial_import("survey_boundaries", "survey_boundaries.zip", quiet=T)
fish_sf2 <- st_as_sf(fish.dat, coords=c("lon", "lat"), remove=F, crs=4326) %>% st_transform(32619)
fish_sf2 <- st_intersection(fish_sf2, st_transform(strata, 32619))
fish.dat2 <- fish.dat #safekeeping
fish.dat <- fish_sf2
#st_geometry(fish.dat) <- NULL

by.sy <- fish.dat %>% data.frame() %>%  dplyr::group_by(bank, surv.year)%>%   dplyr::summarize(sum = sum(pro.repwt/1000))

by.sy[by.sy$bank=="BBn" & by.sy$surv.year>1990,]

# fish.dat$surv.year[fish.dat$month %in% 6:12 & fish.dat$sfa %in% 25:26 ] <- fish.dat$year[fish.dat$month %in% 6:12 & fish.dat$sfa %in% 25:26]+1
# fish.dat$surv.year[fish.dat$month %in% 9:12 & fish.dat$sfa %in% 27] <- fish.dat$year[fish.dat$month %in% 9:12 & fish.dat$sfa %in% 27]+1

#tail(fish.dat[, c("fished", "month", "year", "surv.year")], 50)
survey.yr <- fish.dat %>%
  dplyr::group_by(surv.year, bank, sfa) %>%
  dplyr::summarize(mt = sum(pro.repwt)/1000) %>%
  dplyr::mutate(year=surv.year)

fishing.yr <- fish.dat %>%
  dplyr::group_by(year, bank, sfa) %>%
  dplyr::summarize(mt = sum(pro.repwt)/1000) 
  

banks <- c("Sab", "BBn", "Ger", "GBb")
relative.F <- NULL
for(b in banks) {
  # if(b=="Sab/Mid"){
  #   sab <- cbind(survey.obj[["Sab"]]$model.dat[, c("year", "I")], bank="Sab")
  #   mid <- cbind(survey.obj[["Mid"]]$model.dat[, c("year", "I")], bank="Mid")
  #   sabmid <- full_join(sab, mid) %>%
  #     group_by(year) %>%
  #     summarize(I=sum(I, na.rm=T)) #/0.35) # survey catchability (between 0.2 and 0.5), using this would mean "q-corrected", don't do this
  #   fishing <- survey.yr %>%
  #     filter(bank %in% c("Sab", "Mid")) %>%
  #     group_by(year) %>%
  #     summarize(mt=sum(mt)) %>%
  #     mutate(bank="Sab/Mid")
  #   compare <- full_join(sabmid, fishing[,c("year", "bank", "mt")])
  # }

  #if(!b=="Sab/Mid"){
    if(b=="Ger") compare <- full_join(merged.survey.obj[, c("year", "I")], survey.yr[survey.yr$bank==b,c("year", "bank", "mt")])
    if(!b=="Ger") compare <- full_join(survey.obj[[b]]$model.dat[, c("year", "I")], survey.yr[survey.yr$bank==b &!is.na(survey.yr$bank),c("year", "bank", "mt")])
 # }
  compare$relative.F <- compare$mt / (compare$I /q.index) # survey catchability
  relative.F <- rbind(relative.F, compare)
}
relFyrs <- expand.grid(year=min(relative.F$year, na.rm=T):max(relative.F$year, na.rm=T), bank=banks)
relative.F <- left_join(relFyrs, relative.F)
#relative.F <- relative.F[!is.na(relative.F$mt),]
#relative.F[relative.F$relative.F==Inf & !is.na(relative.F$relative.F),]$relative.F <- NA
relative.F$sfa[relative.F$bank %in% c("BBn", "BBs", "Ger", "BBn/BBs")] <- as.numeric(26)
relative.F$sfa[relative.F$bank %in% c("Ban", "Ban/Sab/Mid", "Sab/Mid", "Sab", "Mid")] <- as.numeric(25)
relative.F$sfa[relative.F$bank %in% c("GBb")] <- as.numeric(27)
relative.F$subarea[relative.F$bank=="Sab"] <- "25A-Sab"
relative.F$subarea[relative.F$bank=="BBn"] <- "26A"
relative.F$subarea[relative.F$bank=="Ger"] <- "26C"
relative.F$subarea[relative.F$bank=="GBb"] <- "27B"

# now limit it to be 2024 onwards
relative.F <- relative.F |> collapse::fsubset(year >= 1994)

# Sable is missing 2022 for some reason, so adding by hand...
relative.F$relative.F[relative.F$year == 2022 & relative.F$bank == "Sab"] <- 0 # There was no fishing in 2022
relative.F$mt[relative.F$year == 2022 & relative.F$bank == "Sab"] <- 0 # There was no fishing in 2022
# not clear why this dropped, but it's in the object so adding in..
relative.F$I[relative.F$year == 2022 & relative.F$bank == "Sab"] <- survey.obj$Sab$model.dat$I[survey.obj$Sab$model.dat$year == 2022]/q.index # q correct

# now I want to compare F to change in biomass...
rf.25a <- relative.F |> collapse::fsubset(bank == "Sab")
rf.26a <- relative.F |> collapse::fsubset(bank == "BBn")
rf.26c <- relative.F |> collapse::fsubset(bank == "Ger")
rf.27b <- relative.F |> collapse::fsubset(bank == "GBb")
# This is lined up so that the change in size from 1994-1995 is called 1994, which lines up with fishing being survey year where June 1994 - May 1995 
# is called 1994.
rf.25a$DB <- c(rf.25a$I[2:nrow(rf.25a)]-rf.25a$I[1:(nrow(rf.25a)-1)],NA)
rf.26a$DB <- c(rf.26a$I[2:nrow(rf.26a)]-rf.26a$I[1:(nrow(rf.26a)-1)],NA)
rf.26c$DB <- c(rf.26c$I[2:nrow(rf.26c)]-rf.26c$I[1:(nrow(rf.26c)-1)],NA)
rf.27b$DB <- c(rf.27b$I[2:nrow(rf.27b)]-rf.27b$I[1:(nrow(rf.27b)-1)],NA)
# Now percent change
rf.25a$prop.DB <- 100*rf.25a$DB/rf.25a$I
rf.26a$prop.DB <- 100*rf.26a$DB/rf.26a$I
rf.26c$prop.DB <- 100*rf.26c$DB/rf.26c$I
rf.27b$prop.DB <- 100*rf.27b$DB/rf.27b$I

# In 26a we can get a relative removal reference point from the GEM method, just need to make the linear model and extract the x-intercept from it.
rr.new.dat <- data.frame(relative.F = seq(0,1,by=0.001))
rr.rf.26a.mod <- lm(prop.DB~relative.F,data=rf.26a)
rr.new.dat$prop.DB <- predict(rr.rf.26a.mod,newdata = rr.new.dat)
closest <- which(abs(rr.new.dat$prop.DB) == min(abs(rr.new.dat$prop.DB)))[1]
rr.rf.26a <- round(rr.new.dat$relative.F[closest],digits=2)

# Here we do the new idea of looking for a period of low variability in the time series and seeing what the relative F was during that time
# Consider that a measure of the 'target' RR. So we need a rolling variance which can deal with NAs!

# Use a 5 year moving average.
ny.ma <- 5
bank.var <- NULL
for(b in banks)
  {
  tmp.dat <- relative.F[relative.F$bank == b,]
  if(b == "Ger") tmp.dat <- tmp.dat[tmp.dat$year >= 2008,]
  tmp.yrs <- min(tmp.dat$year):(max(tmp.dat$year)-ny.ma+1)
  tmp.var <- data.frame(bank = rep(b,length(tmp.yrs)),sd = rep(NA,length(tmp.yrs)),yr.start = rep(NA,length(tmp.yrs)),yr.end = rep(NA,length(tmp.yrs)))
  # Fill in NA's with average of previous and following year, they all have an NA so really don't need the if...
  if(any(is.na(tmp.dat)))
  {
    nas <- which(is.na(tmp.dat$I))
    # Works as long as we don't miss two years in a row (i.e., early German.) or the final year is an NA
    for(i in 1:length(nas)) tmp.dat$I[nas[i]] <- mean(c(tmp.dat$I[nas[i]-1],tmp.dat$I[nas[i]+1]))
  } # end if(any(is.na(tmp.dat)))
  c <- 0
  for(y in tmp.yrs)
  {
    c = c+1
    tmp.var$sd[c] <-   sd(tmp.dat$I[tmp.dat$year %in% y:(y+4)],na.rm=T)
    tmp.var$yr.start[c] <- y
    tmp.var$yr.end [c] <- y+ny.ma-1
  } # end for(y in tmp.yrs)
  min.var <- which(tmp.var$sd == min(tmp.var$sd))
  bank.var[[b]] <- tmp.var[min.var,]
}

low.var <- do.call("rbind",bank.var)

# now we can get the mean for each bank, first for 25A....
low.25a.yrs <- low.var$yr.start[low.var$bank == "Sab"]:low.var$yr.end[low.var$bank == "Sab"]
rf.25a.low.var <- rf.25a[rf.25a$year %in% low.25a.yrs,]
target.rr.25a.index <- signif(median(rf.25a.low.var$relative.F,na.rm=T),digits=2)
#26A
low.26a.yrs <- low.var$yr.start[low.var$bank == "BBn"]:low.var$yr.end[low.var$bank == "BBn"]
rf.26a.low.var <- rf.26a[rf.26a$year %in% low.26a.yrs,]
target.rr.26a.index <- signif(median(rf.26a.low.var$relative.F,na.rm=T),digits=2)
# 26C
low.26c.yrs <- low.var$yr.start[low.var$bank == "Ger"]:low.var$yr.end[low.var$bank == "Ger"]
rf.26c.low.var <- rf.26c[rf.26c$year %in% low.26c.yrs,]
target.rr.26c.index <- signif(median(rf.26c.low.var$relative.F,na.rm=T),digits=2)
# 27B
low.27b.yrs <- low.var$yr.start[low.var$bank == "GBb"]:low.var$yr.end[low.var$bank == "GBb"]
rf.27b.low.var <- rf.27b[rf.27b$year %in% low.27b.yrs,]
target.rr.27b.index <- signif(median(rf.27b.low.var$relative.F,na.rm=T),digits=2)



```

```{r indices-figures,include=F,warning=F}

# The simple reference point figures
plt.dat.25a <- data.frame(year =2020:2022,cur.bm = bm.last.3.25a,
                          lrp.2 = LRP.max.2.25a,lrp.3 = LRP.med.3.25a,lrp.4 = LRP.med.4.25a,
                          usr.4 = USR.max.4.25a,usr.8 = USR.med.8.25a)
                          
plt.25a.bmi.ts <- ggplot(surv.25a) + geom_line(aes(x=year,y=I)) + 
                              geom_line(data= plt.dat.25a,aes(x=year,y=cur.bm),color=u.colors[1],size=1.5) +
                              geom_hline(yintercept = plt.dat.25a$lrp.2[1],color='firebrick2',linetype='solid') +
                              geom_hline(yintercept = plt.dat.25a$lrp.3[1],color='firebrick2',linetype = 'dotted') +
                              geom_hline(yintercept = plt.dat.25a$lrp.4[1],color='firebrick2',linetype='dashed') +
                              geom_hline(yintercept = plt.dat.25a$usr.4[1],color=u.colors[2],linetype = 'solid') +
                              geom_hline(yintercept = plt.dat.25a$usr.8[1],color=u.colors[2],linetype='dashed') +
                              scale_x_continuous(name = '',breaks = seq(1995,2025,by=5),limits = c(1994,2022),labels = NULL) +
                              scale_y_continuous(name = "",limits=c(0,7500)) #+
                              #theme(axis.title.y = element_text(hjust = 4))


# Now BBn
plt.dat.26a <- data.frame(year =2020:2022,cur.bm = bm.last.3.26a,
                          lrp.2 = LRP.max.2.26a,lrp.3 = LRP.med.3.26a,lrp.4 = LRP.med.4.26a,
                          usr.4 = USR.max.4.26a,usr.8 = USR.med.8.26a)
                          
plt.26a.bmi.ts <- ggplot(surv.26a) + geom_line(aes(x=year,y=I)) + 
                              geom_line(data= plt.dat.26a,aes(x=year,y=cur.bm),color=u.colors[1],size=1.5) +
                              geom_hline(yintercept = plt.dat.26a$lrp.2[1],color='firebrick2',linetype='solid') +
                              geom_hline(yintercept = plt.dat.26a$lrp.3[1],color='firebrick2',linetype = 'dotted') +
                              geom_hline(yintercept = plt.dat.26a$lrp.4[1],color='firebrick2',linetype='dashed') +
                              geom_hline(yintercept = plt.dat.26a$usr.4[1],color=u.colors[2],linetype = 'solid') +
                              geom_hline(yintercept = plt.dat.26a$usr.8[1],color=u.colors[2],linetype='dashed') +
                              scale_x_continuous(name = '',breaks = seq(1995,2025,by=5),limits = c(1994,2022),labels = NULL) +
                              scale_y_continuous(name = "",limits=c(0,19500))
# Now german
plt.dat.26c <- data.frame(year =2020:2022,cur.bm = bm.last.3.26c,
                          lrp.2 = LRP.max.2.26c,lrp.3 = LRP.med.3.26c,lrp.4 = LRP.med.4.26c,
                          usr.4 = USR.max.4.26c,usr.8 = USR.med.8.26c)
                          
plt.26c.bmi.ts <- ggplot(surv.26c) + geom_line(aes(x=year,y=I)) + 
                              geom_line(data= plt.dat.26c,aes(x=year,y=cur.bm),color=u.colors[1],size=1.5) +
                              geom_hline(yintercept = plt.dat.26c$lrp.2[1],color='firebrick2',linetype='solid') +
                              geom_hline(yintercept = plt.dat.26c$lrp.3[1],color='firebrick2',linetype = 'dotted') +
                              geom_hline(yintercept = plt.dat.26c$lrp.4[1],color='firebrick2',linetype='dashed') +
                              geom_hline(yintercept = plt.dat.26c$usr.4[1],color=u.colors[2],linetype = 'solid') +
                              geom_hline(yintercept = plt.dat.26c$usr.8[1],color=u.colors[2],linetype='dashed') +
                              scale_x_continuous(name = '',breaks = seq(1995,2025,by=5),limits = c(1994,2022)) +
                              scale_y_continuous(name = "",limits=c(0,6000))

# Now GGb
plt.dat.27b <- data.frame(year =2020:2022,cur.bm = bm.last.3.27b,
                          lrp.2 = LRP.max.2.27b,lrp.3 = LRP.med.3.27b,lrp.4 = LRP.med.4.27b,
                          usr.4 = USR.max.4.27b,usr.8 = USR.med.8.27b)
                          
plt.27b.bmi.ts <- ggplot(surv.27b) + geom_line(aes(x=year,y=I)) + #geom_point(aes(x=year,y=I),size=3) +
                              geom_line(data= plt.dat.27b,aes(x=year,y=cur.bm),color=u.colors[1],size=1.5) +
                              geom_hline(yintercept = plt.dat.27b$lrp.2[1],color='firebrick2',linetype='solid') +
                              geom_hline(yintercept = plt.dat.27b$lrp.3[1],color='firebrick2',linetype = 'dotted') +
                              geom_hline(yintercept = plt.dat.27b$lrp.4[1],color='firebrick2',linetype='dashed') +
                              geom_hline(yintercept = plt.dat.27b$usr.4[1],color=u.colors[2],linetype = 'solid') +
                              geom_hline(yintercept = plt.dat.27b$usr.8[1],color=u.colors[2],linetype='dashed') +
                              scale_x_continuous(name = '',breaks = seq(1995,2025,by=5),limits = c(1994,2022)) +
                              scale_y_continuous(name = "",limits=c(0,6000))

# We can make these a nice 4 by 4 plot...
plt.bmi.ts <- plot_grid(plt.25a.bmi.ts,plt.26a.bmi.ts,plt.26c.bmi.ts,plt.27b.bmi.ts,ncol=2,labels = c("SFA 25A","SFA 26A","SFA 26C","SFA 27B"),label_size=14,label_y=0.95,label_x=0.15) + theme(plot.margin = margin(0, 0, -275, 0))

plt.bmi.ts <- add_sub(plt.bmi.ts, "Survey Biomass Index (tonnes)",angle=90,y=2.25,x=0.01,size=18)
plt.bmi.ts <- ggdraw(plt.bmi.ts)
save_plot(plt.bmi.ts,file =paste0(plot.index.loc,"RPs_BM_Indices.png"),base_height = 8,base_width = 11)



# We can also make those KOBE plots for the areas using the relative indices, which aren't really showing anything
plt.25a.kobe.indx <-  ggplot(rf.25a,aes(y=relative.F,x=I)) +  geom_text(aes(label=substr(year,3,4))) + 
                                                              geom_path() + 
                                                              scale_y_continuous(name="",limits = c(0,NA)) +
                                                              scale_x_continuous(name="",limits = c(0,NA)) 

plt.26a.kobe.indx <-  ggplot(rf.26a,aes(y=relative.F,x=I)) +  geom_text(aes(label=substr(year,3,4))) + 
                                                              geom_path() + 
                                                              scale_y_continuous(name="",limits = c(0,NA)) +
                                                              scale_x_continuous(name="",limits = c(0,NA)) 

plt.26c.kobe.indx <-  ggplot(rf.26c,aes(y=relative.F,x=I)) +  geom_text(aes(label=substr(year,3,4))) + 
                                                              geom_path() + 
                                                              scale_y_continuous(name="",limits = c(0,NA)) +
                                                              scale_x_continuous(name="",limits = c(0,NA)) 

plt.27b.kobe.indx <-  ggplot(rf.27b,aes(y=relative.F,x=I)) +  geom_text(aes(label=substr(year,3,4))) + 
                                                              geom_path() + 
                                                              scale_y_continuous(name="",limits = c(0,NA)) +
                                                              scale_x_continuous(name="",limits = c(0,NA)) 


plt.bmi.kobe <- plot_grid(plt.25a.kobe.indx,plt.26a.kobe.indx,plt.26c.kobe.indx,plt.27b.kobe.indx,ncol=2,labels = c("SFA 25A","SFA 26A","SFA 26C","SFA 27B"),label_size=14,label_y=0.95,label_x=0.15) + theme(plot.margin = margin(0, 0, -200, 0))

plt.bmi.kobe <- add_sub(plt.bmi.kobe, "Survey Biomass Index (tonnes)",angle=0,y=1.25,x=0.55,size=18)
plt.bmi.kobe <- add_sub(plt.bmi.kobe, "Relative exploitation rate",angle=90,y=2.5,x=0.01,size=18)

#plt.bmi.ts <- ggdraw(plt.bmi.ts)
save_plot(plt.bmi.kobe,file =paste0(plot.index.loc,"Kobe_BM_Indices.png"),base_height = 8,base_width = 11)




# The Biomass change vs relative F figures (GEM plots)

# So there is no evidence of anything for these areas other than BBn so there's really no information about removal reference points
# that Science can provide using this method.
plt.25a.gem.indx <- ggplot(rf.25a,aes(x=relative.F,y=prop.DB)) +  geom_text(aes(label=substr(year,3,4))) + 
                                                                  geom_smooth(method='lm') + 
                                                                  geom_hline(yintercept = 0,linetype='dashed',size=1.25)+
                                                                  scale_x_continuous(name="",limits=c(0,NA)) +
                                                                  scale_y_continuous(name="") 

plt.26a.gem.indx <- ggplot(rf.26a,aes(x=relative.F,y=prop.DB)) +  geom_text(aes(label=substr(year,3,4))) + 
                                                                  geom_smooth(method='lm') + 
                                                                  geom_hline(yintercept = 0,linetype='dashed',size=1.25)+
                                                                  scale_x_continuous(name="",limits=c(0,NA)) +
                                                                  scale_y_continuous(name="") 

plt.26c.gem.indx <- ggplot(rf.26c,aes(x=relative.F,y=prop.DB)) +  geom_text(aes(label=substr(year,3,4))) + 
                                                                  geom_smooth(method='lm') + 
                                                                  geom_hline(yintercept = 0,linetype='dashed',size=1.25)+
                                                                  scale_x_continuous(name="",limits=c(0,NA)) +
                                                                  scale_y_continuous(name="") 

plt.27b.gem.indx <- ggplot(rf.27b,aes(x=relative.F,y=prop.DB)) +  geom_text(aes(label=substr(year,3,4))) + 
                                                                  geom_smooth(method='lm') + 
                                                                  geom_hline(yintercept = 0,linetype='dashed',size=1.25)+
                                                                  scale_x_continuous(name="",limits=c(0,NA)) +
                                                                  scale_y_continuous(name="") 


plt.bmi.gem <- plot_grid(plt.25a.gem.indx,plt.26a.gem.indx,plt.26c.gem.indx,plt.27b.gem.indx,ncol=2,labels = c("SFA 25A","SFA 26A","SFA 26C","SFA 27B"),label_size=14,label_y=0.93,label_x=0.12) + theme(plot.margin = margin(0, 0, -270, 0))

plt.bmi.gem <- add_sub(plt.bmi.gem, "Relative exploitation rate",angle=0,y=1.25,x=0.55,size=18)
plt.bmi.gem <- add_sub(plt.bmi.gem, "Change in survey biomass Index (%)",angle=90,y=2,x=0.01,size=18)

#plt.bmi.ts <- ggdraw(plt.bmi.ts)
save_plot(plt.bmi.gem,file =paste0(plot.index.loc,"GEM_BM_Indices.png"),base_height = 8,base_width = 11)




```





