

```{r sab-productivity-analysis,include=F}

# BSSM productivity import
#years <- 1994:2022 # Make sure we are using the right years!!
sab.prod.dat <- data.frame(Year = years,
                           B = DD.out$median$B,
                           R = DD.out$median$R,
                           SSB = DD.out$median$B + DD.out$median$R,
                           m = DD.out$median$m,
                           mr = DD.out$median$mR,
                           g = DD.out$data$g,
                           gR = DD.out$data$gR)

#sab.prod.dat[sab.prod.dat$Year %in% c(2015,2020),-1] <- NA


# Recruits on sable average about 4 years old (75 = 3.5 and 90 = 4.5), so we'll roll with RPS4 for the recruits.
sab.rec.age <- 4
sab.prod.dat$R4 <- c(sab.prod.dat$R[(sab.rec.age+1):nrow(sab.prod.dat)],rep(NA,sab.rec.age))
sab.prod.dat$RPS4 <- sab.prod.dat$R4/sab.prod.dat$SSB 

# Now we can make some figures...
p.rps.ts <- ggplot(sab.prod.dat, aes(x=Year,y=RPS4))  + geom_point() + 
                                                    xlab("'Birth' year") + ylab("Recruits per Spawner (kg\u00B9\u22C5kg\u207B\u00B9)") +
                                                    geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 7))+
                                                    scale_y_log10() +  
                                                    scale_x_continuous(breaks = c(seq(1980,2080,by=5)))# Definitely a signal here
save_plot(paste0(sab.plot.loc,"RPS_ts.png"),p.rps.ts,base_height =6,base_width = 10)                                               
                       
# Density dependence, clear trend with increasing RPS as SSB declines.
# Breakpoints are
sab.rps.bp1 <- 4300
sab.rps.bp2 <- 7000
p.rps.ssb <- ggplot(sab.prod.dat,aes(y=RPS4,x=SSB)) + geom_text(aes(label = substr(Year,3,4)),size=3) + 
                                                  xlab("Adult Biomass (tonnes)") + ylab("Recruits per Spawner (kg\u00B9\u22C5kg\u207B\u00B9)") +
                                                  geom_smooth(method = 'lm') +
                                                  scale_y_log10() + 
                                                  geom_vline(xintercept = c(sab.rps.bp2),size=0.5,color='firebrick2',linetype='dashed')  + 
                                                  scale_x_continuous(breaks = c(seq(1000,20000,by=1000)))# Definitely a signal here
save_plot(paste0(sab.plot.loc,"RPS_vs_SSB.png"),p.rps.ssb,base_height =6,base_width = 10)        

# Recruits vs SSB
p.rec.ssb <- ggplot(sab.prod.dat,aes(y=R4,x=SSB)) + geom_text(aes(label = substr(Year,3,4)),size=3)  +
                                                xlab("Spawning Stock Biomass (tonnes)") + ylab("Recruits (tonnes)") +
                                                geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +scale_y_log10() +
                                                geom_vline(xintercept = c(sab.rps.bp2),size=0.5,color='firebrick2',linetype='dashed')  + 
                                                scale_x_continuous(breaks = c(seq(1000,20000,by=1000)))
save_plot(paste0(sab.plot.loc,"Rec_vs_SSB.png"),p.rec.ssb,base_height =6,base_width = 10)    

# What does a robust regression glook like...
# tst <- lmrob(log(RPS4) ~ SSB,data=sab.prod.dat)
# tst2 <- lm(log(RPS4) ~ SSB,data=sab.prod.dat)
# summary(tst)
# summary(tst2)
# 
# new.dat <- data.frame(SSB = seq(2000,10000,by=100))
# 
# pred.rob <- predict(tst,newdata = new.dat,se=T)
# pred.lm <- predict(tst2,newdata = new.dat,se=T)
# 
# new.dat$RPS.rob <- pred.rob$fit
# new.dat$RPS.lm <- pred.lm$fit
# new.dat$UCI.rob <- new.dat$RPS.rob + 2*pred.rob$se.fit
# new.dat$LCI.rob <- new.dat$RPS.rob - 2*pred.rob$se.fit
# new.dat$UCI.lm <- new.dat$RPS.lm + 2*pred.lm$se.fit
# new.dat$LCI.lm <- new.dat$RPS.lm - 2*pred.lm$se.fit
# 
# # The robust models actually have narrower CIs!!
# ggplot(new.dat) + geom_line(aes(x=SSB,y=RPS.rob)) + geom_line(aes(x=SSB,y=RPS.lm),color='blue') +
#                   geom_ribbon(aes(x=SSB,ymax=UCI.rob,ymin=LCI.rob),alpha=0.2) +
#                   geom_ribbon(aes(x=SSB,ymax=UCI.lm,ymin=LCI.lm),alpha=0.2,color='blue')

# Next is there any evidence of Density dependence with growth?
# Absolutely no evidence of DD!



# No relationship between g and SSB.
p.g.ssb <- ggplot(sab.prod.dat,aes(y=g,x=SSB)) + geom_text(aes(label = substr(Year,3,4))) +
                                             xlab("") + ylab("Growth (Fully Recruited)") +
                                             geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +
                                             #geom_vline(xintercept = 9000,size=0.5,color='firebrick2',linetype='dashed')  + 
                                             scale_x_continuous(breaks = c(seq(1000,20000,by=1000),labels = NA))

p.gR.ssb <- ggplot(sab.prod.dat,aes(y=gR,x=SSB)) + geom_text(aes(label = substr(Year,3,4))) +
                                             xlab("Adult Biomass (tonnes)") + ylab("Growth (Recruits)") +
                                             geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +
                                             #geom_vline(xintercept = 9000,size=0.5,color='firebrick2',linetype='dashed')  + 
                                             scale_x_continuous(breaks = c(seq(1000,20000,by=1000)))

p.gs.ssb <-  cowplot::plot_grid(p.g.ssb,p.gR.ssb,nrow=2)

save_plot(paste0(sab.plot.loc,"Growth_vs_SSB.png"),p.gs.ssb,base_height =12,base_width = 10)  

# Naturnal mortality and SSB, not really anything IMHO.
sab.m.bp <- 0
p.m.ssb <- ggplot(sab.prod.dat,aes(y=m,x=SSB)) + geom_text(aes(label = substr(Year,3,4)))+ 
                                             xlab("") + ylab("FR Natural Mortality (instantaneous)") +
                                             geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +
                                             #geom_vline(xintercept = 10000,size=0.5,color='firebrick2',linetype='dashed')  + 
                                             scale_x_continuous(breaks = c(seq(1000,20000,by=1000)),labels=NULL)

p.mr.ssb <- ggplot(sab.prod.dat,aes(y=mr,x=SSB)) + geom_text(aes(label = substr(Year,3,4)))+ 
                                             xlab("Adult Biomass (tonnes)") + ylab("Recruit Natural Mortality (instantaneous)") +
                                             geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +
                                             #geom_vline(xintercept = 10000,size=0.5,color='firebrick2',linetype='dashed')  + 
                                             scale_x_continuous(breaks = c(seq(1000,20000,by=1000)))

p.mort.ssb <-  cowplot::plot_grid(p.m.ssb,p.mr.ssb,nrow=2)

save_plot(paste0(sab.plot.loc,"M_vs_SSB.png"),p.mort.ssb,base_height =11,base_width = 8)                


# Step 2.... Correlation
# Next thing you should consider is whether there are correlations in your productivity parameters, first look to autocorrelated time series
# Then you want to look for cross-correlations between mortality and recruitment
# First let's look for acf in our time series...
# Starting with recruitment we see there is a strong autocorrlation in the total number of recruits
p.rec.acf <- ggAcf(na.omit(sab.prod.dat$R),lag.max = 10) + ggtitle("")+ ylab("ACF Recruits")
save_plot(paste0(sab.plot.loc,"ACF_Rec.png"),p.rec.acf,base_height =6,base_width = 10)                
# But is this simply due to the underlying trend in R over time... possible, but really what is there is a very strong long cycle rather than a linear trend so ignoring this...
rec.mod <- lm(R ~ I(Year-1994),data=sab.prod.dat)
summary(rec.mod)
# So probably better to look at per capita recruitment and see if that is a better acf'er...
# And here we do see the correlation remains.
p.rps.acf <- ggAcf(na.omit(log(sab.prod.dat$RPS4)),lag.max = 10) + ggtitle("") + ylab("ACF log(RPS)")
save_plot(paste0(sab.plot.loc,"ACF_RPS.png"),p.rps.acf,base_height =6,base_width = 10)                


# pacf shows us that we could approximate the RPS time series as an AR1, though there is a teaser of the 2 year negative correlation similar to what we found on BBn.
# could easily enough model as an AR2 and use that. Also a 5 year correlation there, which I think is that longer term cycle.  But ignoring that...
p.rps.pacf <- ggPacf(na.omit(log(sab.prod.dat$RPS4)),lag.max = 10) + ggtitle("") + ylab("PACF log(RPS)")
# The RPS value for the text and for the sims later
sab.rps.lag <- 1
sab.rps.cor.1 <- round(p.rps.pacf$data$Freq[sab.rps.lag],digits=2)
sab.rps.cor.2 <- 0.01 # Make it a very small number if it is 0.
save_plot(paste0(sab.plot.loc,"PACF_RPS.png"),p.rps.pacf,base_height =6,base_width = 10)   

# On the log scale we see there is no trend in the data
rps.mod <- lm(log(RPS4) ~ I(Year-1994),data=sab.prod.dat)
summary(rps.mod) # Indeed there is...


# How about growth, nope nothing.
p.g.pacf <- ggPacf(sab.prod.dat$g,lag.max = 10) + ggtitle("") + ylab("ACF Growth (FR)")# No autocorrelation in Condition
p.gR.pacf <- ggPacf(sab.prod.dat$gR,lag.max = 10) + ggtitle("") + ylab("ACF Growth (Recruits)")# No autocorrelation in Condition
p.gs.pacf <-  cowplot::plot_grid(p.g.pacf,p.gR.pacf,nrow=2)

save_plot(paste0(sab.plot.loc,"PACF_growths.png"),p.gs.pacf,base_height =12,base_width = 10)                

# Natural morality correlation? Curious, no correlation at 1 lag, but a negative correlation at lag 2, suggesting the m is flipping every couple years I think?
p.m.acf <- ggAcf(sab.prod.dat$m,lag.max = 10) + ggtitle("") + ylab("ACF FR Natural Mortality") + xlab("") + scale_x_continuous(breaks = 1:14,labels=NULL) # Not significant
p.m.pacf <- ggPacf(sab.prod.dat$m,lag.max = 10) + ggtitle("") + ylab("PACF FR Natural Mortality")# Just barely significant
sab.m.lag <- 2
sab.m.cor.2 <- round(p.m.pacf$data$Freq[sab.m.lag],digits=2)
sab.m.cor.1 <- 0.01 # Make it a very small number if it is 0.
# Recruit mortality, no autocorrelation.
p.mr.acf <- ggAcf(sab.prod.dat$mr,lag.max = 10) + ggtitle("") + ylab("ACF Recruit Natural Mortality") + xlab("") + scale_x_continuous(breaks = 1:14,labels=NULL) # No autocorrelation in 
p.mr.pacf <- ggPacf(sab.prod.dat$mr,lag.max = 10) + ggtitle("") + ylab("PACF Recuit Natural Mortality")# No autocorrelation in Condition


p.m.pacfs <-  cowplot::plot_grid(p.m.pacf,p.mr.pacf,nrow=2)
save_plot(paste0(sab.plot.loc,"PACF_m.png"),p.m.pacfs,base_height =12,base_width = 10)                

# So check if there is a linear trend, and there isn't
mod.m <- lm(m~I(Year-1993),data=sab.prod.dat)
summary(mod.m) # No trend


# So next up lets look for evidence of correlation between your productivity parameters, specifically RPS and m
# We offset the RPS for this to the year they show up in the time series
sab.prod.dat$RPS4_offset <- c(rep(NA,sab.rec.age),sab.prod.dat$RPS4[-((length(sab.prod.dat$RPS4)-(sab.rec.age-1)):length(sab.prod.dat$RPS4))])
ggplot(sab.prod.dat,aes(x=Year,y=RPS4)) + geom_point() + geom_line(size=2) + geom_point(aes(y = m)) + geom_line(aes(y = m),color='blue') 
ggplot(sab.prod.dat,aes(x=m,y=RPS4)) + geom_text(aes(label = substr(Year,3,4))) + geom_smooth(method = 'gam')
# If we offset the RPS to the year they are actually showing up, might be some weak correlation, but can't say it's anything more than noise, so we can ignore this I think.
p.rpsoff.m <- ggplot(sab.prod.dat,aes(x=Year,y=RPS4_offset)) + geom_text(aes(label = substr(Year-4,3,4)))  + 
                                                           xlab("") +
                                                           ylab("RPS (kg\u00B9\u22C5kg\u207B\u00B9) & Natural mortality (Inst)") +
                                                           geom_line(aes(y = m),color='firebrick2',size=1,linetype='dashed')
p.rps.m.ccf <- ggCcf(sab.prod.dat$RPS4_offset,sab.prod.dat$m,lag.max = 10) + ggtitle("")
# Peak cross correlation...
sab.m.rps.lag <- p.rps.m.ccf$data$lag[which(abs(p.rps.m.ccf$data$Freq) == abs(max(p.rps.m.ccf$data$Freq)))]
sab.m.rps.cor <- round(p.rps.m.ccf$data$Freq[p.rps.m.ccf$data$lag == sab.m.rps.lag],digits=2)

p.rps.m.ccf.combo <-  cowplot::plot_grid(p.rpsoff.m,p.rps.m.ccf,nrow=2)
save_plot(paste0(sab.plot.loc,"CCF_ts_RPS_offset_m.png"),p.rps.m.ccf.combo,base_height =12,base_width = 10)                
      
# The final plot I want to show here is the correlation between the model estimate and the survey index.
# These will be aligned so don't need to get too fancy
mod.index.bm <- data.frame(year = sab.prod.dat$Year,mod.bm = sab.prod.dat$B,index.bm = surv.25a$I/mod.out$BUGSoutput$median$q)
mod.index.bm 

p.sab.mod.ind.bm <-ggplot(mod.index.bm) + geom_text(aes(x=index.bm,y=mod.bm,label = substr(year,3,4))) +
                                          scale_x_continuous(name="Q-corrected Survey Biomass Index (tonnes)") +
                                          scale_y_continuous(name="Model Biomass (tonnes)") +
                                          geom_abline(slope=1,intercept=0)
save_plot(paste0(sab.plot.loc,"Model_vs_index_biomass.png"),p.sab.mod.ind.bm,base_height =6,base_width = 10)   




# PICK IT UP FROM HERE.






```

```{r sab-productivity-simulations,include=F}
# Set the seed so we can repeat these simulations!
set.seed(2)
g.strat <- list(type = "bp",strat = 'dist',bp=1e99,cen.tend = "mean",set.g=1)#,mn.mx = 1 sd.mx = 0.05)

r.strat <- list(type = "cor",strat = 'dist', bp = c(sab.rps.bp2), rec.age=sab.rec.age, cen.tend='mean',
                      ar1=sab.rps.cor.1,ar2=sab.rps.cor.2,rps.m.cor = sab.m.rps.cor,rps.m.lag = sab.m.rps.lag,
                      mn.at.max = min(sab.prod.dat$RPS4,na.rm=T),sd.at.max = 0.1) 
m.strat <- list(type = "cor",strat = 'dist', bp = 1e99, cen.tend = 'median',
                      ar1=sab.m.cor.1,ar2=sab.m.cor.2)#mn.at.max =  max(sab.prod.dat$m,na.rm=T),sd.at.max = 0.1) #
mod.4.sab = "BSSM"
sab.exp.scenario <- seq(0,0.1,0.005)
#sab.model.yrs <- years
sab.max.SSB <- floor(max(sab.prod.dat$SSB/100,na.rm=T)) * 100

# Run projection
if(run.sims == T)
{
# Run projection
sab.res <- proj.mod(mods = list(bssm.mod = sab.mod),n_sim=n_sims,n_y = n_y,model=mod.4.sab,model.yrs = sab.model.yrs,
                plot_url = plot.sab.rp.mod.loc, run = 'no_model_error', 
                res_url = res.sab.rp.mod.loc,save.results = T, 
                exp.scenario=sab.exp.scenario, 
                g.mod =   list(type = g.strat$type,bp.strategy = g.strat$strat,bp= g.strat$bp,set.g = g.strat$set.g,cen.tend = g.strat$cen.tend),
                               #mn.at.max = g.strat$mn.at.max,sd.at.max =g.strat$sd.at.max), 
                rec.mod = list(type = r.strat$type,bp.strategy = r.strat$strat,bp= r.strat$bp, 
                               rec.age = r.strat$rec.age,rps.m.cor = r.strat$rps.m.cor,rps.m.lag = r.strat$rps.m.lag,cen.tend = r.strat$cen.tend,
                               ar1=r.strat$ar1,ar2=r.strat$ar2,
                               mn.at.max = r.strat$mn.at.max,sd.at.max =r.strat$sd.at.max), 
                m.mod =   list(type = m.strat$type,bp.strategy = m.strat$strat,bp= m.strat$bp, cen.tend = m.strat$cen.tend,#mn.at.max = m.strat$mn.mx,sd.at.max = m.strat$sd.mx,
                                ar1=m.strat$ar1,ar2=m.strat$ar2))#,
                               #mn.at.max = m.strat$mn.at.max,sd.at.max =m.strat$sd.at.max))
saveRDS(sab.res,paste0(res.sab.rp.mod.loc,"full_bmsy_sims_",min(sab.model.yrs),"-",max(sab.model.yrs)))
} # end if run.sims == T
if(run.sims == F) sab.res <- readRDS(paste0(res.sab.rp.mod.loc,"full_bmsy_sims_",min(sab.model.yrs),"-",max(sab.model.yrs)))

#Exp.res <- readRDS("D:/Framework/SFA_25_26_2024/RefPts/Results/Sab/R_75_FR_90/SEAM_1994_2022_vary_m_m0_0.2_qR_0.33_10_knots_g_original/RPs/SEAM_g_sv_0_1_dist_1_0.05_r_bp_dist_4500__0.032_0.24_m_bp_dist_10000__0.34_0.1.Rds")

sab.Exp.res <- sab.res$Exp.res

sab.RPs <- sab.Exp.res %>% dplyr::filter(year >= n_y-25) %>% dplyr::group_by(F.scenario) %>% dplyr::summarise(med.B = median(B,na.rm=T),
                                                                                                       med.C = median(Catch,na.rm=T))  

sab.c.at.msy <- max(sab.RPs$med.C)
sab.rr <- sab.RPs$F.scenario[sab.RPs$med.C == sab.c.at.msy] # Nobody would argue with 9% either...
sab.bmsy <- round(sab.RPs$med.B[sab.RPs$med.C == sab.c.at.msy],digits=-2)
sab.b0 <- round(sab.RPs$med.B[sab.RPs$F.scenario==0],digits=-2)

sab.c.at.msy <- round(sab.c.at.msy,digits=0)

# So our LRP options
sab.lrp.b0 <- 0.2 * sab.b0
sab.lrp.3.bmsy <- 0.3 * sab.bmsy
sab.lrp.4.bmsy <- 0.4 * sab.bmsy
# USR and TRP 
sab.usr.b0 <- 0.4 * sab.b0
sab.usr.bmsy <- 0.8 * sab.bmsy
sab.trp.bmsy <- sab.bmsy
sab.trp.b0 <- 0.8 * sab.b0



sab.res.at.rr.last.yrs <- sab.Exp.res[sab.Exp.res$F.scenario==sab.rr & sab.Exp.res$year > (n_y-last.yrs),]
# We can estimate the proportion of the time the stocks are in the critical, cautious, and healthy zones in the last 25 years of the simulations
sab.prop.yrs.critical <- round(100*length(which(sab.res.at.rr.last.yrs$B < sab.lrp.b0))/n_sims/last.yrs,digits=1)
sab.prop.yrs.cautious <- round(100*length(which(sab.res.at.rr.last.yrs$B >= sab.lrp.b0 & sab.res.at.rr.last.yrs$B < sab.usr.b0))/n_sims/last.yrs,digits=1)
sab.prop.yrs.healthy <- round(100*length(which(sab.res.at.rr.last.yrs$B >= sab.usr.b0))/n_sims/last.yrs,digits=1)

# How long does it take to 'rebuild'

sim.years <- sort(unique(sab.Exp.res$year))
F.scenario <- sort(unique(sab.Exp.res$F.scenario))

time.grid <- expand.grid(scenario = F.scenario,years = sim.years)
time.to <- data.frame(time.grid,Biomass = NA, T.msy = F,T.usr = F, T.lrp=F,T.trp = F)
for(i in sim.years)
{
B.now <- sab.Exp.res %>% dplyr::filter(year %in% i) %>% dplyr::group_by(F.scenario) %>% dplyr::summarise(med.B = median(B,na.rm=T))
time.to$Biomass[time.to$years == i] <- B.now$med.B
# This feels way clunky...
if(any(B.now$med.B >= sab.bmsy)) 
{
  trues <- which(B.now$med.B >= sab.bmsy)
  tmp <- time.to$T.msy[time.to$years == i]
  tmp[trues] <- T
  time.to$T.msy[time.to$years == i] <- tmp
}
if(any(B.now$med.B >= sab.usr.b0))
{
   trues <- which(B.now$med.B >= sab.usr.b0)
  tmp <- time.to$T.usr[time.to$years == i]
  tmp[trues] <- T
  time.to$T.usr[time.to$years == i] <- tmp
}
if(any(B.now$med.B >= sab.lrp.b0))
{
  trues <- which(B.now$med.B >= sab.lrp.b0)
  tmp <- time.to$T.lrp[time.to$years == i]
  tmp[trues] <- T
  time.to$T.lrp[time.to$years == i] <- tmp
}
if(any(B.now$med.B >= sab.trp.b0))
{
  trues <- which(B.now$med.B >= sab.trp.b0)
  tmp <- time.to$T.trp[time.to$years == i]
  tmp[trues] <- T
  time.to$T.trp[time.to$years == i] <- tmp
}
}


# If the stock is currently above the reference point you want these to =F, if it's below the reference point you want these to = T
sab.res.T.msy <- time.to |> collapse::fsubset(T.msy == T) |> collapse::fgroup_by(scenario) |> collapse::fselect(scenario,years,Biomass,T.msy) 
sab.res.T.usr <- time.to |> collapse::fsubset(T.usr == F) |> collapse::fgroup_by(scenario) |> collapse::fselect(scenario,years,Biomass,T.usr) 
sab.res.T.lrp <- time.to |> collapse::fsubset(T.lrp == F) |> collapse::fgroup_by(scenario) |> collapse::fselect(scenario,years,Biomass,T.lrp) 
sab.res.T.trp <- time.to |> collapse::fsubset(T.trp == T) |> collapse::fgroup_by(scenario) |> collapse::fselect(scenario,years,Biomass,T.trp) 
# So now summarize these...

sab.T.msy <- sab.res.T.msy %>% collapse::fgroup_by(scenario) %>% collapse::fsummarize(T.msy = min(years))
sab.T.usr <- sab.res.T.usr %>% collapse::fgroup_by(scenario) %>% collapse::fsummarize(T.usr = min(years))
sab.T.lrp <- sab.res.T.lrp %>% collapse::fgroup_by(scenario) %>% collapse::fsummarize(T.lrp = min(years)) # Hmm...
sab.T.trp <- sab.res.T.trp %>% collapse::fgroup_by(scenario) %>% collapse::fsummarize(T.trp = min(years)) # This tells me that TRP is really unachievable

# Figures from this...

# Show that the time series we're provided have similar characteristics to the input time series.
# Given the crazy high volume of these, I show the results for the BMSY scenario.
sab.res.4.plts <- sab.Exp.res |> collapse::fsubset(F.scenario == sab.rr & Sim <= n_sims)

# Here are the growth time series.
sab.rp.sim.g.plt <- ggplot(sab.res.4.plts) + geom_line(aes(x=year,y=g,group=Sim),alpha=0.02)
sab.rp.sim.gR.plt <- ggplot(sab.res.4.plts) + geom_line(aes(x=year,y=gR,group=Sim),alpha=0.02)
sab.rp.sim.m.plt <- ggplot(sab.res.4.plts) + geom_line(aes(x=year,y=M,group=Sim),alpha=0.02) 
sab.rp.sim.mr.plt <- ggplot(sab.res.4.plts) + geom_line(aes(x=year,y=mr,group=Sim),alpha=0.02) 
sab.rp.sim.rps.plt <- ggplot(sab.res.4.plts) + geom_line(aes(x=year,y=rps,group=Sim),alpha=1) 

# Extract the lag 1 ACF for each of the productivity parameters... 
sab.cor.res <- data.frame(g.cor = NA, gr.cor=NA,mr.acf.ar1 = NA,mr.acf.ar2 = NA,m.acf.ar1 = NA,m.acf.ar2 = NA,rps.ar1 = NA,rps.ar2 = NA,rps.m.cor = NA)
g.acf.all <- gr.acf.all <- m.acf.all <- mr.acf.all <-rps.acf.all <- rps.m.ccf.all <- NULL

max.lag <- 10

for(i in 1:n_sims)
{
  rps.dat <- sab.res$rps[,i,which(F.scenario == sab.rr)] # This is using the MSY scenario
  dat <- sab.res.4.plts |> collapse::fsubset(Sim == i)
  g.acf.all[[i]] <- ggPacf(dat$g,lag.max = max.lag,plot=F)$acf
  m.acf.all[[i]] <- ggPacf(dat$M,lag.max = max.lag,plot=F)$acf
  mr.acf.all[[i]] <- ggPacf(dat$MR,lag.max = max.lag,plot=F)$acf
  gr.acf.all[[i]] <- ggPacf(dat$gR,lag.max = max.lag,plot=F)$acf
  rps.acf.all[[i]] <- ggPacf(rps.dat,lag.max = max.lag,plot=F)$acf
  rps.m.ccf.all[[i]] <- ggCcf(rps.dat,dat$M,lag.max = max.lag,plot=F)$acf
  g.acf <- g.acf.all[[i]][1]
  gr.acf <- gr.acf.all[[i]][1]
  m.acf.ar1 <- m.acf.all[[i]][1]
  m.acf.ar2 <- m.acf.all[[i]][2]
  rps.acf.ar1 <- rps.acf.all[[i]][1]
  rps.acf.ar2 <- rps.acf.all[[i]][2]
  mr.acf.ar1 <- mr.acf.all[[i]][1]
  mr.acf.ar2 <- mr.acf.all[[i]][2]
  rsp.m.ccf <-  rps.m.ccf.all[[i]][max.lag+sab.m.rps.lag+1] # This gets the right lag almost magically.

  
  tmp <- data.frame(g.cor = g.acf, gr.cor=gr.acf,m.acf.ar1=m.acf.ar1,
                    mr.acf.ar1 = mr.acf.ar1,mr.acf.ar2 = mr.acf.ar2,
                    m.acf.ar2 =m.acf.ar2,rps.ar1 = rps.acf.ar1,
                    rps.ar2 = rps.acf.ar2,rps.m.cor = rsp.m.ccf)
  sab.cor.res[i,] <- tmp
} # end for(i in 1:n_sims)


g.sim.pacf <- data.frame(dat = colMeans(do.call('rbind',g.acf.all)),lag=1:max.lag)
gr.sim.pacf <- data.frame(dat = colMeans(do.call('rbind',gr.acf.all)),lag=1:max.lag)
m.sim.pacf <- data.frame(dat = colMeans(do.call('rbind',m.acf.all)),lag=1:max.lag)
mr.sim.pacf <- data.frame(dat = colMeans(do.call('rbind',mr.acf.all)),lag=1:max.lag)
rps.sim.pacf <- data.frame(dat = colMeans(do.call('rbind',rps.acf.all)),lag=1:max.lag)
rps.m.sim.ccf <- data.frame(dat = colMeans(do.call('rbind',rps.m.ccf.all)),lag=-max.lag:max.lag)


# So we retained the correlation structure for the most part, though it was generally weaker than what we observed in the time series.
sab.cor.sim.summary <- data.frame(t(round(colMeans(as.matrix(sab.cor.res)),digits=2)))
```




```{r special-sab-prod-sims-figs,include =F}
# Now I can make the PACF plots for the productivity parameters
#ggplot(g.sim.pacf,mapping=aes(x=lag,y=dat)) + geom_segment(mapping=aes(xend=lag,yend=0)) + geom_hline(yintercept=0) + scale_y_continuous(name = "Mean Partial Auto-correlation",limits = c(-0.5,0.5))
# Maximum and minimum for the figure, keep it symmetric...
max.abs <- max(abs(sab.cor.sim.summary),na.rm=T)

sab.m.sim.cor.plt <- ggplot(m.sim.pacf,mapping=aes(x=lag,y=dat)) + geom_segment(mapping=aes(xend=lag,yend=0)) + geom_hline(yintercept=0) + 
                                              scale_y_continuous(name = "Mean PACF (Fully-recruited M)",limits = c(-max.abs,max.abs)) + 
                                              scale_x_continuous(name = "",breaks = 1:max.lag,labels=NULL)

sab.mr.sim.cor.plt <- ggplot(mr.sim.pacf,mapping=aes(x=lag,y=dat)) + geom_segment(mapping=aes(xend=lag,yend=0)) + geom_hline(yintercept=0) + 
                                              scale_y_continuous(name = "Mean PACF (Recruit M)",limits = c(-max.abs,max.abs))+ 
                                              scale_x_continuous(name = "",breaks = 1:max.lag,labels=NULL)

sab.gr.sim.cor.plt <- ggplot(gr.sim.pacf,mapping=aes(x=lag,y=dat)) + geom_segment(mapping=aes(xend=lag,yend=0)) + geom_hline(yintercept=0) + 
                                               scale_y_continuous(name = "Mean PACF (Recruit growth)",limits = c(-max.abs,max.abs))+ 
                                               scale_x_continuous(name = "Lag",breaks = 1:max.lag)


sab.rps.sim.cor.plt <- ggplot(rps.sim.pacf,mapping=aes(x=lag,y=dat)) + geom_segment(mapping=aes(xend=lag,yend=0)) + geom_hline(yintercept=0) + 
                                                scale_y_continuous(name = "Mean PACF (RPS)",limits = c(-max.abs,max.abs))+ 
                                                scale_x_continuous(name = "Lag",breaks = 1:max.lag)


sab.sim.cors.plt <- plot_grid(sab.m.sim.cor.plt,sab.mr.sim.cor.plt,sab.gr.sim.cor.plt,sab.rps.sim.cor.plt)

save_plot(sab.sim.cors.plt,file = paste0(plot.sab.rp.mod.loc,min(sab.model.yrs),"-",max(sab.model.yrs),"/PACF_sim_correlation.png"),base_height = 11,base_width=8.5)



sab.rps.m.sim.cor.plt <- ggplot(rps.m.sim.ccf,mapping=aes(x=lag,y=dat)) +  geom_segment(mapping=aes(xend=lag,yend=0)) + geom_hline(yintercept=0) + 
                                                scale_y_continuous(name = "Mean CCF (M vs. RPS)",limits = c(-max.abs,max.abs))+ 
                                                scale_x_continuous(name = "Lag",breaks = -max.lag:max.lag)

save_plot(sab.rps.m.sim.cor.plt,file = paste0(plot.sab.rp.mod.loc,min(sab.model.yrs),"-",max(sab.model.yrs),"/CCF_sim_correlation.png"),base_height = 8.5,base_width=8.5)

# The density dependence from the simulations...
sab.res.4.plts$SSB <- sab.res.4.plts$B + sab.res.4.plts$Rec
# To get the RPS offset right I need to loop-d-loo

for(i in 1:n_sims)
{
  tmp <- sab.res.4.plts[sab.res.4.plts$Sim == i,]
  tmp$rps.offset <- c(tmp$rps[(sab.rec.age+1):nrow(tmp)],rep(NA,sab.rec.age))
  sab.res.4.plts$rps.offset[sab.res.4.plts$Sim == i] <- tmp$rps.offset
}


# Set the alpha level for the lines on the figures showing the individual realizations.
if(n_sims <= 10) alphs <- 0.5
if(n_sims > 10) alphs <- 0.1
if(n_sims > 100) alphs <- 1/255 # This is the minimum you can Alpha

sab.prod.sum <- data.frame(mn.gR.obs = mean(sab.prod.dat$gR,na.rm=T),mn.gR.sim = mean(sab.res.4.plts$gR),
                           med.m.obs = median(sab.prod.dat$m,na.rm=T),med.m.sim = median(sab.res.4.plts$M),
                           mn.mR.obs = mean(sab.prod.dat$mr,na.rm=T),mn.mR.sim = mean(sab.res.4.plts$MR),
                           mn.rps.obs = mean(sab.prod.dat$RPS4,na.rm=T),mn.rps.sim = mean(sab.res.4.plts$rps))


sab.m.sim.comp.plt <- ggplot(sab.res.4.plts) + geom_point(aes(x=SSB/1000,y=M),alpha=alphs,shape=21,fill='black',stroke=NA) + 
                         geom_vline(xintercept = sab.max.SSB/1000,color='red',linetype='solid') +
                         geom_hline(yintercept = sab.prod.sum$med.m.obs,color='blue',linetype='dashed')+
                         geom_hline(yintercept = sab.prod.sum$med.m.sim,color='blue',linetype='solid')+
                         scale_x_continuous(name="",labels = NULL) +
                         scale_y_continuous(name=("Fully-recruited NM (instantaneous)"))

sab.mr.sim.comp.plt <- ggplot(sab.res.4.plts) + geom_point(aes(x=SSB/1000,y=MR),alpha=alphs,shape=21,fill='black',stroke=NA) +
                         geom_hline(yintercept = sab.prod.sum$mn.mR.obs,color='blue',linetype='dashed')+
                         geom_hline(yintercept = sab.prod.sum$mn.mR.sim,color='blue',linetype='solid')+
                         scale_x_continuous(name="",labels = NULL) +
                         scale_y_continuous(name=("Recruit NM (instantaneous)"))

sab.gr.sim.comp.plt <- ggplot(sab.res.4.plts) + geom_point(aes(x=SSB/1000,y=gR),alpha=alphs,shape=21,fill='black',stroke=NA)  +
                         geom_hline(yintercept = sab.prod.sum$mn.gR.obs,color='blue',linetype='dashed')+
                         geom_hline(yintercept = sab.prod.sum$mn.gR.sim,color='blue',linetype='solid')+
                         scale_x_continuous(name="") +
                         scale_y_continuous(name=("Recruit growth"))

# The really low RPS values are because of the correlation, they happen after most of the really large recruitment years, so are due to the large negative lag 2 rps, ha!
sab.rps.sim.comp.plt <- ggplot(sab.res.4.plts) + geom_point(aes(x=SSB/1000,y=rps.offset),alpha=alphs,shape=21,fill='black',stroke=NA) + 
                         geom_vline(xintercept = sab.rps.bp2/1000,color='red',linetype='solid') +
                         geom_hline(yintercept = sab.prod.sum$mn.rps.obs,color='blue',linetype='dashed')+
                         geom_hline(yintercept = sab.prod.sum$mn.rps.sim,color='blue',linetype='solid')+
                         scale_x_continuous(name="") +
                         scale_y_log10(name=("Recruits per Spawner (kg\u00B9\u22C5kg\u207B\u00B9)"))


sab.sim.comps.plt <- plot_grid(sab.m.sim.comp.plt,sab.mr.sim.comp.plt,sab.rps.sim.comp.plt,sab.gr.sim.comp.plt)
sab.sim.comps.plt2 <- add_sub(sab.sim.comps.plt, "Adult Biomass (tonnes x 1000)",angle=0,y=1.4,x=0.55,size=24)

save_plot(sab.sim.comps.plt2,file = paste0(plot.sab.rp.mod.loc,min(sab.model.yrs),"-",max(sab.model.yrs),"/Sim_paramter_DD.png"),base_height = 11,base_width=8.5)


sab.mod.rp.plt <- ggplot(sab.prod.dat) + geom_line(aes(x=Year,y=B/1000)) + 
                       geom_hline(yintercept = sab.lrp.b0/1000,color='firebrick2',linetype='solid') +
                       geom_hline(yintercept = sab.lrp.3.bmsy/1000,color='firebrick2',linetype = 'dotted') +
                       geom_hline(yintercept = sab.lrp.4.bmsy/1000,color='firebrick2',linetype='dashed') +
                       geom_hline(yintercept = sab.usr.b0/1000,color=u.colors[2],linetype = 'solid') +
                       geom_hline(yintercept = sab.usr.bmsy/1000,color=u.colors[2],linetype='dashed') +
                       geom_hline(yintercept = sab.bmsy/1000,color=u.colors[1],linetype='solid',size=1.5) +
                       scale_x_continuous('',breaks=seq(1990,2030,by=3)) +
                       scale_y_continuous('Fully-recruited Biomass (tonnes x 1000)') 

save_plot(sab.mod.rp.plt,file = paste0(plot.sab.rp.mod.loc,min(sab.model.yrs),"-",max(sab.model.yrs),"/Sim_RPs.png"),base_height = 8.5,base_width=8.5)


sab.mod.real.plt <- ggplot(sab.res.4.plts) + geom_line(aes(x=year,y=B/1000,group=Sim),alpha=alphs) + 
                       geom_hline(yintercept = sab.lrp.b0/1000,color='firebrick2',linetype='solid',size=1.5) +
                       #geom_hline(yintercept = sab.lrp.3.bmsy/1000,color='firebrick2',linetype = 'dotted') +
                       #geom_hline(yintercept = sab.lrp.4.bmsy/1000,color='firebrick2',linetype='dashed') +
                       geom_hline(yintercept = sab.usr.b0/1000,color=u.colors[2],linetype = 'solid',size=1.5) +
                       #geom_hline(yintercept = sab.usr.bmsy/1000,color=u.colors[2],linetype='dashed') +
                       #geom_hline(yintercept = sab.bmsy/1000,color=u.colors[1],linetype='solid',size=1.5) +
                       scale_x_continuous('') +
                       scale_y_continuous('Fully-recruited Biomass (tonnes x 1000)') +
                       theme(legend.position = "none")

save_plot(sab.mod.real.plt,file = paste0(plot.sab.rp.mod.loc,min(sab.model.yrs),"-",max(sab.model.yrs),"/Sim_reals_w_RPS.png"),base_height = 8.5,base_width=8.5)



```

```{r sab-hcr-sims,include =F}

# HCR specific settings
set.seed(4)
sab.trp.exp <- 0.05
sab.usr.exp <- 0.01
sab.lrp.exp <- 0
sab.exp.sd <- 0.1 


hcr.strat <-list(TRP = sab.trp.bmsy,TRP.exp = sab.trp.exp,
                 USR = sab.usr.b0, USR.exp = sab.usr.exp, 
                 LRP = sab.lrp.b0, LRP.exp = sab.lrp.exp,exp.sd = sab.exp.sd)
# The g/m/r.strat are in the productivity section...
# For elsewhere, this is the HCR figure plot directory
sab.HCR <- paste0("T_",hcr.strat$TRP,"_",hcr.strat$TRP.exp,"_U_",hcr.strat$USR,"_",hcr.strat$USR.exp,"_L_",hcr.strat$LRP,"_",hcr.strat$LRP.exp)
sab.hcr.plt.loc <- paste0(plot.sab.rp.mod.loc,"HCR/",sab.HCR,"/")
sab.hcr.res.loc <- paste0(res.sab.rp.mod.loc,"HCR/",sab.HCR,".Rds")
if(run.sims == T)
{
# An HCR model
sab.hcr <- proj.mod(mods = list(bssm.mod = sab.mod),n_sim=n_sims,n_y = n_y,model=mod.4.sab,
                run = 'no_model_error',  
                plot_url = plot.sab.rp.mod.loc,  res_url = res.sab.rp.mod.loc,save.results = T,
                g.mod =   list(type = g.strat$type,bp.strategy = g.strat$strat,bp= g.strat$bp,set.g = g.strat$set.g,cen.tend = g.strat$cen.tend),
                               #mn.at.max = g.strat$mn.at.max,sd.at.max =g.strat$sd.at.max), 
                rec.mod = list(type = r.strat$type,bp.strategy = r.strat$strat,bp= r.strat$bp, 
                               rec.age = r.strat$rec.age,rps.m.cor = r.strat$rps.m.cor,rps.m.lag = r.strat$rps.m.lag,cen.tend = r.strat$cen.tend,
                               ar1=r.strat$ar1,ar2=r.strat$ar2,
                               mn.at.max = r.strat$mn.at.max,sd.at.max =r.strat$sd.at.max), 
                m.mod =   list(type = m.strat$type,bp.strategy = m.strat$strat,bp= m.strat$bp, cen.tend = m.strat$cen.tend,#mn.at.max = m.strat$mn.mx,sd.at.max = m.strat$sd.mx,
                                ar1=m.strat$ar1,ar2=m.strat$ar2),
                HCR.sim = list(TRP = hcr.strat$TRP,TRP.exp = hcr.strat$TRP.exp, USR = hcr.strat$USR, USR.exp = hcr.strat$USR.exp,
                               LRP = hcr.strat$LRP, LRP.exp = hcr.strat$LRP.exp,exp.sd = hcr.strat$exp.sd))
}
if(run.sims == F) sab.hcr <- readRDS(sab.hcr.res.loc)
  
sab.mn.catch.hcr <- round(mean(sab.hcr$Catch,na.rm=T),digits=0)
sab.med.catch.hcr <- round(median(sab.hcr$Catch,na.rm=T),digits=0)
sab.med.bm.hcr <- round(median(sab.hcr$B),digits=0)

# For this I need to use the summarized object
sab.hcr.last.yrs <- sab.hcr$Exp.res[sab.hcr$Exp.res$year > (n_y-last.yrs),]
sab.prop.yrs.bl.lrp.hcr <- round(100*length(which(sab.hcr.last.yrs$B  < sab.lrp.b0))/n_sims/last.yrs,digits=2)
sab.prop.yrs.cautious.hcr <- round(100*length(which(sab.hcr.last.yrs$B >= sab.lrp.b0 & sab.hcr.last.yrs$B < sab.usr.b0))/n_sims/last.yrs,digits=1)
sab.prop.yrs.healthy.hcr <- round(100*length(which(sab.hcr.last.yrs$B >= sab.usr.b0 & sab.hcr.last.yrs$B < sab.trp.bmsy))/n_sims/last.yrs,digits=1)
sab.prop.yrs.above.trp.hcr <- round(100*length(which(sab.hcr.last.yrs$B > sab.trp.bmsy))/n_sims/last.yrs,digits=1)

sab.min.healthy.zone.catch.hcr <- sab.usr.b0*0.025
sab.max.healthy.zone.catch.hcr <- sab.trp.bmsy*0.025
sab.min.trp.catch.hcr <- sab.trp.bmsy*sab.trp.exp
sab.catch.quants.hcr <- quantile(sab.hcr$Catch,na.rm=T,probs = seq(0,1,by=0.01))

# model catchability...
sab.q <- round(median(sab.mod$sims.list$q),digits=2)

```