---
title: "BBn and Sable Reference Point exploration"
author: "DK based on RM"
date: "Fall 2022"
output:
  bookdown::pdf_document2: 
    extra_dependencies: ["subfig","float"]
    citation_package: natbib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r global-crap,include=F}
library(tidyverse)
library(knitr)
library(tinytex)
library(kableExtra)
library(dplyr)
library(SEBDAM)
library(ggthemes)
library(cowplot)
library(forecast)

theme_set(theme_few(base_size = 22))
u.colors <- c("#FFD500","#005BBB")

# Here's where I'm sticking the figures
mod.loc <- "D:/Framework/SFA_25_26_2024/Model/"
fun.loc <-"D:/Github/Framework/RefPts/functions/"
rp.loc <- "D:/Framework/SFA_25_26_2024/RefPts/"

# Functions we need to source for this to all work
source(paste0(fun.loc,"projection_function.r"))
source(paste0(fun.loc,"Density_dependence_function.R"))
source(paste0(fun.loc,"breakpoint_function.R"))
source(paste0(fun.loc,"correlation_function.R"))

# Model run parameters
years <- 1994:2022
R.size <- "75"
FR.size <- "90"
num.knots <- 10 # Going to test 10, 15, and 20
qR <- 0.33# This is for TMB (log recruit catchability) testing catchability of 0.5, test 0.3 and 0.1
init.m <- 0.2 # This is for SEAM, sets first year natural mortality, going to test 0.4, 0.15, and 0.05
# Various explorations of the g models.
g.mod <- 'g_original'
#g.mod <- 'alt_g'
#g.mod <- 'proper_g'



#Loading the output from TLM BBN model
#tlm.select <- "1994_2022_qR_0.45"
# tlm.select <- paste0(min(years),"_",max(years),"_qR_",qR,"_",g.mod)
# tlm.mod <- readRDS(paste0(mod.loc,"Results/Sab/R_75_FR_90/Sab_TLM_model_output_",tlm.select,".Rds"))
# tlm.mod$report$totB <- tlm.mod$report$B
# tlm.mod$report$totR <- tlm.mod$report$R
# tlm.mod$report$mean_m <- tlm.mod$report$m
#get_parameters(tlm.mod)
#tlm.mod$report$gI <- tlm.mod$report$g


# # If running with SEBDAM this is what ya use.
#seam.select <- "1994_2022_vary_m_m0_2_qR_0.5_10_knots"
seam.select <- paste0(min(years),"_",max(years),"_vary_m_m0_",init.m,"_qR_",qR,"_",num.knots,"_knots_",g.mod)
#seam.select <- "1994_2022_vary_m_m0_2_qR_0.5_7_knots"
seam.mod <- readRDS(paste0(mod.loc,"Results/Sab/R_75_FR_90/Sab_SEAM_model_output_",seam.select,".Rds"))
pred.proc.seam <- get_processes(seam.mod)
seam.mod$obj$env$data$g <- seam.mod$obj$env$data$gI
seam.mod$report$totR <-c(seam.mod$report$totR,NA)
#get_parameters(seam.mod)

```

```{r productivity-analysis,include=F}

# Setup...
num.knots <- length(seam.mod$obj$env$data$area)
years <- 1994:2023
NY <- length(years)
matYear<-c(rep(years,each=num.knots))
knots<-rep(1:num.knots,NY)

# TLM version
# prod.dat <- data.frame(Year = 1991:2022,
#                         B = tlm.mod$report$totB[-length(tlm.mod$report$totB)],
#                         R = tlm.mod$report$totR[-length(tlm.mod$report$totR)], # For some reason the SEBDAM run needs a NA at the end here.
#                         SSB = tlm.mod$report$totB[-length(tlm.mod$report$totB)] + tlm.mod$report$totR[-length(tlm.mod$report$totR)],
#                         m = tlm.mod$report$mean_m[-length(tlm.mod$report$mean_m)],
#                         g = tlm.mod$obj$env$data$g[],
#                         gR = tlm.mod$obj$env$data$gR[])#,
#                         CF = cond.dat$CF)
#plot.url <- paste0("D:/Github/BBn_model/Results/Figures/Sab/Ref_points/",tlm.select,"/")

### ENd TLM Productivity Data

# SEAMly version
prod.dat <- data.frame(Year = years[-NY],
                        B = seam.mod$report$totB[-length(seam.mod$report$totB)],
                        R = seam.mod$report$totR[-length(seam.mod$report$totR)], # For some reason the SEBDAM run needs a NA at the end here.
                        SSB = seam.mod$report$totB[-length(seam.mod$report$totB)] + seam.mod$report$totR[-length(seam.mod$report$totR)],
                        m = seam.mod$report$mean_m[-length(seam.mod$report$mean_m)],
                        g = c(seam.mod$obj$env$data$g[-length(seam.mod$obj$env$data$g)]),
                        gR = c(seam.mod$obj$env$data$gR[-length(seam.mod$obj$env$data$gR)]))#,
                        #g = c(seam.mod$obj$env$data$g),
                        #gR = c(seam.mod$obj$env$data$gR))
                        #CF = cond.dat$CF[cond.dat$year %in% years[-length(years)]])
plot.url <- paste0(rp.loc,"Figures/Sab/R_75_FR_90/SEAM_",seam.select,"/")

prod.dat[prod.dat$Year %in% c(2015,2020),-1] <- NA

# The Natural mortality term didn't used to be weighted, but it is not, so this is not necessary any more.
# bmr <- data.frame(B=as.vector(seam.mod$report$areaB/1000),
#                   m=as.vector(seam.mod$report$m),
#                   R=c(as.vector(seam.mod$report$areaR/1000),rep(0,num.knots)), # Probably should be NAs for taht final year, but lets us easily get an m estimate for the projection year (only based on B)
#                   Year=matYear, knotID=knots)
# # Now get an m estimate for the whole area for B, R, and both, I think easiest will be to get totB and totR by year in here...
# tBR <- bmr %>% group_by(Year) %>% dplyr::summarise(totB = sum(B,na.rm=T),
#                                                    totR = sum(R,na.rm=T),
#                                                    totSSB = sum(B,na.rm=T) + sum(R,na.rm=T))
# # Now merge that with bmr...
# bmr <- left_join(bmr,tBR,by="Year")

# # Now getting weighted means by year should be easy...
# nat.mat <- bmr %>% group_by(Year) %>% dplyr::summarise(m.FR = sum(B*m/totB,na.rm = T),
#                                                        m.R  = sum(R*m/totR,na.rm=T),
#                                                        m.all= sum((R+B)*m/totSSB))
# nat.mat$m.seam <- seam.mod$report$mean_m

# # We could use m.FR, or have separate M's here for R or FR if we wanted, several options worth discussing.
# prod.dat$m <- nat.mat$m.all[-length(nat.mat$m.all)]
# # Natural mortality comparison
# # I also want to replace the m in the SEAM model with the weighted mean.  I don't think it's gonna make a huge difference, but it is better.
# seam.mod$report$mean_m <- nat.mat$m.all
# Now make a figure showing the differences, need to pivot longer here.
# nat.mat <- nat.mat[-nrow(nat.mat),] # Don't want 2023 in this...
# nat.mat.long <- pivot_longer(nat.mat,-Year,names_to = "cat",values_to = "m") # or c("m.FR","m.R","m.all")
# # Now make a plot to compare these.
# m.comp <- ggplot(nat.mat.long,aes(x= Year,y=m,group=cat,color=cat)) + geom_point(size=3) + geom_line(linewidth=1.5) + 
#                                                                       xlab("") + ylab("Natural Mortality (instantaneous)") +
#                                                                       scale_y_continuous(breaks = seq(0,1.6,by=0.1)) + 
#                                                                       scale_x_continuous(breaks = seq(1980,2025,by=5)) + 
#                                                                       scale_color_manual(values = c("blue","firebrick2","grey","orange"),name = "",
#                                                                                          breaks=c("m.all", "m.FR","m.R","m.seam"),
#                                                                                          labels=c("Weighted", "FR","Rec","Original")) 
# save_plot(paste0(plot.url,"Natural_mortality_comparison.png"),m.comp,base_height = 6,base_width = 10)  

# # Comparing the TLM and SEAM results, as you change the number of knots is makes increasingly more sense.
# two.mods <- data.frame(years = rep(years,2),model = c(rep("SEAM",NY),rep("TLM",NY)),
#                        B = c(seam.mod$report$totB,tlm.mod$report$totB),
#                        R = c(seam.mod$report$totR,tlm.mod$report$totR),
#                        m = c(seam.mod$report$mean_m,tlm.mod$report$mean_m))
# 
# p1 <- ggplot(two.mods,aes(x=years,y = B,group=model,color=model)) + geom_line(linewidth=1.5) + 
#                                                                     ylab("Biomass (tonnes)") + xlab("") +
#                                                                     scale_x_continuous(breaks = seq(1980,2025,by=5)) + 
#                                                                     scale_color_manual(values = c("blue","firebrick2"),guide = guide_legend(override.aes = list(alpha = 0) )) +
#                                                                     theme(legend.title = element_text(color = "transparent"),
#                                                                           legend.text = element_text(color = "transparent"))
# 
# 
# p2 <- ggplot(two.mods,aes(x=years,y = R,group=model,color=model)) + geom_line(linewidth=1.5) +  
#                                                                     ylab("Recruits (tonnes)") + xlab("")+
#                                                                     scale_x_continuous(breaks = seq(1980,2025,by=5)) + 
#                                                                     scale_color_manual(values = c("blue","firebrick2"))
# 
# 
# p3 <- ggplot(two.mods,aes(x=years,y = m,group=model,color=model)) + geom_line(linewidth=1.5) +  
#                                                                     ylab("Natural mortality (instantaneous)") + xlab("") +
#                                                                     scale_x_continuous(breaks = seq(1980,2025,by=5)) + 
#                                                                     scale_color_manual(values = c("blue","firebrick2"),guide = guide_legend(override.aes = list(alpha = 0) )) +
#                                                                     theme(legend.title = element_text(color = "transparent"),
#                                                                           legend.text = element_text(color = "transparent"))
#                                                                     
# 
# p.tlm.seam <- cowplot::plot_grid(p1,p2,p3,nrow=3)
# save_plot(paste0(plot.url,"SEAM_vs_TLM.png"),p.tlm.seam,base_height = 18,base_width = 10)                                                                      



# Now we can get common Recruitment data R3 assumes recruits are 3 year olds, r4 are 4 year olds etc.
prod.dat$R3 <- c(prod.dat$R[4:nrow(prod.dat)],NA,NA,NA)
prod.dat$R4 <- c(prod.dat$R[5:nrow(prod.dat)],NA,NA,NA,NA)
prod.dat$R5 <- c(prod.dat$R[6:nrow(prod.dat)],NA,NA,NA,NA,NA)
prod.dat$R6 <- c(prod.dat$R[7:nrow(prod.dat)],NA,NA,NA,NA,NA,NA)
# Assume Scallop reach recruit size at age 3, will need to check that.
prod.dat$RPS3 <- prod.dat$R3/prod.dat$SSB 
prod.dat$RPS4 <- prod.dat$R4/prod.dat$SSB 
prod.dat$RPS5 <- prod.dat$R5/prod.dat$SSB
prod.dat$RPS6 <- prod.dat$R6/prod.dat$SSB


### STEP 1, how old are recruits??
# First of all what is the likely age of recruits, for Sable we have 80-90 mm recruits, our tentative von B parameters are...
# Data is coming from ageing data in 1989, found here.... Y:\Offshore\Assessment\Data\Ageing\archive\old_ageing_from_Amy_2022\SAB height at age 1989_2.pdf 
von.B <- function(L.inf,to,K,age,R.size,FR.size) 
{
  L <- L.inf*(1-exp(-K*(age-to)))
  res <- data.frame(L = L, age=age)
  min.R <- min(abs(res$L - R.size))
  min.FR <- min(abs(res$L - FR.size))
  R.age <- res$age[which(abs(res$L - R.size) == min.R)]
  FR.age <- res$age[which(abs(res$L - FR.size) == min.FR)]
  bins <- data.frame(Age = c(R.age,FR.age), size = c(R.size,FR.size),class = c("Recruits","Fully Recruited"))
  return(res <- list(res=res,bins = bins))
}

# There is no ageing for Sable since like the late 1980's, so for now I base this on that data, until we have new data, hopefully coming soon!! 
# The interim values come from files found in here... Y:\Offshore\Assessment\Data\Ageing\archive\old_ageing_from_Amy_2022
# Particularly SAB height at age 1989.pdf
L.inf <- 159.2
#to <- 1.335 # So this uses a 1 year offset that we no longer believe in, going to make this 0.335 to align more with what we now do...
to <- 0.2
K <- 0.2
ages <- seq(0,15,by=0.05)
R.size = 75
FR.size = 90
res <- von.B(L.inf,to,K,ages,R.size =R.size,FR.size = FR.size)


# So here we see that 4 year olds are 77 mm 5 year olds are around 87 mm, so seems like assuming recruits are 4 years old makes sense here
# A recruit size bin of 10 mm seems to make sense, could perhaps stretch it to 15 mm, will see what the new data shows.
p.vb <- ggplot(res$res) + geom_line(aes(x=age,y=L),size=1.5) + scale_x_continuous(breaks = 0:max(ages), expand = c(0, 0))  + 
                          scale_y_continuous(limits = c(1,L.inf),breaks = c(seq(0,150,by=5)), expand = c(0, 0)) + 
                          xlab("Age") + ylab("Shell height (mm)") +
                          geom_segment(data = res$bins %>% dplyr::filter(class == "Recruits"), aes(x=0,y=size,xend=Age,yend=size),linetype = 'dashed',color="blue") +
                          geom_segment(data = res$bins %>% dplyr::filter(class == "Recruits"), aes(x=Age,y=1,xend=Age,yend=size),linetype = 'dashed',color="blue") +
                          geom_segment(data = res$bins %>% dplyr::filter(class == "Fully Recruited"), aes(x=0,y=size,xend=Age,yend=size),linetype = 'dashed',color="darkgreen") +
                          geom_segment(data = res$bins %>% dplyr::filter(class == "Fully Recruited"), aes(x=Age,y=1,xend=Age,yend=size),linetype = 'dashed',color="darkgreen") 
save_plot(paste0(plot.url,"von_B.png"),p.vb,base_height = 6,base_width = 10)                                                                      



# OK, so we see recruits are probably 3-4 years old based on that von B, so we could use either RPS3 or RPS4 for the density dependence 
# See a very strong signal for both ages.  I'm going to go with 5 year olds as recruits, it's consistent with BBn and the recruit size bin mean would be 
# closer to 5 than 4 based on the von B.  It shouldn't make much difference as the relationship is quite strong.
p.rps.ts <- ggplot(prod.dat, aes(x=Year,y=RPS4))  + geom_point() + 
                                                    xlab("'Birth' year") + ylab("Recruits per Spawner (kg\u00B9\u22C5kg\u207B\u00B9)") +
                                                    geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 7))+
                                                    scale_y_log10() +  
                                                    scale_x_continuous(breaks = c(seq(1980,2080,by=5)))# Definitely a signal here
save_plot(paste0(plot.url,"RPS_ts.png"),p.rps.ts,base_height =6,base_width = 10)                                               
                       
# Density dependence 
p.rps.ssb <- ggplot(prod.dat,aes(y=RPS4,x=SSB)) + geom_text(aes(label = substr(Year,3,4)),size=3) + 
                                                  xlab("Spawning Stock Biomass (tonnes)") + ylab("Recruits per Spawner (kg\u00B9\u22C5kg\u207B\u00B9)") +
                                                  geom_smooth(method = 'lm') +
                                                  scale_y_log10() + geom_vline(xintercept = 7150,size=0.5,color='firebrick2',linetype='dashed')  + 
                                                  scale_x_continuous(breaks = c(seq(1000,20000,by=1000)))# Definitely a signal here
save_plot(paste0(plot.url,"RPS_vs_SSB.png"),p.rps.ssb,base_height =6,base_width = 10)        
# So what does this tell us? DK interpretation
#1: The late 90's was also a aberration on Sable, the highest recruits all from the same period as we saw really high recruitment on BBn, that's interesting.


# Next is there any evidence of Density dependence with growth?
# Absolutely no evidence of DD!
p.rec.ssb <- ggplot(prod.dat,aes(y=R5,x=SSB)) + geom_text(aes(label = substr(Year,3,4)),size=3)  +
                                                xlab("Spawning Stock Biomass (tonnes)") + ylab("Recruits (tonnes)") +
                                                geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +scale_y_log10() +
                                                geom_vline(xintercept = 7150,size=0.5,color='firebrick2',linetype='dashed')  + 
                                                scale_x_continuous(breaks = c(seq(1000,20000,by=1000)))
save_plot(paste0(plot.url,"Rec_vs_SSB.png"),p.rec.ssb,base_height =6,base_width = 10)    

# No relationship between g and SSB.
p.g.ssb <- ggplot(prod.dat,aes(y=g,x=SSB)) + geom_text(aes(label = substr(Year,3,4))) +
                                             xlab("") + ylab("Growth (Fully Recruited)") +
                                             geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +
                                             #geom_vline(xintercept = 9000,size=0.5,color='firebrick2',linetype='dashed')  + 
                                             scale_x_continuous(breaks = c(seq(1000,20000,by=1000),labels = NA))

p.gR.ssb <- ggplot(prod.dat,aes(y=gR,x=SSB)) + geom_text(aes(label = substr(Year,3,4))) +
                                             xlab("Spawning Stock Biomass (tonnes)") + ylab("Growth (Recruits)") +
                                             geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +
                                             #geom_vline(xintercept = 9000,size=0.5,color='firebrick2',linetype='dashed')  + 
                                             scale_x_continuous(breaks = c(seq(1000,20000,by=1000)))

p.gs.ssb <-  cowplot::plot_grid(p.g.ssb,p.gR.ssb,nrow=2)

save_plot(paste0(plot.url,"Growth(FR)_vs_SSB.png"),p.gs.ssb,base_height =12,base_width = 10)  

# Naturnal mortality and SSB, not really anything IMHO.
p.m.ssb <- ggplot(prod.dat,aes(y=m,x=SSB)) + geom_text(aes(label = substr(Year,3,4)))+ 
                                             xlab("Spawning Stock Biomass (tonnes)") + ylab("Natural Mortality (instantaneous)") +
                                             geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +
                                             geom_vline(xintercept = 10000,size=0.5,color='firebrick2',linetype='dashed')  + 
                                             scale_x_continuous(breaks = c(seq(1000,20000,by=1000)))
save_plot(paste0(plot.url,"M_vs_SSB.png"),p.m.ssb,base_height =6,base_width = 10)                

# RPS and Growth is a big nothing
p.rps.g <- ggplot(prod.dat ,aes(y=RPS5,x=g)) + geom_text(aes(label = substr(Year,3,4))) + 
                                               xlab("Growth (Fully Recruited)") + ylab("Recruits per Spawner (kg\u00B9\u22C5kg\u207B\u00B9)") +
                                               geom_smooth(method = 'gam',formula = y ~ s(x, bs = "cs", k = 3)) +
                                               #geom_vline(xintercept = 1.2,size=0.5,color='firebrick2',linetype='dashed') # + 
                                               scale_x_continuous(breaks = c(seq(0.8,2,by=0.1)))+ scale_y_continuous(breaks = seq(0,2,by=0.1)) 

save_plot(paste0(plot.url,"RPS_vs_Growth.png"),p.rps.g,base_height =6,base_width = 10)                

# So there is the Density dependence analysis, not much you ca do with Growth or M, but something certainly there with Recruits and SSB that should be
# built into the model, though I remain convinced using a traditional SR-model is a bad idea simply because of need to extrapolate it.

# Step 2.... Correlation
# Next thing you should consider is whether there are correlations in your productivity parameters, first look to autocorrelated time series
# Then you want to look for cross-correlations between mortality, recruitment, and growth, for example maybe growth is low in years when M is high
# This will matter to your simulations, so investigate it.
# First let's look for acf in our time series...
# Starting with recruitment we see there is a strong autocorrlation in the total number of recruits
p.rec.acf <- ggAcf(na.omit(prod.dat$R)) + ggtitle("")+ ylab("ACF Recruits")
save_plot(paste0(plot.url,"ACF_Rec.png"),p.rec.acf,base_height =6,base_width = 10)                
# But is this simply due to the underlying trend in R over time... possible, but really what is there is a very strong long cycle rather than a linear trend so ignoring this...
rec.mod <- lm(R ~ I(Year-1994),data=prod.dat)
summary(rec.mod)
# So probably better to look at per capita recruitment and see if that is a better acf'er...
# And here we do see the correlation remains.
p.rps.acf <- ggAcf(na.omit(log(prod.dat$RPS5))) + ggtitle("") + ylab("ACF log(RPS)")
save_plot(paste0(plot.url,"ACF_RPS.png"),p.rps.acf,base_height =6,base_width = 10)                


# pacf shows us that we could approximate the RPS time series as an AR1, though there is a teaser of the 2 year negative correlation similar to what we found on BBn.
# could easily enough model as an AR2 and use that. Also a 5 year correlation there, which I think is that longer term cycle.  But ignoring that...
p.rps.pacf <- ggPacf(na.omit(log(prod.dat$RPS5))) + ggtitle("") + ylab("PACF log(RPS)")
save_plot(paste0(plot.url,"PACF_RPS.png"),p.rps.pacf,base_height =6,base_width = 10)   

# On the log scale we see there is no trend in the data, t
rps.mod <- lm(log(RPS5) ~ I(Year-1994),data=prod.dat)
summary(rps.mod) # Indeed there is...


# How about growth, nope nothing.
p.g.acf <- ggAcf(prod.dat$g) + ggtitle("") + ylab("ACF Growth (FR)")# No autocorrelation in Condition
p.gR.acf <- ggAcf(prod.dat$gR) + ggtitle("") + ylab("ACF Growth (Recruits)")# No autocorrelation in Condition
p.gs.acf <-  cowplot::plot_grid(p.g.acf,p.gR.acf,nrow=2)

save_plot(paste0(plot.url,"ACF_growths.png"),p.gs.acf,base_height =12,base_width = 10)                

# Natural morality correlation? Curious, no correlation at 1 lag, but a negative correlation at lag 2, suggesting the m is flipping every couple years I think?
p.m.acf <- ggAcf(prod.dat$m) + ggtitle("") + ylab("ACF Natural Mortality") + xlab("") + scale_x_continuous(breaks = 1:14,labels=NULL) # No autocorrelation in Condition
p.m.pacf <- ggPacf(prod.dat$m) + ggtitle("") + ylab("PACF Natural Mortality")# No autocorrelation in Condition
p.m.acfs <-  cowplot::plot_grid(p.m.acf,p.m.pacf,nrow=2)
save_plot(paste0(plot.url,"ACF_m.png"),p.m.acfs,base_height =12,base_width = 10)                

# So check if there is a linear trend, and there is...
mod.m <- lm(m~I(Year-1993),data=prod.dat)
summary(mod.m) # No trend


# So next up lets look for evidence of correlation between your productivity parameters, specifically RPS and m
prod.dat$RPS4_offset <- c(rep(NA,4),prod.dat$RPS4[-((length(prod.dat$RPS4)-3):length(prod.dat$RPS4))])
ggplot(prod.dat,aes(x=Year,y=RPS4)) +geom_point() + geom_line(size=2) + geom_point(aes(y = m)) + geom_line(aes(y = m),color='blue') #+ geom_smooth(method = 'gam')
ggplot(prod.dat,aes(x=m,y=RPS4)) + geom_text(aes(label = substr(Year,3,4))) + geom_smooth(method = 'gam')
# If we offset the RPS to the year they are actually showing up, might be some weak correlation, but can't say it's anything more than noise, so we can ignore this I think.
p.rpsoff.m <- ggplot(prod.dat,aes(x=Year,y=RPS4_offset)) + geom_text(aes(label = substr(Year-5,3,4)))  + 
                                                           xlab("") +ylab("Recruits per Spawner (kg\u00B9\u22C5kg\u207B\u00B9) & Natural mortality (Inst)") +
                                                           geom_line(aes(y = m),color='firebrick2',size=1,linetype='dashed')
p.rps.m.ccf <- ggCcf(prod.dat$m,prod.dat$RPS4_offset) + ggtitle("")

p.rps.m.ccf.combo <-  cowplot::plot_grid(p.rpsoff.m,p.rps.m.ccf,nrow=2)
save_plot(paste0(plot.url,"CCF_ts_RPS_offset_m.png"),p.rps.m.ccf.combo,base_height =12,base_width = 10)                
      


# Now moving on to make some other useful figures we'll want for the show.

catchy <- seam.mod$obj$env$data$C*seam.mod$obj$env$data$area # Get this into tonnes from catch density.
#if(mod.select == "TLM") catchy <- mod.fit$obj$env$data$C
  
pred.proc.seam$log_tot_frame$totB.LCI <- exp(pred.proc.seam$log_tot_frame$log_totB - 1.96*pred.proc.seam$log_tot_frame$se_log_totB)
pred.proc.seam$log_tot_frame$totB.UCI <- exp(pred.proc.seam$log_tot_frame$log_totB + 1.96*pred.proc.seam$log_tot_frame$se_log_totB)

# See above for explanation of how I'm doing these calculations to be consistent with the past
ann.exploit <- data.frame(year = years[-length(years)],B = exp(pred.proc.seam$log_tot_frame$log_totB)[-length(years)], Catch = colSums(catchy)[-length(years)],
                          B.LCI = pred.proc.seam$log_tot_frame$totB.LCI[-length(years)], B.UCI = pred.proc.seam$log_tot_frame$totB.UCI[-length(years)])
ann.exploit$exploit <- c(NA,ann.exploit$Catch[-nrow(ann.exploit)])/(ann.exploit$B+c(NA,ann.exploit$Catch[-nrow(ann.exploit)]))
ann.exploit$exploit.UCI <- c(NA,ann.exploit$Catch[-nrow(ann.exploit)])/(ann.exploit$B.LCI+c(NA,ann.exploit$Catch[-nrow(ann.exploit)]))
ann.exploit$exploit.LCI <- c(NA,ann.exploit$Catch[-nrow(ann.exploit)])/(ann.exploit$B.UCI+c(NA,ann.exploit$Catch[-nrow(ann.exploit)]))
ann.exploit$FM <- 1-exp(-ann.exploit$exploit)
ann.exploit$FM.LCI <- 1-exp(-ann.exploit$exploit.LCI)
ann.exploit$FM.UCI <- 1-exp(-ann.exploit$exploit.UCI)

  
ann.exploit$delta.B <- NA
ann.exploit$delta.B.per <- NA
ann.exploit$SP <-NA

for(i in 2:(length(years)-1)) 
{
  ann.exploit$delta.B[i] <- ann.exploit$B[i] - ann.exploit$B[i-1]
  ann.exploit$delta.B.per[i] <- (ann.exploit$B[i] - ann.exploit$B[i-1])/ ann.exploit$B[i-1] * 100
  ann.exploit$SP[i] <-   ann.exploit$B[i] -  ann.exploit$B[i-1] +  ann.exploit$C[i-1]
}

# We need to toss 2015 and 2020, but also the year after given how exploitation is across two years.
ann.exploit <- ann.exploit %>% dplyr::filter(!year %in% c(2015:2016,2020:2021))



# Exploitation + uncertainty
#windows(11,11)
exploit.plot <- ggplot(ann.exploit) + geom_line(aes(x=year,y=exploit),size=1.5,color= u.colors[2]) +   
                                      geom_ribbon(aes(ymin=exploit.LCI,ymax=exploit.UCI,x=year),alpha=0.5,fill=u.colors[2],color=u.colors[2]) +
                                      xlab("") + ylab("Exploitation Rate (Proportional)") + scale_x_continuous(breaks = seq(1980,2030,by=3)) + ylim(c(0,0.09))
save_plot(paste0(plot.url,"Exploit_ts.png"),exploit.plot,base_height =12,base_width = 10)                

# Kobe plot
#windows(11,11)
kobe.plt <- ggplot(ann.exploit,aes(x=B,y=exploit)) + geom_text(aes(label=year)) +  xlim(c(0,NA)) + 
                                    annotate(geom="rect",xmin=0,xmax=5500,ymin=0.02,ymax=Inf, fill = "red", alpha=0.5)+
                                    annotate(geom="rect",xmin=5500,xmax=Inf,ymin=0,ymax=0.02, fill="green", alpha = 0.5) +
                                    annotate(geom="rect",xmin=0,xmax=5500,ymin=0,ymax=0.02, fill="gold1", alpha = 0.6) +
                                    annotate(geom="rect",xmin=5500,xmax=Inf,ymin=0.02,ymax=Inf, fill="gold1", alpha = 0.6) +
                                    geom_path(aes(y= exploit, x= B )) + 
                                    xlab("Biomass (Tonnes)") + ylab("Exploitation Rate (Proportional)") +
                                    geom_hline(yintercept = 0.03,linetype='dashed') + geom_vline(xintercept = 4000,linetype='dashed')

save_plot(paste0(plot.url,"Kobe_plot.png"),kobe.plt,base_height =12,base_width = 10)                

# Same this with LRP and USR and FMSY
# The phase plot
#windows(11,11)
phase.plt <- ggplot(ann.exploit,aes(x=B,y=exploit)) + geom_text(aes(label=year)) +  xlim(c(0,NA)) + 
                                    annotate(geom="rect",xmin=-Inf,xmax=1350,ymin=-Inf,ymax=Inf, fill = "red", alpha=0.5)+
                                    annotate(geom="rect",xmin=1350,xmax=3000,ymin=-Inf,ymax=Inf, fill="gold1", alpha = 0.5) +
                                    annotate(geom="rect",xmin=3000,xmax=Inf,ymin=-Inf,ymax=Inf, fill="green", alpha = 0.6) +                                  
                                    geom_path(aes(y= exploit, x= B )) +
                                    geom_hline(yintercept = 0.06,linetype='dashed') + geom_vline(xintercept = c(1350,3000),linetype='dashed') +
                                    xlab("Biomass (Tonnes)") + ylab("Exploitation Rate (Proportional)") 
save_plot(paste0(plot.url,"Phase_plot.png"),phase.plt,base_height =12,base_width = 10)                
    
# Now that explotation vs Biomass figure...
#windows(11,11)
ggplot(ann.exploit,aes(y=delta.B,x=exploit)) + geom_text(aes(label=year)) + geom_smooth(method='lm') +
                                          geom_hline(yintercept = 0,linetype='dashed')
                                    
   # Now that explotation vs Biomass figure... The JEM plot (Jessica's Empirical Method)....
#windows(11,11)
jem.plt <- ggplot(ann.exploit,aes(y=delta.B.per,x=exploit)) + geom_text(aes(label=year)) + geom_smooth(method='lm',color=u.colors[2],fill=u.colors[2],alpha=0.2) +
                                                              geom_hline(yintercept = 0,linetype='dashed')   +  
                                                              xlab("Exploitation Rate (Proportional)") + ylab("Biomass Change (%)")                             
save_plot(paste0(plot.url,"JEM_plot.png"),jem.plt,base_height =6,base_width = 10)                


# Again the explotation rate against biomass but without any bells and whistles, just looking for patterns...
# And there are no real strong patterns,mu might be slightly lower at abundances above 5000...
ggplot(ann.exploit,aes(x=B,y=exploit)) + geom_text(aes(label=year)) + geom_smooth(method='gam')
# So here we can use this infor to explore potential HCR's based on what the fishery has done in the past 
B.exp <- mean(ann.exploit$exploit,na.rm=T)
B.exp.2010s <- mean(ann.exploit$exploit[ann.exploit$year %in% 2011:2019],na.rm=T)
low.B.exp <- mean(ann.exploit$exploit[ann.exploit$B < 5000])
hi.B.exp <- mean(ann.exploit$exploit[ann.exploit$B >= 5000],na.rm=T)
low.B.exp <- sd(ann.exploit$exploit[ann.exploit$B < 5000])
hi.B.exp <- sd(ann.exploit$exploit[ann.exploit$B >= 5000],na.rm=T)

# A surplus production figure


```

```{r productivity-simulations,include=F}



 # RUNME
#g.strat <- data.frame(type = "cor",strat = 'dist', bp = 0,mn.mx = 1, sd.mx = 0.05,ar1=0,ar2=0) # The g correlation method seems to get g a bit too  high.
g.strat <- data.frame(type = "sv",set.value = 1,strat = 'dist', bp = 0,mn.mx = 1, sd.mx = 0.05,set.g=NA,set.gR=NA)
# This is to compare with the decision table with g and gR set at 1... you can see the stock is screwed without the g and gR terms....
#g.strat <- data.frame(type = "set",set.g = 1,set.gR =1,strat = 'dist', bp = 8e3,mn.mx = 1, sd.mx = 0.05)

#g.strat <- data.frame(type = "lm",strat = "Linear", bp = "Model",mn.mx = 1, sd.mx = 0.05)
r.strat <- data.frame(type = "bp",strat = 'dist', bp = 4.5e3, mn.mx = signif(min(prod.dat$RPS4,na.rm=T),digits=2), sd.mx = 0.2,rec.age=4,
                     ar1=signif(p.rps.pacf$data$Freq[1],digits=2),ar2=0,rps.m.cor = 0.43,rps.m.lag = 2) # Note lag is -5, high RPS comes 5 years before high m due to RPS offset.
# r.strat <- data.frame(type = "bp",strat = 'dist', bp = 7150,mn.mx = signif(min(prod.dat$RPS4,na.rm=T),digits=2), sd.mx = 0.2,rec.age=5,
#                       ar1=0,ar2=0,rps.m.cor = 0,rps.m.lag = 0)
# #r.strat <- data.frame(type = "lm",strat = "Linear", bp = "Model",mn.mx = signif(min(prod.dat$RPS5,na.rm=T),digits=2), sd.mx = 0.2,rec.age=5)
m.strat <- data.frame(type = "bp",strat = 'dist', bp = 1.e4,mn.mx = 2*signif(mean(prod.dat$m,na.rm=T),digits=2), sd.mx = 0.1,ar1=0,ar2=signif(p.m.pacf$data$Freq[2],digits=2)) #
#m.strat <- data.frame(type = "bp",strat = 'dist', bp = 0,mn.mx = 0.1, sd.mx = 0.1) # Using the maximum here is batshit because it's soo high!!
#m.strat <- data.frame(type = "lm",strat = "Linear", bp = "Model",mn.mx = signif(max(prod.dat$m,na.rm=T),digits=2), sd.mx = 0.1)
mod = "SEAM"
plot_url = "D:/Framework/SFA_25_26_2024/RefPts/Figures/Sab/R_75_FR_90/"
res_url = "D:/Framework/SFA_25_26_2024/RefPts/Results/Sab/R_75_FR_90/"

Res <- proj.mod(mods = list(seam.mod=seam.mod),n_sim=500,n_y = 200,model=mod,plot_url = plot_url, run = 'no_model_error', res_url = res_url,save.results = T, 
                exp.scenario=seq(0,0.2,0.01), mod.run = seam.select,
                #base.yrs = 2008:2022,
                g.mod =   list(type = g.strat$type,set.value = g.strat$set.value,set.gR = g.strat$set.gR, bp.strategy = g.strat$strat,bp= g.strat$bp, 
                               mn.at.max = g.strat$mn.mx,sd.at.max = g.strat$sd.mx,ar1=g.strat$ar1,ar2=g.strat$ar2),
                rec.mod = list(type = r.strat$type,bp.strategy = r.strat$strat,bp= r.strat$bp, mn.at.max = r.strat$mn.mx,sd.at.max = r.strat$sd.mx,rec.age = r.strat$rec.age,
                                ar1=r.strat$ar1,ar2=r.strat$ar2,rps.m.cor = r.strat$rps.m.cor,rps.m.lag = r.strat$rps.m.lag),
                 m.mod =   list(type = m.strat$type,bp.strategy = m.strat$strat,bp= m.strat$bp, mn.at.max = m.strat$mn.mx,
                                sd.at.max = m.strat$sd.mx,ar1=m.strat$ar1,ar2=m.strat$ar2))

Exp.res <- readRDS("D:/Framework/SFA_25_26_2024/RefPts/Results/Sab/R_75_FR_90/SEAM_1994_2022_vary_m_m0_0.2_qR_0.33_10_knots_g_original/RPs/SEAM_g_sv_0_1_dist_1_0.05_r_bp_dist_4500__0.032_0.24_m_bp_dist_10000__0.34_0.1.Rds")


RPs <- Exp.res %>% dplyr::filter(year >= 175) %>% dplyr::group_by(F.scenario) %>% dplyr::summarise(med.B = median(B,na.rm=T),
                                                                                                       med.C = median(Catch,na.rm=T))  

C.at.msy <- max(RPs$med.C)
RR <- RPs$F.scenario[RPs$med.C == C.at.msy] # Nobody would argue with 9% either...
B.msy <- RPs$med.B[RPs$med.C == C.at.msy]
B0 <- RPs$med.B[RPs$F.scenario==0]
# So our LRP options
LRP.B0 <- 0.2 * B0
LRP.3.BMSY <- 0.3 * B.msy
LRP.4.BMSY <- 0.4 * B.msy
# USR and TRP 
USR.B0 <- 0.4 * B0
USR.BMSY <- 0.8 * B.msy
TRP.B.msy <- B.msy
TRP.B0 <- 0.8 * B0

T.msy <- 0.8 * B0

# How long does it take to 'rebuild'

years <- sort(unique(Exp.res$year))
F.scenario <- sort(unique(Exp.res$F.scenario))

time.grid <- expand.grid(scenario = F.scenario,years = years)
time.to <- data.frame(time.grid,Biomass = NA, T.msy = F,T.usr = F, T.lrp=F,T.trp = F)
for(i in years)
{
B.now <- Exp.res %>% dplyr::filter(year %in% i) %>% dplyr::group_by(F.scenario) %>% dplyr::summarise(med.B = median(B,na.rm=T))
time.to$Biomass[time.to$years == i] <- B.now$med.B
# This feels way clunky...
if(any(B.now$med.B >= B.msy)) 
{
  trues <- which(B.now$med.B >= B.msy)
  tmp <- time.to$T.msy[time.to$years == i]
  tmp[trues] <- T
  time.to$T.msy[time.to$years == i] <- tmp
}
if(any(B.now$med.B >= USR.B0))
{
   trues <- which(B.now$med.B >= USR.B0)
  tmp <- time.to$T.usr[time.to$years == i]
  tmp[trues] <- T
  time.to$T.usr[time.to$years == i] <- tmp
}
if(any(B.now$med.B >= LRP.B0))
{
  trues <- which(B.now$med.B >= LRP.B0)
  tmp <- time.to$T.lrp[time.to$years == i]
  tmp[trues] <- T
  time.to$T.lrp[time.to$years == i] <- tmp
}
if(any(B.now$med.B >= TRP.B0))
{
  trues <- which(B.now$med.B >= TRP.B0)
  tmp <- time.to$T.trp[time.to$years == i]
  tmp[trues] <- T
  time.to$T.trp[time.to$years == i] <- tmp
}
}


res.T.msy <- time.to %>% dplyr::group_by(scenario) %>% dplyr::filter(T.msy == T) %>% dplyr::select(scenario,years,Biomass,T.msy)
res.T.usr <- time.to %>% dplyr::group_by(scenario) %>% dplyr::filter(T.usr == T) %>% dplyr::select(scenario,years,Biomass,T.usr)
res.T.lrp <- time.to %>% dplyr::group_by(scenario) %>% dplyr::filter(T.lrp == F) %>% dplyr::select(scenario,years,Biomass,T.lrp)
res.T.trp <- time.to %>% dplyr::group_by(scenario) %>% dplyr::filter(T.trp == T) %>% dplyr::select(scenario,years,Biomass,T.trp)
# So now summarize these...

T.msy <- res.T.msy %>% dplyr::group_by(scenario) %>% dplyr::summarise(T.msy = min(years))
T.usr <- res.T.usr %>% dplyr::group_by(scenario) %>% dplyr::summarise(T.usr = min(years))
T.lrp <- res.T.lrp %>% dplyr::group_by(scenario) %>% dplyr::summarise(T.usr = min(years)) # Hmm...
T.trp <- res.T.trp %>% dplyr::group_by(scenario) %>% dplyr::summarise(T.usr = min(years)) # This tells me that TRP is really unachievable

# End RUNME
#summary(as.vector(Res$B[75:100,,1]))
```

```{r hcr-sims,include =F}

 # RUNME
hcr.strat <-data.frame(TRP = round(TRP.B0),TRP.exp = 0.05, # Try 80% of B@0
                       USR =   round(USR.B0), USR.exp = 0.01, # 40% of B@0
                       LRP = round(LRP.B0), LRP.exp = 0,exp.sd = 0.1) # Around 5500 is the Biomass at 0 catch in the 0.4, 4 knot scenario.
# This is to compare with the decision table with g and gR set at 1... 
g.strat <- data.frame(type = "sv",set.value =1,strat = 'dist', mn.mx = 1, sd.mx = 0.05)
#g.strat <- data.frame(type = "lm",strat = "Linear", bp = "Model",mn.mx = 1, sd.mx = 0.05)
r.strat <- data.frame(type = "bp",strat = 'dist', bp = 4.5e3,mn.mx = signif(min(prod.dat$RPS4,na.rm=T),digits=2), sd.mx = 0.2,rec.age=4,
                     ar1=signif(p.rps.pacf$data$Freq[1],digits=2),ar2=0,rps.m.cor = 0.43,rps.m.lag = 2) # Note lag is -5, high RPS comes 5 years before high m due to RPS offset.
# r.strat <- data.frame(type = "bp",strat = 'dist', bp = 7150,mn.mx = signif(min(prod.dat$RPS4,na.rm=T),digits=2), sd.mx = 0.2,rec.age=5,
#                       ar1=0,ar2=0,rps.m.cor = 0,rps.m.lag = 0)
# #r.strat <- data.frame(type = "lm",strat = "Linear", bp = "Model",mn.mx = signif(min(prod.dat$RPS5,na.rm=T),digits=2), sd.mx = 0.2,rec.age=5)
m.strat <- data.frame(type = "bp",strat = 'dist', bp = 1e4,mn.mx = 2*signif(mean(prod.dat$m,na.rm=T),digits=2), sd.mx = 0.1,ar1=0,ar2=signif(p.m.pacf$data$Freq[2],digits=2)) #
#m.strat <- data.frame(type = "bp",strat = 'dist', bp = 10000,mn.mx = signif(max(prod.dat$m,na.rm=T),digits=2), sd.mx = 0.1)
#m.strat <- data.frame(type = "lm",strat = "Linear", bp = "Model",mn.mx = signif(max(prod.dat$m,na.rm=T),digits=2), sd.mx = 0.1)
mod = "SEAM"
plot_url = "D:/Framework/SFA_25_26_2024/RefPts/Figures/Sab/R_75_FR_90/"
res_url = "D:/Framework/SFA_25_26_2024/RefPts/Results/Sab/R_75_FR_90/"


# An HCR model
hcr <- proj.mod(n_sim=500,n_y = 200,model=mod,plot_url = plot_url, run = 'no_model_error', res_url = res_url,save.results = T, mod.run = seam.select,
               g.mod =   list(type = g.strat$type,set.value = g.strat$set.value,bp.strategy = g.strat$strat,bp= g.strat$bp, 
                               mn.at.max = g.strat$mn.mx,sd.at.max = g.strat$sd.mx,ar1=g.strat$ar1,ar2=g.strat$ar2),
                rec.mod = list(type = r.strat$type,bp.strategy = r.strat$strat,bp= r.strat$bp, mn.at.max = r.strat$mn.mx,sd.at.max = r.strat$sd.mx,rec.age = r.strat$rec.age,
                                ar1=r.strat$ar1,ar2=r.strat$ar2,rps.m.cor = r.strat$rps.m.cor,rps.m.lag = r.strat$rps.m.lag),
                 m.mod =   list(type = m.strat$type,bp.strategy = m.strat$strat,bp= m.strat$bp, mn.at.max = m.strat$mn.mx,
                                sd.at.max = m.strat$sd.mx,ar1=m.strat$ar1,ar2=m.strat$ar2),
                 HCR.sim = list(TRP = hcr.strat$TRP,TRP.exp = hcr.strat$TRP.exp, USR = hcr.strat$USR, USR.exp = hcr.strat$USR.exp,
                                    LRP = hcr.strat$LRP, LRP.exp = hcr.strat$LRP.exp,exp.sd = hcr.strat$exp.sd))

summary(hcr$m)
summary(prod.dat$m)
summary(hcr$g)
summary(prod.dat$g)
summary(hcr$Rec)
summary(prod.dat$R)
summary(hcr$B)
summary(hcr$rps)
summary(prod.dat$RPS4)
plot(hcr$rps[,4,1])
ccf(hcr$mort[,2,1],hcr$rps[,2,1]) # High mort happening 5 years after the 'birth' of the high RPS'ers

```