---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Port sampling

```{r}
require(lubridate)
require(dplyr)
require(mgcv)
require(ggplot2)
require(ggridges)
require(viridis)


direct <- "Y:/Offshore/Assessment/"

# Bring in the port sampling data, which contains meat weights and meat counts for sampled fishing trips
load(paste0(direct,"Data/PortSampling/PS_data_reorg_4_analysis/Port_sampling_processed_data_2022.rData"))
# for port.sampling object, which becomes "bbn.dat" (even for sable)

# survey data 
load("C:/Users/keyserf/Documents/temp_data/testing_results_framework_75-90RSCS_newMWSH_GBb.Rdata")
# for mw[[bnk]] object containing all survey and hydration mw data. 

# plot destination
plotsGo <- "Y:/Offshore/Assessment/Framework/SFA_25_26_2024/DataInputs/Port_sampling/"

french <- F # set to T for french
if(french==T) {fr <- "_fr"}
if(french==F) {fr <- ""}

require(rosettafish)
funs <- c("https://raw.githubusercontent.com/freyakeyser/rosetta_shell/main/terms.csv")
# Now run through a quick loop to load each one, just be sure that your working directory is read/write!
for(fun in funs) 
{
  download.file(fun,destfile = basename(fun))
  rosetta_terms <- read.csv(paste0(getwd(),"/",basename(fun)), encoding = "UTF-8")
  file.remove(paste0(getwd(),"/",basename(fun)))
}
```


# overall summary bbn and sab
```{r}
# port.sampling$fished[1:10]
# port.sampling$ps.date[1:10]
# port.sampling$ps.fished[1:10]
# summary(port.sampling$ps.fished)
if(french==F) ylabel <- "Meat weight (g)"
if(french==T) ylabel <- "Masse de la chair (g)"

# png(paste0(plotsGo, "timeseries_mw", fr, ".png"), width=6.5, height=9, units = "in", res=420)
# ggplot() +
#   geom_point(data = port.sampling[port.sampling$bank %in% c("BBn", "Sab"),], aes(ps.fished, meat_weight)) +
#   geom_smooth(data = port.sampling[port.sampling$bank %in% c("BBn", "Sab"),], aes(ps.fished, meat_weight, group=bank)) +
#   facet_wrap(~bank, ncol=1) +
#   ylab(ylabel) +
#   scale_x_date(date_breaks="2 years") + 
#   xlab(NULL)+
#   theme_bw()
# dev.off()
# 
# png(paste0(plotsGo, "boxplot_mw", fr, ".png"), width=6.5, height=9, units = "in", res=420)
# ggplot() +
#   geom_boxplot(data = port.sampling[port.sampling$bank %in% c("BBn", "Sab"),], aes(year, meat_weight, group=year)) +
#   facet_wrap(~bank, ncol=1) +
#   theme_bw() +
#   ylab(ylabel) +
#   xlab(en2fr("Year", translate=french, custom_terms=rosetta_terms))
# dev.off()
# 
# png(paste0(plotsGo, "mw_2022", fr, ".png"), width=6.5, height=9, units = "in", res=420)
# ggplot() +
#   geom_point(data = port.sampling[port.sampling$bank %in% c("BBn", "Sab") & port.sampling$year==2022,], aes(ps.fished, meat_weight)) +
#   geom_smooth(data = port.sampling[port.sampling$bank %in% c("BBn", "Sab") & port.sampling$year==2022,], aes(ps.fished, meat_weight, group=bank)) +
#   facet_wrap(~bank, ncol=1) +
#   ylab(ylabel) +
#   scale_x_date(date_breaks="2 years") + 
#   xlab(NULL)+
#   theme_bw()
# dev.off()
# 
# png(paste0(plotsGo, "mw_monthly", fr, ".png"), width=6.5, height=9, units = "in", res=420)
# ggplot() +
#   geom_point(data = port.sampling[port.sampling$bank %in% c("BBn", "Sab"),], aes(month, meat_weight)) +
#   geom_smooth(data = port.sampling[port.sampling$bank %in% c("BBn", "Sab"),], aes(month, meat_weight, group=bank)) +
#   facet_wrap(~bank, ncol=1)  +
#   ylab(ylabel) +
#   xlab("Month")+
#   theme_bw() +
#   scale_x_continuous(breaks=1:12)
# dev.off()
# 
# png(paste0(plotsGo, "mw_monthly_box", fr, ".png"), width=6.5, height=9, units = "in", res=420)
# ggplot() +
#   geom_boxplot(data = port.sampling[port.sampling$bank %in% c("BBn", "Sab"),], aes(month, meat_weight, group=month)) +
#   facet_wrap(~bank, ncol=1) +
#   ylab(ylabel) +
#   xlab("Month")+
#   theme_bw() +
#   scale_x_continuous(breaks=1:12)
# dev.off()

port.sampling$ID <- 1:nrow(port.sampling)

medians <- port.sampling %>%
  group_by(bank, month, year) %>%
  dplyr::summarize(monthly_med=median(meat_weight),
            monthly_mean=mean(meat_weight),
            monthly_sd=sd(meat_weight),
            nsamples = length(ID))

medians2 <- port.sampling %>%
  group_by(bank, year) %>%
  dplyr::summarize(annual_med=median(meat_weight),
                   nsamples_yr = length(ID))

medians <- left_join(medians, medians2)

medians$monthyr <- ymd(paste0(medians$year, "-", medians$month, "-01"))
medians2$monthyr <- ymd(paste0(medians2$year, "-01-01"))
medians2$ndaysyr <- as.numeric(strftime(ymd(paste0(medians2$year, "12-31")), "%j"))
medians2$xend <- ymd(medians2$monthyr) + years(1)

if(french==F) ylabel <- "Meat weight (g)"
if(french==T) ylabel <- "Masse de la chair (g)"

medians2$bank <- gsub(x=medians2$bank, pattern="BBn", replacement = "26A-BBn")
medians2$bank <- gsub(x=medians2$bank, pattern="BBs", replacement = "26B-BBs")
medians2$bank <- gsub(x=medians2$bank, pattern="Ger", replacement = "26C-Ger")
medians2$bank <- gsub(x=medians2$bank, pattern="Sab", replacement = "25A-Sab")
medians2$bank <- gsub(x=medians2$bank, pattern="Mid", replacement = "25A-Mid")
medians2$bank <- gsub(x=medians2$bank, pattern="Ban", replacement = "25B-Ban")
medians2$bank <- gsub(x=medians2$bank, pattern="GBb", replacement = "27B-GBb")
medians2$sfa <- substr(x = medians2$bank, start = 1, stop = 2)

medians$bank <- gsub(x=medians$bank, pattern="BBn", replacement = "26A-BBn")
medians$bank <- gsub(x=medians$bank, pattern="BBs", replacement = "26B-BBs")
medians$bank <- gsub(x=medians$bank, pattern="Ger", replacement = "26C-Ger")
medians$bank <- gsub(x=medians$bank, pattern="Sab", replacement = "25A-Sab")
medians$bank <- gsub(x=medians$bank, pattern="Mid", replacement = "25A-Mid")
medians$bank <- gsub(x=medians$bank, pattern="Ban", replacement = "25B-Ban")
medians$bank <- gsub(x=medians$bank, pattern="GBb", replacement = "27B-GBb")
medians$sfa <- substr(x = medians$bank, start = 1, stop = 2)

medians$monthnum <- as.numeric(medians$monthyr - min(medians$monthyr))
medians2$monthnum <- as.numeric(medians2$monthyr - min(medians$monthyr))
labs <- unique(medians2[,c("monthnum", "monthyr")])
labs$monthnum <- -labs$monthnum


sfa <- c(25, 26, 27)
for(i in sfa){
  margin <- margin(0,0,0,0, "cm")
  if(i %in% c(27)) margin <- margin(0,3,0,3, "cm")
  if(i ==26) yn=-20
  if(i == 25) yn=-60
  if(i==27) yn=-10
  png(paste0(plotsGo, "medians_long_vert", fr, "_", i, ".png"), width=6, height=7, units = "in", res=420)
  print(
    ggplot() +
      # geom_bar(data=medians2[medians2$bank %in% c("BBn", "Sab"),], aes(monthyr, annual_med, width=ndaysyr), stat="identity", fill="grey", just = 0) +
      geom_segment(data=medians2[medians2$sfa==i,],mapping=aes(x=-monthnum, xend=-monthnum-365, y=annual_med, yend=annual_med), colour="blue", linewidth=1) +
      geom_errorbar(data=medians[medians$sfa==i,], aes(x=-monthnum, ymin=monthly_med-(1.96*monthly_sd), ymax=monthly_med+(1.96*monthly_sd)), width=0)+
      geom_point(data=medians[medians$sfa==i,], aes(-monthnum, monthly_med)) +
      geom_text(data=medians2[medians2$sfa==i,], aes(-monthnum - (365/2), yn, label=nsamples_yr), vjust=0.5, hjust=0, colour="blue")+
      #geom_line(data=medians[medians$bank %in% c("BBn", "Sab"),], aes(monthyr, annual_med), group=1, size=1) +
      facet_wrap(~bank, ncol=3) +
      ylab(ylabel) +
      xlab("Date")+
      theme_bw() +
      scale_x_continuous(breaks=labs$monthnum, labels=strftime(labs$monthyr, "%m/%Y"))+#, date_labels = "%m/%Y") + 
      #scale_y_continuous(expand=c(0.25,10)) +
      coord_flip() +
      theme(plot.margin=margin)
  )
  dev.off()
}

# anomaly (seasonal)

medians$anom <- medians$annual_med - medians$monthly_med
months <- medians %>%
  dplyr::group_by(bank, month) %>%
  dplyr::summarize(nsamples = sum(nsamples),
                   bottom = boxplot(anom)$stats[1])

# if(french==F) ylabel <- "Meat weight anomaly (g)"
# if(french==T) ylabel <- "Anomalie en masse de la chair (g)"
# png(paste0(plotsGo, "medians_anom", fr, ".png"), width=6.5, height=8, units = "in", res=420)
# ggplot() +
#   geom_hline(data=medians[medians$bank %in% c("Sab", "BBn"),], aes(yintercept=0), linetype="dashed")+
#   geom_boxplot(data=medians[medians$bank %in% c("Sab", "BBn"),], aes(month, anom, group=month)) +
#   geom_text(data=months[months$bank %in% c("Sab", "BBn"),], aes(month, bottom, label=nsamples), vjust=1.5)+
#   facet_wrap(~bank, ncol=1, scales="free_y") +
#   ylab(ylabel) +
#   xlab(en2fr("Month", translate=french, custom_terms=rosetta_terms)) +
#   theme_bw() +
#   scale_x_continuous(breaks=1:12) +
#   scale_y_continuous(expand=c(0,3))
# dev.off()

port.sampling$sfa <- NA
port.sampling$sfa[port.sampling$bank %in% c("BBn", "BBs", "Ger")] <- 26
port.sampling$sfa[port.sampling$bank %in% c("Sab", "Mid", "Ban")] <- 25
port.sampling$sfa[port.sampling$bank %in% "GBb"] <- 27

ps_tab <- port.sampling %>% 
  dplyr::filter(!bank %in% c("GBa", "SPB")) %>%
  dplyr::group_by(sfa,bank) %>%
  dplyr::summarize(total=length(unique(ID)),
            years=length(unique(year)),
            recent=max(year),
            months = length(unique(month)),
            ltm_mw = round(median(meat_weight),2),
            sd_mw = round(sd(meat_weight),2),
            min_mw = round(min(meat_weight),2), 
            max_mw = round(max(meat_weight),2))
ps_tab$main<-NA
ps_tab$main[ps_tab$bank %in% c("Sab", "BBn")] <- "*"

#1:12 %in% unique(port.sampling[port.sampling$bank=="Sab",]$month)
# Sable is missing data from Jan and Feb
write.csv(ps_tab, paste0(plotsGo, "/ps_tab.csv"))

```

# Single bank results
```{r}
bank <- "BBn"

bbn.dat <- port.sampling[port.sampling$bank == bank,]

# For the models to come let's center on the day we believe the ASM's arrive on the scence (May 24, 2010 according to Ginette)
# The day here represents 100 days. FK changed ps.date to ps.fished
bbn.dat$mod.day <- as.numeric(bbn.dat$ps.fished - as.Date(min(bbn.dat$ps.fished)))/100

####################################
### now we need a MW-SH relationship to estimate the SH of the landings

# # Add an year month combo column to port.sampling...
# port.sampling$year_month <- ymd(paste(year(port.sampling$ps.fished),month(port.sampling$ps.fished),15,sep="-"))
# mw.by.month <- aggregate(meat_weight ~ year_month + year,port.sampling,mean)
# names(mw.by.month) <- c("date","year","mw")
# 
# #ggplot(mw.by.month,aes(x= date,mw)) + geom_point() + geom_line()
# 
# ps.mw.sh <- merge(mw.by.month,SH.target,by =c("year"))
# 
# ps.mw.sh$mc <- 500/ps.mw.sh$mw
# # Condition here is kinda interesting as it standardizes the meat weight between the fleets, i.e. what is the
# # meat weight the different fleets are picking up for a 100 mm scallop.  In theroy I wouldn't expect this to be any different...
# # What the questions around condition are:
# # 1:  How does condition vary throughout the year, when does condition appear to peak.
# # 2:  For a 100 mm scallop, is there any difference between the fleets in terms of the size of the meat they capture.
# # I'm not sure if my logic holds up here, but I think it does, hinges on the assumption that the targeted SH doesn't vary
# # significantly throughout the year
# ps.mw.sh$cond <- ps.mw.sh$mw/(ps.mw.sh$sh/100)^3
# ps.mw.sh$month <- as.factor(month(ps.mw.sh$date))
# 
# ggplot() +
#   geom_point(data = ps.mw.sh, aes(month, cond)) +
#   geom_line(data = ps.mw.sh, aes(month, cond, group=1)) +
#   facet_wrap(~year)
# 
# ggplot() +
#   geom_boxplot(data = ps.mw.sh, aes(month, cond, group=month))
# 
# ggplot() +
#   geom_boxplot(data = ps.mw.sh, aes(month, mw, group=month)) 
# 
# ggplot() +
#   geom_boxplot(data = ps.mw.sh, aes(month, mc, group=month)) 

# OK, so I want to see what propotion of the port sampling data might have a SH of < 95 mm, based on the MW-SH data.
# This is similar to above, but I'm going to have to use the raw data, so this is gonna be slow....

#if(bank=="BBn", "BBs", "Ger", "GBb") 
years <- 2006:2022
#if(bank=="Sab") years <-  c(2006:2014, 2016:2019,2021:2022)
may.mws <- NULL
bbn.dat$sh <- NA
all.may <- data.frame(a = rep(NA,length(years)), year = years)

pred.dates <- ymd(paste0(sort(rep(2006:2022,12)),"-",rep(1:12,12),"-",rep(0,144),rep(1,144)))
# For the models to come let's center on the day we believe the ASM's arrive on the scence (May 24, 2010 according to Ginette)
# This is needed to line up with mod.pred.day... I know this lumps the 31st with the day furthest away from the 31st rather than the next month
# But the idea here is everything in month x is treated the same.
bbn.dat$year_month <- date(paste0(year(bbn.dat$date),"-",bbn.dat$month,'-01'))
bbn.dat$mod.day <- as.numeric(bbn.dat$year_month - as.Date("2010-05-24"))/100
bbn.dat$year <- year(bbn.dat$date)

bbn.dat$surv.year <- bbn.dat$year
#bbn.dat$surv.year[bbn.dat$month %in% 1:5 & bbn.dat$sfa %in% 25:26 ] <- bbn.dat$year[bbn.dat$month %in% 1:5 & bbn.dat$sfa %in% 25:26]-1
#bbn.dat$surv.year[bbn.dat$month %in% 1:8 & bbn.dat$sfa %in% 27] <- bbn.dat$year[bbn.dat$month %in% 1:8 & bbn.dat$sfa %in% 27]-1

years <- unique(bbn.dat$surv.year)

for(i in 1:length(years))
{
  may.mws[[as.character(years[i])]] <-  na.omit(mw[[bank]][mw[[bank]]$surv.year == years[i],]) # get BBn and chuck the na's
  may.mws[[as.character(years[i])]]$sh_3 <- (may.mws[[as.character(years[i])]]$sh/100)^3 # cube the SH's
  may.mws[[as.character(years[i])]]$sh <- (may.mws[[as.character(years[i])]]$sh/100) # sh in decimeters
  # Run the model and save the results
  # all.may$a[i] <-  lme(fixed = wmw ~ sh_3 -1, data = may.mws[[as.character(years[i])]], random = ~ sh_3 -1 | tow, method="REML")$coefficients$fixed
  
  r.tows <- NULL
  f.mws <- NULL
  fix.slope <- cf.data[[bank]]$CF.fit$mw.sh.coef[cf.data[[bank]]$CF.fit$mw.sh.coef$year==years[i],]$fix.slope[1]
  fix.int <- cf.data[[bank]]$CF.fit$mw.sh.coef[cf.data[[bank]]$CF.fit$mw.sh.coef$year==years[i],]$fix.int[1]
  bbn.dat$sh[bbn.dat$surv.year == years[i]] <- ((bbn.dat$meat_weight[bbn.dat$surv.year == years[i]]/exp(fix.int))^ (1/fix.slope))*100
  # What is the shell height being targeted in may
  # old model
  # bbn.dat$sh[bbn.dat$year == years[i]] <- 100*(bbn.dat$meat_weight[bbn.dat$year == years[i]]/all.may$a[i])^(1/3)
}

sh.plt <- ggplot(bbn.dat,aes(date,sh)) + 
  geom_point(alpha = 0.05,size=0.2) +
  #geom_smooth(method = 'gam')+
  geom_hline(yintercept = 95, linetype = 'dashed',linewidth=1.5,color="grey") +
  theme(text = element_text(size=16)) + 
  theme_bw() + 
  scale_x_date(date_breaks="2 years") + 
  scale_y_continuous(breaks = seq(0,200,by=5)) +
  xlab("") + 
  ylab(paste0(en2fr("Shell height", translate=french, custom_terms=rosetta_terms), " (mm)")) 
#png(paste0(plotsGo, bank, "/timeseries_sh", fr, ".png"), width=6.5, height=4, units = "in", res=420)
print(sh.plt)
#dev.off()

# ggplot() + 
#   geom_density_ridges_gradient(data=bbn.dat, aes(x=sh, y=as.factor(year), group=year), 
#                                scale=0.7, #, # you may wish to adjust this
#                                bandwidth=5 # you may wish to adjust this
#                                ) +

if(length(unique(bbn.dat$surv.year))<6) scale_fac = 0.55
if(length(unique(bbn.dat$surv.year))>5) scale_fac = 0.9

png(paste0(plotsGo, bank, "/shf_ps", fr, "_new.png"), width=6.5, height=8, units = "in", res=420)
ggplot() + 
  geom_density_ridges(data=bbn.dat, aes(x = sh, y = as.factor(surv.year), height = stat(density)),
                      stat = "binline", bins = 40, scale = scale_fac, draw_baseline = F) +
  theme_bw() +
  ylab(en2fr("Year",translate=french, custom_terms=rosetta_terms)) + 
  xlab(paste0(en2fr("Shell height", translate=french, custom_terms=rosetta_terms), " (mm)")) +
  scale_x_continuous(limits=c(50,200), breaks=seq(50,200,10)) +
  scale_y_discrete(expand=c(0,0.9), limits=rev)
dev.off()  


# combine with survey SHF
shf <- SHF.summary[[bank]]
names(shf)[1] <- "years"
if(bank %in% c("Sab", "BBn", "BBs", "GBb")) {
  shf <- shf %>% tidyr::pivot_longer(cols = starts_with("V"))
  shf$name <- gsub(x=shf$name, pattern="V", replacement="")
}
if(bank %in% c("Mid", "Ban", "Ger")) shf <- shf %>% tidyr::pivot_longer(cols = as.character(seq(5,200,5)))

if(!any(shf$name==200)) shf$name <- (as.numeric(shf$name)-1)*5
if(!any(shf$name==0)) shf$name <- as.numeric(shf$name)-5
# bins go from 0-5mm to 195-200mm, labelled as 0 and 195 respectively

shf <- shf[!is.na(shf$years),]
shf <- shf[shf$name>65,] # keep bins 70-75 mm and up (GREATER than bin 65, which is 65-70)

years <- shf %>%
  dplyr::group_by(years) %>%
  dplyr::summarize(total=sum(value))

shf <- left_join(shf, years)
shf$density <- shf$value/shf$total
shf$name <- as.numeric(shf$name)

# bins <- data.frame(shf=rep(seq(65,199.9,0.1), length(unique(shf$years))), 
#                    name=rep(rep(seq(70,200,5), each=50), length(unique(shf$years))), 
#                    years=rep(unique(shf$years), each=1350))

# need these wonky bins to get the "steps" for the plot
bins <- data.frame(shf=seq(70,204.9,0.1),
                   name=rep(seq(70,200,5), each=50))
yearsbins <- data.frame(years=rep(unique(shf$years), each=length(seq(70,200,5))), 
                        name=rep(seq(70,200,5), length(unique(shf$years))))
bins <- full_join(bins, yearsbins, relationship="many-to-many")

shf <- full_join(shf, bins)

# get the range of years with data, blanks in missing years
shf <- left_join(data.frame(years = min(shf$years, na.rm=T):max(shf$years, na.rm=T)), shf)
shf$bank <- bank

# do the same for the PS data
shfps <- bbn.dat[!is.na(bbn.dat$sh),]
shfps <- shfps[shfps$sh>70 | shfps$sh==70,] # keep everything greater than or equal to 70 
shfps <- shfps[shfps$month %in% c(4:8),]

shfps.yr <- shfps %>%
  dplyr::group_by(surv.year) %>%
  dplyr::summarize(total=n())

shfps <- shfps %>%
  dplyr::mutate(bin = cut(sh, breaks=seq(70,210,5), right=F)) %>% # gotta go above 200 since these are estimates (not 5mm bins)
  dplyr::group_by(surv.year, bin) %>%
  dplyr::summarize(value=n())

shfps <- left_join(shfps, shfps.yr)
shfps$density <- shfps$value/shfps$total
# tidy up the brackets
bins <- unlist(strsplit(x = as.character(shfps$bin), split=","))
bins <- bins[grep(x=bins,pattern="[", fixed=T)]
bins <- gsub(x=bins, pattern="[", replacement="", fixed=T)
shfps$name <- bins # named for lower bound
#stringr::str_detect(shfps$bin, pattern = shfps$name) # just a check

# bins <- data.frame(name=as.character(rep(seq(5,210,5), length(unique(shfps$year)))), year=rep(unique(shfps$year), each=42))
# bins <- data.frame(shf=rep(seq(65,209.9,0.1), length(unique(shfps$surv.year))), name=rep(rep(seq(70,210,5), each=50), length(unique(shfps$surv.year))), surv.year=rep(unique(shfps$surv.year), each=1450))
bins <- data.frame(shf=seq(70,214.9,0.1),
                   name=rep(seq(70,210,5), each=50))
yearsbins <- data.frame(years=rep(unique(shfps$surv.year), each=length(seq(70,210,5))), 
                        name=rep(seq(70,210,5), length(unique(shfps$surv.year))))
bins <- full_join(bins, yearsbins, relationship="many-to-many")

shfps$name <- as.numeric(shfps$name)
names(shfps)[names(shfps)=="surv.year"] <- "years"
shfps <- full_join(shfps, bins) # has NAs

shfps <- left_join(data.frame(years = min(shfps$years, na.rm=T):max(shfps$years, na.rm=T)), shfps) # should not be removing NAs for these years
shfps$bank <- bank

shfps <- dplyr::select(shfps, bank, years, name, shf, density)
shfps$density[is.na(shfps$density)] <- 0
names(shfps) <- c("bank", "years", "name", "shf", "density_ps")
shfps$name <- as.numeric(shfps$name)

# getting ready to join survey with fishery
shf <- unique(dplyr::select(shf, bank, years, name, shf, density))

# years with port sampling data
#shfps.yr$surv.year # this is NOT survey year any more, just labelled as such

shf <- full_join(shf, shfps)
shf <- shf[shf$years %in% shfps.yr$surv.year,]
names(shf)[names(shf)=="name"] <- "bin"
shf <- shf %>% tidyr::pivot_longer(cols = starts_with("d"))

height <- length(unique(shf$years)) * 2
if(height>8) height <- 8
if(height<4) height <- 4

if(bank=="Ger") shf <- shf[shf$years>2007,]

png(paste0(plotsGo, bank, "/shf_selectivity", fr, ".png"), width=6, height=height, units = "in", res=420)
ggplot() + geom_line(data=shf, aes(shf, value, colour=name), linewidth=1) + 
  facet_wrap(~years, ncol=1, strip.position="right") +
  theme_bw() +
  scale_colour_manual(name=NULL, labels=c("Survey", "Fishery"), values=c("blue", "black")) +
  xlab("Shell height (5 mm bin)") +
  ylab("Proportion of scallops >65 mm") +
  scale_y_continuous(n.breaks = 3)
dev.off()

# HERE IS THE MAIN ANALYSIS FOR the BBn Res doc, shows proportion below certain sizes
n.bl.100 <- bbn.dat %>% dplyr::group_by(year) %>% dplyr::filter(sh < 100) %>% dplyr::summarise(n = length(sh))
n.all.bbn <- bbn.dat %>% dplyr::group_by(year) %>% dplyr::summarise(tot = length(sh))

prop.bl.100 <- left_join(n.bl.100,n.all.bbn,'year')
prop.bl.100$prop <- prop.bl.100$n / prop.bl.100$tot

ggplot(data = prop.bl.100,aes(x=year,y=prop)) + 
  geom_point() + ylab("Proportion of meats below 100 mm") +
  #theme(text = element_text(size=22)) + 
  scale_x_continuous(breaks = seq(2000,2030,by=2))


n.bl.95 <- bbn.dat %>% dplyr::group_by(year) %>% dplyr::filter(sh < 95) %>% dplyr::summarise(n = length(sh))
prop.bl.95 <- left_join(n.bl.95,n.all.bbn,'year')
prop.bl.95$prop <- prop.bl.95$n / prop.bl.95$tot

ggplot(data = prop.bl.95,aes(x=year,y=prop)) + 
  geom_point() + 
  ylab("Proportion of meats below 95 mm") +
  # theme(text = element_text(size=22)) + 
  scale_x_continuous(breaks = seq(2000,2030,by=2))

# Based on Ageing info, we think 75-90 mm is the best option, that would be ≈ 3-4 year olds.
n.bl.90 <- bbn.dat %>% dplyr::group_by(year) %>% dplyr::filter(sh < 90) %>% dplyr::summarise(n = length(sh))
prop.bl.90 <- left_join(n.bl.90,n.all.bbn,'year')
prop.bl.90$prop <- prop.bl.90$n / prop.bl.90$tot

# This is basically under 1%, which I think will be fine.
ggplot(data = prop.bl.90,aes(x=year,y=prop)) + 
  geom_point() + 
  ylab("Proportion of meats below 90 mm") +
  #theme(text = element_text(size=22)) + 
  scale_x_continuous(breaks = seq(2000,2030,by=2))


n.bl.85 <- bbn.dat %>% dplyr::group_by(year,.drop=F) %>% dplyr::filter(sh < 85) %>% dplyr::summarise(n = length(sh))
prop.bl.85 <- left_join(n.bl.85,n.all.bbn,'year')
prop.bl.85$prop <- prop.bl.85$n / prop.bl.85$tot

# So there is basically 0 catch coming from < 85 mm, well under 1%
ggplot(data = prop.bl.85,aes(x=year,y=prop)) + geom_point() + ylab("Proportion of meats below 90 mm") +
  theme(text = element_text(size=22)) + scale_x_continuous(breaks = seq(2000,2030,by=2))


prop.bl.100$lim <- "<100"
prop.bl.95$lim <- "<95"
prop.bl.90$lim <- "<90"
prop.bl.85$lim <- "<85"

overall <- full_join(full_join(full_join(prop.bl.100, prop.bl.95), prop.bl.90), prop.bl.85)
overall$lim <- factor(overall$lim, levels=c("<85", "<90", "<95", "<100"))

# for text:
yearround <- overall %>% group_by(lim) %>% summarize(median(prop))



if(french==F) {
  ylabel <- "Proportion of meats"
}

if(french==T) {
  ylabel <- "Proportion des chairs"
}


png(paste0(plotsGo, bank, "/proportion_boxplot", fr, "_new.png"), width=6.5, height=4, units = "in", res=420)
ggplot() + 
  geom_boxplot(data=overall, aes(lim, prop, group=lim))+
  theme_bw() +
  ylab(ylabel) +
  xlab(paste0(en2fr("Shell height", translate=french, custom_terms=rosetta_terms), " (mm)"))
dev.off()


# Just look at spring-summer, going with April-August as in theory condition should be fairly stable during this period.
# Based on Ageing info, we think 75-90 mm is the best option, that would be ≈ 3-4 year olds.
sel.months <- 4:8
n.bl.90.ss <- bbn.dat %>% dplyr::group_by(year) %>% dplyr::filter(sh < 90 & month %in% sel.months) %>% dplyr::summarise(n = length(sh))
n.all.bbn.ss <-  bbn.dat %>% dplyr::group_by(year) %>% dplyr::filter(month %in% sel.months) %>% dplyr::summarise(tot = length(sh))
prop.bl.90.ss <- left_join(n.bl.90.ss,n.all.bbn.ss,'year')
prop.bl.90.ss$prop <- prop.bl.90.ss$n / prop.bl.90.ss$tot

n.bl.95.ss <- bbn.dat %>% dplyr::group_by(year) %>% dplyr::filter(sh < 95 & month %in% sel.months) %>% dplyr::summarise(n = length(sh))
n.all.bbn.ss <-  bbn.dat %>% dplyr::group_by(year) %>% dplyr::filter(month %in% sel.months) %>% dplyr::summarise(tot = length(sh))
prop.bl.95.ss <- left_join(n.bl.95.ss,n.all.bbn.ss,'year')
prop.bl.95.ss$prop <- prop.bl.95.ss$n / prop.bl.95.ss$tot

n.bl.100.ss <- bbn.dat %>% dplyr::group_by(year) %>% dplyr::filter(sh < 100 & month %in% sel.months) %>% dplyr::summarise(n = length(sh))
n.all.bbn.ss <-  bbn.dat %>% dplyr::group_by(year) %>% dplyr::filter(month %in% sel.months) %>% dplyr::summarise(tot = length(sh))
prop.bl.100.ss <- left_join(n.bl.100.ss,n.all.bbn.ss,'year')
prop.bl.100.ss$prop <- prop.bl.100.ss$n / prop.bl.100.ss$tot

n.bl.85.ss <- bbn.dat %>% dplyr::group_by(year) %>% dplyr::filter(sh < 85 & month %in% sel.months) %>% dplyr::summarise(n = length(sh))
n.all.bbn.ss <-  bbn.dat %>% dplyr::group_by(year) %>% dplyr::filter(month %in% sel.months) %>% dplyr::summarise(tot = length(sh))
prop.bl.85.ss <- left_join(n.bl.85.ss,n.all.bbn.ss,'year')
prop.bl.85.ss$prop <- prop.bl.85.ss$n / prop.bl.85.ss$tot


prop.bl.100.ss$lim <- "<100"
prop.bl.95.ss$lim <- "<95"
prop.bl.90.ss$lim <- "<90"
prop.bl.85.ss$lim <- "<85"

overall <- full_join(full_join(full_join(prop.bl.100.ss, prop.bl.95.ss), prop.bl.90.ss), prop.bl.85.ss)
overall$lim <- factor(overall$lim, levels=c("<85", "<90", "<95", "<100"))


# This is basically under 1%, which I think will be fine.
ggplot(data = prop.bl.90.ss,aes(x=year,y=prop)) + geom_point() + ylab("Proportion of meats below 90 mm") +
  theme(text = element_text(size=22)) + scale_x_continuous(breaks = seq(2000,2030,by=2))

png(paste0(plotsGo, bank, "/proportion_boxplot_ss", fr, "_new.png"), width=6.5, height=4, units = "in", res=420)
ggplot() + 
  geom_boxplot(data=overall, aes(lim, prop, group=lim))+
  theme_bw() +
  ylab(ylabel) +
  xlab(paste0(en2fr("Shell height", translate=french, custom_terms=rosetta_terms), " (mm)"))
dev.off()

# for text:
ss <- overall %>% group_by(lim) %>% summarize(median(prop))
yearround$type <- "yearround"
ss$type <- "ss"
overall <- full_join(yearround, ss)
write.csv(overall, paste0(plotsGo, bank, "/boxplot_vals.csv"))

# Based on the ageing work, if we go with 90 mm as our end of recruitment bin, the recruits should be 75-90 mm in size.
```