# Introduction

Scallop fishery description. Introduce SFAs and management scheme. The last full assessment for the Offshore Scallop fishery occurred in 2013, and focused on Georges Bank 'a' and Browns Bank north, which are part of SFA 27 and 26, respectively. Annual updates for these two stocks have occurred since***. However, the offshore scallop fishery consists of 9 management units in total. SFA 26 also includes Browns Bank South and German Bank, SFA 27 includes Georges Bank 'b', and SFA 25, known as the eastern scotian shelf, includes management units 25 (Sable and Middle Bank), and 25b (Banquereau Bank). An annual review of fishery and survey data summaries for all 9 stocks occurs as part of the OSAC process, however, the methodology underlying the current fishery and survey summaries has not been peer-reviewed. Furthermore, stock status information has not been published since 2001 for the Eastern Scotian Shelf stocks (Sable and Middle Banks) and 1997 for German Bank; Browns Bank South and Banquereau Bank have not been published before.

## Species biology


## Framework objectives

The objectives of this framework are:
- To describe the fishery, survey, and biological data informing the assessment of SFAs 25 and 26 (Part 1, this document)
- To evaluate the analysis methodology used to summarize the above data for SFAs 25 and 26 (Part 2, separate document)
- To propose reference points for SFAs 25 and 26 (Part 2, separate document)

This Data Inputs review document will:
- Summarize and review the sampling protocols used during the surveys of SFA 25 and 26 over time
- Review the statistical design(s) of the surveys of SFA 25 and 26 over time
- Review the fishery data collected for trips occurring in SFA 25 and 26 (process, volume of data, quality and validation)
- Review the methods used to summarize survey and fishery data into Science advice
- Present the summarized survey and fishery data for each management unit

notes:
tow-by-tow summary. station locations over time?
clappers only for sable and north
ts figures for all banks (fishery, abund, biomass, cond)
survey map for all banks... example for german

# Fishery

- Fishery independent data
- Logbooks

## Fishery history

- Fleet dynamics  
- Management  

## Fishery data

- Footprint  
- CPUE  
- Port sampling  



