---
output:
  word_document: default
  html_document: default
editor_options: 
  chunk_output_type: console
---


```{r}
banks <- c("Sab", "Mid", "Ban", "BBn", "BBs", "Ger", "GBb")
ps.prop <- NULL
for(i in banks){
  ps.props <- read.csv(paste0("Y:/Offshore/Assessment/Framework/SFA_25_26_2024/DataInputs/Port_sampling/", i, "/boxplot_vals.csv"))
  ps.props$bank <- i
  ps.props$median.prop. <- round(ps.props$median.prop., 3)
  ps.prop <- rbind(ps.prop, ps.props)
}

# ps.prop <- pivot_wider(ps.prop, id_cols = c(bank, lim), names_from = type, values_from=median.prop.) %>%
#   dplyr::select(-lim) %>%
#   dplyr::rename(Stock = bank,
#                 `Year-round` = yearround,
#                 `Apr--Aug` = ss)
# ps.prop$Stock[ps.prop$Stock=="Sab"] <- "25A-Sab"
# ps.prop$Stock[ps.prop$Stock=="Mid"] <- "25A-Mid"
# ps.prop$Stock[ps.prop$Stock=="Ban"] <- "25B"
# ps.prop$Stock[ps.prop$Stock=="BBn"] <- "26A"
# ps.prop$Stock[ps.prop$Stock=="BBs"] <- "26B"
# ps.prop$Stock[ps.prop$Stock=="Ger"] <- "26C"
# ps.prop$Stock[ps.prop$Stock=="GBb"] <- "27B"
# ps.prop$`Apr--Aug`[is.na(ps.prop$`Apr--Aug`)] <- 0

```

# Introduction

The Maritimes Region Offshore Scallop fishery is managed using Scallop Fishing Areas (SFAs, Figure \@ref(fig:map)). Information on scallop population dynamics within seven of the SFA management units is provided annually by Fisheries and Oceans Canada (DFO) Science in the Maritimes Region during meetings of the Offshore Scallop Advisory Committee (OSAC). Stock assessment science advice is provided annually through the Canadian Science Advisory Secretariat (CSAS) using the science advice frameworks established in 2009 [@jonsen_georges_2009] and 2013 [@dfo_assessment_2013; @hubley_georges_2014] for SFA 27A Georges Bank 'a', and in 2011 for SFA 26A Browns Bank North [@hubley_browns_2011]. Stock assessment advice through CSAS was last conducted for SFA 25A Eastern Scotian Shelf (Sable, Western, and Middle Banks) in 2001 [@dfo_eastern_2001] and for SFA 26C German Bank in 1997 [@dfo_german_1997]. This document represents the first time that information on SFA 25B Banquereau Bank, SFA 26B Browns Bank South, and SFA 27B Georges Bank ‘b’ has been presented.

This Data Inputs document is the first of three research documents that form a broader assessment framework for SFAs 25, 26 and 27B Georges Bank 'b'. Throughout this document, the nomenclature in Table \@ref(tab:ps-tab) (e.g. SFA 25A-Sab for the portion of SFA 25 known as Sable Bank) will be used to refer to management units and survey areas, as these are smaller areas within the SFAs. Throughout this document scallop are grouped and discussed in relation to three size classes (defined by shell height); fully-recruited scallop are the size landed by the commercial fishery, recruit scallop as defined as scallop that will reach fully-recruited size in one year, and pre-recruit scallop are defined as being smaller than recruit size. 

The objectives of this document are to:

-	describe the fishery and the methods used to collect fishery-dependent data (e.g. logbook and port sampling data) from trips occurring in SFA 25, 26, and 27B (process, volume of data, quality and validation),   
-	describe the DFO Maritimes Offshore Scallop Survey and the methods used to collect fishery-independent data (e.g. survey design and sampling protocols) for stocks in SFA 25, 26, and 27B,    
-	update the methods for modelling the relationships between meat weight and shell height for stocks in SFA 25, 26, and 27B,   
-	develop shell height-at-age relationships from new age determination data from SFA 25A-Sab and SFA 26A,  
-	evaluate the shell heights of the three size classes of scallop (pre-recruit, recruit, and fully-recruited) for SFA 25A-Sab and SFA 26A, and,  
-	present various indicators of stock dynamics. 


## Species biology

The biology of the sea scallop (_Placopecten magellanicus_) is summarized in @jonsen_georges_2009, @naidu_fisheries_2006, and @shumway_fisheries_2016. Paraphrasing these summaries, sea scallops are bivalve molluscs that range from North Carolina, US to the Gulf of St. Lawrence, Canada. They are broadcast spawners, with pelagic larvae settling on the seafloor at depths of 18–110m after 1–2 months. While largely sessile, juveniles and adults may be able to swim short distances, adjust their orientation or position in the sediment, or attach to substrate with byssus threads. Growth rates are dependent on environmental conditions such as depth and temperature, likely due to the availability of microbial planktonic food sources. Sexual maturation typically occurs within 3–5 years of age (with shell heights of approximately 75–100 mm). Spawning typically occurs in the fall, though there is some evidence of spring spawning in some populations.

Recent studies have contributed new information to the biological understanding of sea scallop. Scallop growth and condition can depend on depth, location, fishing pressure, and season [@hart_estimating_2009; @hennen_shell_2012; @sarro_spatial_2009]. New relationships have been found between the environment and scallop physiology and distribution; growth may be reduced with increasing levels of carbon dioxide [@pousse_juvenile_2023], condition may be correlated with sea surface temperature [@liu_using_2021], and fall scallop biomass may increase under climate change [@friedland_trends_2023]. An in situ study of scallop swimming ability observed that scallops up to 100 mm in shell height swim and swimming duration and distance increased with shell height [@mason_situ_2014]. Adding evidence to previous studies, scallops on Georges Bank exhibited semiannual spawning patterns, with a spring spawn observed in several years in addition to the primary fall spawn [@thompson_identifying_2014]. Natural mortality has been found to be density dependent [@hart_estimating_2022] and the occurrence of grey meats (grey adductor muscle) may be due to an apicomplexan parasite [@inglis_gray_2016] coupled with other factors that reduce scallop condition [@siemann_investigating_2019]. 


# Fishery

The Maritimes Region Offshore Scallop fishery is described in an [Integrated Fisheries Management Plan](https://www.dfo-mpo.gc.ca/fisheries-peches/ifmp-gmp/scallop-petoncle/2018/index-eng.html) [@dfo_integrated_2024-1] that is updated as needed by DFO Fisheries and Aquaculture Management. To summarize, there are currently six license-holding companies and eight active vessels. The fishery is managed using a total allowable catch (TAC) with Enterprise Allocations for each company based on a percent share of the TAC. In addition to following regulatory and license conditions related to gear, vessel size, and SFA meat count limits (the number of scallops in a 500 gram sample), each fishing trip must complete and submit a fishing logbook (consisting of a monitoring document and fishing logs) and participate in dockside monitoring and port sampling upon landing. The data collected are used for both fisheries management and stock assessment purposes.

TACs have varied over time, but are consistently highest in SFA 27A Georges Bank 'a' (not included here), followed by SFA 26A and 27B (Figure \@ref(fig:hist)). TACs were not used on the Eastern Scotian Shelf until 1995, however fishing was allowed. SFA 25A and 25B were treated as one management unit and SFA 26A and SFA 26B were treated as one management unit until 1998. Prior to 1998, fishing in SFA 27B was combined with fishing in SFA 27A. Fishing seasons run from January 1 to December 31 for all SFAs, except SFA 26C which runs from June 1 to November 15 to avoid gear conflicts with the lobster fishery [@dfo_integrated_2024-1]. Each SFA corresponds to a bathymetric bank, except SFA 25A, which represents the Eastern Scotian Shelf and contains both Sable and Middle Banks. Western Bank is also in SFA 25A and was fished for many years until the Western/Emerald Bank Conservation Area (WEBCA) was established in 2017, which closed it to scallop fishing. Middle Bank (SFA 25A-Mid) is shown separately from Sable Bank (SFA 25A-Sab) in fishery figures presented in this document as the two banks are surveyed separately.

## Fishery history

Historically, Georges Bank (SFA 27) has been the primary focus of the Offshore Scallop fishery. In 1977, Canada and the US both declared 200-mile fishing zones. This limited Canadian fishing to a disputed zone of SFA 27. The dispute and the competitive fishery continued in this area until the International Court of Justice (ICJ) established an international boundary in October 1984, which awarded the northeast portion of SFA 27 to Canada [@icj_delimitation_1984]. The establishment of the ICJ line initiated discussions between DFO and the Offshore Scallop fishing industry on how to rebuild and maintain the Offshore Scallop stocks (for more details see @jonsen_georges_2009 and @stevens_evolution_2008). This led to opportunities and interest in the potential exploitation of other banks within the Canadian offshore jurisdiction. In 1973, the "deep-sea" fleet was limited to 76 licenses [@stevens_evolution_2008], and 50--76 vessels were active on the offshore banks from 1979--1984 [@robert_scallop_1985]. In September 1986, the Minister of Fisheries and Oceans divided the fishery into separate inshore and offshore scallop fleets with a spatial separation at the 43°40’ North latitude line near Yarmouth, Nova Scotia. This led to the inshore fleet being phased out of SFA 27 and SFA 26 fisheries over the next few years, while the offshore fleet was not permitted to fish in what were classified as inshore waters [@jonsen_georges_2009]. These changes to the available fishing areas for the offshore fleet led to competition for access to fishing grounds and resulted in the exploitation of all known offshore beds, even in areas quite distant from home ports (e.g. SFA 25B) [@robert_scallop_1988]. The number of licensed vessels that fished each year has declined over time; in 2003, 25 of 76 vessels fished offshore [@stevens_evolution_2008].

Since approximately 2010, the Offshore Scallop fleet has gradually shifted toward the use of factory freezer trawler vessels and automatic shucking machines. In 2016, there were twelve active vessels: five freezer trawlers and seven wetfish vessels. As of 2024, the fleet consists of five freezer trawler vessels (four of which have automatic shucking machines) and three wetfish vessels. All of these vessels exceed 32.1 metres (m) in overall length and fish using two or three New Bedford style steel dredges ranging from 12--15 feet in width. The ring size in the bag of the rakes varies by vessel, but are typically 3--4 inches (76--101 millimetres, mm) in diameter [@dfo_review_2008]. Over time, the fishery has become more efficient by increasing effort in high productivity areas, and reducing effort in low productivity areas [@keith_evaluating_2020], based on fishing experience and bottom mapping information. 

## Fishery data

Commercial fishery data are collected from mandatory logbooks submitted by fishers at the end of each trip. Landings are subject to dockside monitoring and a port sampling program to independently verify landed weights and compliance with meat count regulations. Logbook data are subjected to a quality control process to validate information used for Science purposes related to location, date, gear, tow duration and number, and landings. Prior to 2009, fishing log data were recorded on a 24 hour basis; from 2009 on, log data were recorded every 6 hours. For fishing that occurred prior to 2009, only records that passed historical quality control protocols (historically deemed "class 1", meaning that effort data for the records were available and reliable) were used for catch rate calculations; these catch rates were then used to estimate effort for records that were unreliable. For data in 2009 and later, all records were corrected through the quality control process, which resulted in 100% of the records being usable for catch rate, effort, and landings calculations. Logbook and port sampling data up to and including 2022 are used in this document.

In SFA 25, scallop landings have been below 100 tonnes (t) annually in recent years (Figure \@ref(fig:fts-25)). Within SFA 25, landings have traditionally been highest from SFA 25A-Sab. Fishing has occurred over much of SFA 25A since 1980, with landings highest in the western portion of SFA 25A-Sab, and the southeastern portion of SFA 25A-Mid (Figure \@ref(fig:fts-25) and \@ref(fig:foot-25)). Fishing in SFA 25B tends to target small areas, and this bank has been fished relatively infrequently over time (Figure \@ref(fig:foot-25)). Fishing effort has been below 50,000 hour-metres (hm) annually in all SFA 25 management units since 2000, with catch rates (kilograms per hour-metre; kg/hm) below 10 kg/hm in most years (Figure \@ref(fig:fts-25)). Meat weights have varied within and between stocks in SFA 25 (Table \@ref(tab:ps-tab), Figure \@ref(fig:mw-annual-25)). The long term median meat weights for SFA 25A-Sab, SFA 25A-Mid, and SFA 25B were 17.7 grams (g), 23.3 g, and 19.8 g, respectively (Table \@ref(tab:ps-tab)).

In SFA 26, scallop landings have varied between management units. SFA 26A has been below 500 t annually in recent years, but have exceeded 1,000 t historically, while SFA 26B and 26C have each been below 250 t in most years (Figure \@ref(fig:fts-26)). Fishing on SFA 26B is more sporadic than on SFA 26A or SFA 26C; for example, SFA 26B was not fished from 2014--2016 or 2020--2021 (Figure \@ref(fig:fts-26)). Fishing effort has rarely exceeded 50,000 hm in any of the SFA 26 management units, while catch rates (kg/hm) have been variable (Figure \@ref(fig:fts-26)). Fishing has occurred throughout SFA 26 since 1980, but overall catches have been highest on SFA 26A, particularly in the northern half of the management unit (Figure \@ref(fig:foot-26)). Meat weights have varied within and between stocks in SFA 26; the long term median meat weights for SFA 26A, SFA 26B and SFA 26C were 17.43 grams (g), 11.07 g, and 18.89 g, respectively (Table \@ref(tab:ps-tab), Figure \@ref(fig:mw-annual-26)). 

In SFA 27B, annual scallop landings have generally been below 750 t (Figure \@ref(fig:fts-27)). The area has been fished every year since 1981, except 2011. Fishing effort has rarely exceeded 30,000 hm since 2002, while catch rates have increased over time and exceed 20 kg/hm in recent years (Figure \@ref(fig:fts-27)). Fishing has occurred throughout SFA 27B since 1980, and catches are usually highest along the border with SFA 27A (Figure \@ref(fig:foot-27)). Meat weights have varied in SFA 27B, with a long term median of 13.8 g (Table \@ref(tab:ps-tab), Figure \@ref(fig:mw-annual-27)). 


# Survey

The DFO Maritimes Offshore Scallop Survey (the "survey" throughout this document) occurs through Collaborative Agreements (formerly Joint Project Agreements) between DFO Maritimes Science and the Seafood Producers Association of Nova Scotia (SPANS), which represents all license holders. The survey collects data on Sea Scallop (*Placopecten magellanicus*) in SFAs 25, 26, and 27, and additionally for Iceland Scallop (*Chlamys islandica*) in SFA 25B. The survey occurs in multiple management units within SFAs 25, 26, and 27, with survey data being the primary source of fishery-independent information used in the Maritimes Region scallop stock assessments. Under a Collaborative Agreement, survey responsibilities are shared by DFO and SPANS. At-sea survey activities are directed by the DFO Chief Scientist aboard the survey vessel. SPANS coordinates the provision of the survey vessel and the necessary crew complement to conduct the survey activities. DFO Science designs the survey, provides and manages scientific equipment, and validates, archives, and analyzes survey data. Survey data up to 2022 are used in this document.

## Survey history  

While survey tows have occurred in SFA 27B since 1978, the first official surveys in SFA 26A and 26C occurred in 1979. These surveys were funded by DFO and were conducted on the Canadian Coast Guard Ship (CCGS) E.E. Prince. In general, these surveys were designed using a stratification scheme based on catches or catch rates derived from commercial fishery logbooks [@jamieson_commercial_1986]. Strata for each bank were defined annually based on logbook records from the previous year of fishing on the bank. Station allocation was approximately proportional to the area of each stratum, but adjusted such that the higher catch strata were allocated more stations than the lower catch strata [@jamieson_commercial_1986]. Station locations were randomly assigned within each stratum based on the year’s allocation scheme. Neither historical survey strata areas nor coordinates were retained, however station locations are known.

SFA 25A-Mid was added to the survey in 1983, followed by SFA 25A-Sab (including Western Bank) in 1984 [@robert_scallop_1985]. For the next decade, survey coverage depended on the levels of fishing activity/effort on the individual banks with occasional limited surveys of SFA 25B. The area surveyed on each bank (or “survey domain”) changed annually during these years [@robert_scallop_1987]. Stratification methods also varied between stocks and over time. The evolving survey designs are detailed by bank in Section 3.4. 

During this period, there were additional projects included in the survey activities, including scallop tagging, phytoplankton and larval sampling, monitoring of juvenile hake within scallops, monitoring of epiphytes, genetic analysis, and meat sampling for heavy metal analysis. These science projects are not detailed here.

In 1994, the CCGS E.E. Prince was slated for retirement. Under a shared stewardship arrangement between the Offshore Scallop industry and DFO, the industry provided and crewed a commercial scallop Fishing Vessel (FV), FV Cape Keltic, to conduct the annual stock assessment surveys of the Offshore Scallop banks under the direction of a DFO Chief Scientist [@dfo_integrated_2024-1]. Comparative survey towing activities took place in SFA 25A-Mid (12 tows), SFA 25A-Sab (58 tows), SFA 26A (30 tows) and SFA 27 (12 tows) in 1994. There were no significant differences between the two vessels in estimates of biomass per tow for shell height classes over 100 mm [@robert_status_1995]. Since this time there have been three additional vessel changes; no comparative surveys were undertaken for these vessel changes. In 2007 and 2008, the survey took place on the FV E.E. Pierce, from 2009–2014 the survey took place on the FV Tenacity and starting in 2015 the FV Fundy Leader has been used to conduct the survey. Studies suggest that scallop catchability is not significantly affected by vessel changes using dredge gear [@roman_examination_2022; @smith_comparative_2013]

In 2015, there were delays in survey vessel preparations and therefore survey operations. Due to the delays, SFA 25A was not surveyed. SFA 26A was surveyed in July/August (with additional tows taking place in late September), and SFA 26C was surveyed in September.

In 2020, due to the COVID-19 pandemic, a limited survey of SFA 26A and the northern portion of SFA 27 was conducted by industry partners with logistical support from DFO Science but no DFO Chief Scientist on the vessel [@dfo_stock_2022]. A selection of stations from the 2018 and 2019 surveys of these banks formed the survey design in 2020. These data were collected for informational purposes only since the approved survey design was not used; they were not included in stock assessment analysis and are not included in this document.

## Sampling protocols  

Regardless of survey design, the same sampling protocol is followed: at each survey station, a 2.44 m New Bedford style scallop dredge (75 mm ring size) lined with 38 mm polypropylene mesh netting is used to conduct tows at predetermined locations. Each survey tow occurs for 10 minutes at a speed of 3 to 4 knots.

The scallop catch from each tow is sorted into baskets (for scallops > 50 mm) and buckets (for scallops ≤ 50 mm). The individual scallops’ shell heights are measured in 5 mm size bins and their mortality state (dead or alive) is recorded.

At the start of the survey time series, biological samples of 30 scallops were taken from a tow every 10 minute square of latitude and longitude. The scallops were dissected into meat, gonad, and soft parts while on board the vessel. The individual components were then frozen while at sea. In a DFO lab onshore at a later date, the biological components were thawed, weighed (wet and dry weight), had their shell heights measured precisely (to the nearest 0.1 mm instead of using the 5 mm bins) and aged. In summer of 2010, the procedure was revised such that only meat weight and shell height information were collected, but for an increased number of scallops (5 scallops per 5 mm bin); this "detailed sampling" process now takes place exclusively on the vessel during the survey. The relationship between the shell height and adductor muscle weight is particularly useful for monitoring the condition (meat weight given shell height) of scallops in a given place and time [@hubley_browns_2011].

Tows are tracked using a global positioning system (GPS) to provide information on location and length [@hubley_georges_2014]. Tow lengths can vary due to conditions such as vessel speed, tides, and sea state. For this reason, accurate tow lengths are required to standardize shell height frequency data across tows of various lengths to a common 800 m tow length. 

Over the past two decades, Ocean Vision was the navigational system used to record tow tracks, but during the 2022 survey of SFAs 26A, 26C and 27, an Olex navigational system was trialed as a replacement for Ocean Vision. A total of 449 tows were recorded using both systems. Tow tracking followed the same at-sea protocol as usual, but the two systems were used simultaneously. Tow lengths were calculated based on the tracks recorded by each system and compared by tow using the sf package in R [@pebesma_simple_2018]. The tows were recorded using the WGS 84 coordinate reference system, but were converted to the Universal Transverse Mercator (UTM) coordinate system for the purposes of length calculation (the UTM zone for each stock is provided in Table \@ref(tab:strata-tab)). 

Tows recorded using Olex were found to be longer in length (metres, m) than tows recorded using Ocean Vision (Figure \@ref(fig:nav-linear)). The median difference in length was 41.5 m (or 4%). After standardizing all tows to an 800 m tow length, this systematic difference would result in a small negative bias in indices derived from tows recorded using the Olex system compared to historical tows measured with Ocean Vision. To eliminate the bias in tow length ($L_{tow}$), a correction factor ($\delta$) of 1.04 was applied to the Olex tow length ($L_{olex}$):

$$L_{tow} = \frac{L_{olex}} {\delta}$$ 

This correction factor is applied to all Olex tows to ensure comparability with historical data collected under the Ocean Vision system (Figure \@ref(fig:nav-box)). Historical data collected using Ocean Vision is not affected by the transition to Olex.

## Survey database

The survey data (1978--Present) are housed in an internal DFO Oracle database called SCALOFF. As annual surveys take place, data are validated and uploaded to SCALOFF. This allows for consistent data handling, quality control, and data security. 

## Survey design  

Survey design details are presented by SFA in the following order to align with the chronological expansion of the survey across the Scotian Shelf over time: SFA 26 (began in 1978), SFA 27B (began in 1978), SFA 25 (began in 1983). Bank names are used when referring to years prior to the introduction of SFAs for each area, while the Table \@ref(tab:ps-tab) naming scheme is used once relevant. This summary includes information from both DFO publications and unpublished cruise reports. 

To summarize survey coverage over time, the spatial density of survey stations (for all years used for the development of survey indices) was calculated as the number of survey tows per cell in a 10 km^2^ grid on SFAs 25, 26, and 27B. In SFA 25, the number of survey tows in some 10km^2^ cells is high because of the fixed survey design on SFA 25A-Mid, whereas the stratification approach on SFA 25A-Sab leads to a more even coverage over a broader spatial area (Figure \@ref(fig:sfoot-25)). In SFA 26, survey tow density was highest in SFA 26A (Figure \@ref(fig:sfoot-26)). In SFA 27B, more tows have occurred near the boundary of SFA 27A than along the slope of the bank (Figure \@ref(fig:sfoot-27)).

### SFA 26

#### Browns Bank North (SFA 26A) and Browns Bank South (SFA 26B)

The first opportunistic survey of Browns Bank occurred in 1978 and consisted of seven randomly selected stations in areas where the commercial fleet was active. The following year, an official survey took place using randomly selected stations within two strata (Low Density and High Density) in a survey domain that surrounded commercial fishing locations [@jamieson_assessment_1981]. Stations were allocated proportional to commercial fishing effort. In 1980, 10 minute (10') grid cells with fishing activity were used to define the survey domain and 38 stations were completed; other survey design details are not available for this year. In 1981, the survey domain consisted of 10’ grid cells with at least ten days of fishing reported in commercial fishing logbooks from September 1980 to June 1981. The domain was separated into four strata based on landings, with a total of 30 stations on Browns Bank (allocation details are not available).

The 1982 survey was cancelled due to weather. In 1983, a catch percentage was calculated for each 10' grid cell by dividing the commercial fishery catch in the cell by the total commercial fishery catch on the bank. Cells were then separated into four strata levels (deemed Low, Medium, High and Exploratory) based on arbitrary catch percentage thresholds. Thirty stations were randomly allocated to the strata. The time frame of the commercial fishery logbook data used for these early surveys is unclear, but logbook data from the 1985 fishing season were used for the 1986 survey. In 1984, twenty stations were surveyed. The High stratum on Browns Bank represented cells with > 10% total catch, which covered 66% of the survey domain, and ten stations were allocated. The Medium stratum contained cells with 4--10% of the total catch, covering 25% of the survey domain, and received seven stations. The Low stratum represented cells with 0–-4% of the total catch, covered 8% of the survey domain, and was allocated three stations.

Within each stratum, the allocated stations were assigned at random. Some station locations were adjusted due to unsuitable bottom for towing. A similar methodology was used in subsequent years with the catch levels and strata areas being refined annually to reflect the catches experienced during the previous years' fishing activities. 

In 1985, an Exploratory stratum was added to Browns Bank to allow survey stations to occur in an area that was not fished in 1984, but had high numbers of age 2 scallops in previous surveys [@robert_scallop_1986]. In 1988 and 1989, the Browns Bank survey was cancelled due to a lack of fishing activity [@robert_scallop_1989]. 

An experimental fishery and management plan was implemented in 1989 for Browns Bank. Exploitation increased substantially during this time and there was a perception that the bank could potentially sustain long-term continuous exploitation [@robert_scallop_1990]. The 1990 survey focused on the areas fished during the experimental fishery since there had been little fishing activity for several years before this. Surveys from 1991--1993 were focused in the north, due to the spatial distribution of fishing activity [@robert_scallop_1993; @robert_status_1995].

In 1994, comparative surveys took place using the retiring CCGS E.E Prince and the industry supplied commercial scallop dragger, FV Cape Keltic, to facilitate the change to a new survey vessel. There were no significant differences between the two vessels in estimates of biomass per tow for shell height classes over 100 mm [@robert_status_1995], so the survey time series was treated as continuous (no conversion factor applied). The catch distribution from the previous 9 months of logbook records was used to derive strata; these strata were deemed Low, Medium, High, and Very High, where Very High was a stratum added in 1994 to reduce the variability in the High stratum given the catch rates observed. Stations were assigned randomly within each stratum. The survey continued to include an Exploratory stratum in years during which it was deemed necessary to cover additional areas of interest [@robert_status_1997].

In the fall of 1994, an additional survey took place on the south side of Browns Bank. The areas sampled were based on the locations fished between 1976 and 1985 and set in a grid pattern [@robert_status_1995]. This led to the expansion of the survey area in 1995 and 1996. Areas previously fished accounted for 64% of the total survey area in these years [@robert_status_1997].

In the late 1990s, information from a multibeam bathymetric survey (Canadian Hydrographic Service and Atlantic Geological Survey of Canada) of a portion of Browns Bank became available and was used in planning survey tows and towing direction [@kostylev_benthic_2001]. These mapping data provided a high resolution delineation of bottom type and topography. The introduction of bottom mapping data led to a re-evaluation of commercial fishing effort and catch rates used for the survey design [@robert_browns_1998].

By 2001, the relationship between bottom type (surficial geology) and scallop abundance was better understood. As a result, the stratification scheme for the survey was changed to a design based on surficial geology [@kostylev_benthic_2001; @kostylev_stock_2003]. The survey stations were randomly selected and allocated proportionally to the area of each stratum. There were 5 strata: gravel lag with thin sand, gravel lag, thin sand over gravel lag, thick sand, and sand with barchans. The five surficial geology strata were used annually from 2001 to 2011 (Table \@ref(tab:strata-tab)). In 1998, Browns Bank was divided into North and South management units, referred to here as SFAs 26A and 26B (Hubley et al. 2011).

Since 2011, SFA 26B has not been surveyed annually; the intermittent surveys continue to use the same stratified survey design based on surficial geology. On Browns Bank North, over time it became evident that the surficial geology was unable to account for the spatial variability in scallop abundance [@hubley_georges_2014]. A 2013 science and industry working group recommended a change in design to strata that were based on a more direct measure of scallop abundance. The historical commercial catch rate (HCR) for 2002--2012 was chosen as the stratifying variable because of limited survey coverage in previous years. This new design had significant gains in realized and potential efficiency [@hubley_georges_2014]. The areas associated with the HCR survey strata were revised in 2021 due to the discovery of a calculation error that had occurred since 2014; 81 km^2^ were removed from the area of the Very Low stratum, and a total of 5 km^2^ were removed from all other strata. The impact of this change on survey results was negligible. These strata remain in use for SFA 26A, while surficial geology strata are still used for SFA 26B (Table \@ref(tab:strata-tab), Figures \@ref(fig:map-bbn) and \@ref(fig:map-bbs)). 

#### German Bank (SFA 26C)

In 1979, the first official survey on German Bank occurred. As on Browns Bank, randomly selected stations were allocated proportional to commercial fishing effort within two strata (Low Density and High Density) in a survey domain that encompassed commercial fishing locations [@jamieson_assessment_1981]. 

In 1980, 10' grid cells with fishing activity were used to define the survey domain and 17 stations were completed; other survey design details are not available. In 1981, the survey domain was defined based on 10' grid cells with at least 10 days of commercial fishing activity from September 1980 to June 1981. The domain was separated into four strata levels based on landings, with a total of 23 stations on German Bank (allocation details are not available). Some station locations were adjusted due to unsuitable substrate for towing. At the start of the survey series, German Bank was surveyed using a 38 mm liner in the dredge but upon experiencing extensive damage to the liner due to the topography and bottom type of the area, it was decided to survey the area without a liner. 

The 1982 survey was cancelled due to weather. In 1983, the survey domain consisted of 10' grid cells with at least 5 fishing days. The time frame of the commercial fishery logbook data used for the 1983--1985 surveys is unclear, but logbook data from the 1985 fishing season were used for the 1986 survey. Grid cells were assigned to a Low, Medium, or High stratum based on the percentage of total landings from the bank in each cell. Stations were allocated randomly within the strata. In 1984, the German Bank strata were defined as High (>10% of total catch), Medium (4--10% of total catch) and Low (<4% of total catch). From 1986 to 1993, German Bank was not surveyed due to a lack of fishing activity in the area [@robert_scallop_1991].

In the Fall of 1994, survey operations resumed on German Bank after an 8 year hiatus (there was no fishing activity for 7 years). This survey took place using the industry supplied commercial scallop dragger, FV Cape Keltic. The survey covered areas south of the 43°40’ line and occurred after the lobster season to avoid gear conflicts. The restriction on the area surveyed was due to the inshore/offshore fleet separation that occurred in December of 1986 [@robert_activity_1995]. For surveys in 1994--1996, the commercial fishery logbook catch records from the previous year were used to stratify survey stations (similar to Browns Bank). An Exploratory stratum was occasionally added to the survey and the area surveyed depended on the locations of fishing activity in the previous year [@robert_activity_1995; @robert_status_1997].

In 1997 and 1998, the German Bank survey was cancelled due to a lack of fishing activity. Survey activities resumed in 1999 with the same catch stratification methodology. Starting in 2003, a subset of the survey stations were repeated from the previous surveys to better understand and improve the evaluation of the stock in this area. This continued until 2008.

In 2008, a trial was conducted in which 30 of the 80 planned survey tows and one exploratory tow used a liner comprised of 38 mm polypropylene mesh netting. The results of this trial, along with an accumulation of survey experience in SFA 26C and the addition of using high resolution bathymetry maps, led to the use of lined gear from this point forward. From 2009 on, the survey design was changed to use a sampling with partial replacement design to reduce statistical uncertainty [@warren_potential_1994], following the methods of @smith_scallop_2007. For this design, 25% of the stations are randomly selected from stations conducted in the previous year and 75% of the stations are randomly generated from areas with towable bottom (Table \@ref(tab:strata-tab), Figure \@ref(fig:map-ger)).

### SFA 27B

#### Georges Bank 'b' (SFA 27B)

Survey tows have been conducted on Georges Bank 'b' annually since 1978, consistent with the Georges Bank survey description by @jonsen_georges_2009. The majority of tows have occurred in August since the beginning of the time series, with additional tows occurring in May or June in most years. Initially, the survey covered the entirety of Georges Bank with 150 stations, using 4--6 strata based on annual commercial fishery logbook catch rate, and 6--42 stations (with a median of 23 stations) occurred on Georges Bank ‘b’ each year between 1981 and 2009. In 2009, a stratification scheme was proposed for the August survey of Georges Bank based on the survey abundance index from 1981–2008. At this time, the survey was divided into Georges Bank 'a' (SFA 27A) and Georges Bank 'b' (SFA 27B) surveys [@hubley_georges_2009]. This resulted in five strata and 30 stations dedicated to SFA 27B that have been used since 2009 (Table \@ref(tab:strata-tab), Figure \@ref(fig:map-gbb)). A spring monitoring survey of SFA 27 that occurs annually in May also includes 4 stations in SFA 27B, but given the limited nature of this survey, these data are not presented here. 

### SFA 25

#### Sable Bank (SFA 25A-Sab)

In 1983, Sable/Western Bank was added to the survey due to fishing effort expanding to the Eastern Scotian Shelf; however, the 1983 survey was cancelled due to weather conditions, so the first survey occurred in 1984 [@robert_scallop_1985]. At this time, all of SFA 25A was open to fishing. The survey domain consisted of 10' grid cells with at least five days of fishing. The time frame of the commercial fishery logbook data used for the 1983--1985 surveys is unclear, but logbook data from the 1985 fishing season were used for the 1986 survey. A stratified survey design was used with stratification based on commercial fishery logbook catch. A catch percentage was calculated for each grid cell by dividing the catch in the cell by the total commercial fishery catch on the bank. Three strata were created by arbitrarily dividing the resulting percentages into three groups, one with high catch percentages, one with medium percentages, and the third with low. In 1984, the High stratum consisted of grid cells with >8% of the commercial fishery catch on Sable/Western. This stratum covered 45% of the survey domain, and was assigned 13 stations. The Medium stratum consisted of grid cells with 4--8% of the commercial fishery catch on Sable/Western, covered 33% of the survey domain, and was assigned 13 stations. The Low stratum consisted of grid cells with 0--4% of the commercial fishery catch on Sable/Western, covered 23% of the survey domain, and was assigned 14 stations.

In 1986, the catch on Sable/Western Bank was the highest it had ever been [@robert_scallop_1987], which was attributed to the new Enterprise Allocation (EA) management approach. The Sable/Western survey domain expanded significantly from 1986 to 1990 to accommodate the changing fleet dynamics [@robert_scallop_1988; @robert_scallop_1990].

In 1991, a reduced survey occurred with 76 of the 90 planned survey stations completed. The High stratum was completed as planned, the Medium stratum was missing 2 tows, and only 50% of the planned tows in the Low stratum were completed [@robert_scallop_1992]. In 1994, a comparative survey was also undertaken in SFA 25A-Sab [@robert_activity_1995]. As with other areas, there were no apparent differences between the two vessels in estimates of biomass per tow for scallop shell height classes over 100 mm [@robert_status_1995], so the survey time series was treated as continuous (no conversion factor applied). In 1994, stratification using the 1993 catch would have provided poor coverage since fishing activity was spatially limited; therefore, 29 stations were allocated using the established stratification scheme, and an additional 29 survey stations were added to an Exploratory stratum to cover areas that were unfished at that time. The stations conducted in SFA 25A-Sab in 1994 were repeated in 1995 [@robert_scallop_1996].

In the next few years, exploratory tows were added to the stratified survey (within an Exploratory stratum) to cover grounds fished in the past in SFA 25A-Sab. These exploratory stations were not allocated in a systematic way. From 1999--2009, the survey design was based on the catch stratification methodology and 135 stations were sampled each year. 

From 2010 onwards, the stratification scheme has been based on the historical survey index from 1984--2008 (Table \@ref(tab:strata-tab)). There was a reduction in survey stations in 2012 due to reduced fishing effort and area covered by the fleet. The survey domain was further reduced in 2018 due to the implementation of the WEBCA in 2017, which excluded the fishery from fishing within this conservation area [@dfo_integrated_2024-1]. The most recent survey of SFA 25A-Sab is shown in Figure \@ref(fig:map-sab). 

#### Middle Bank (SFA 25A-Mid)

In 1983, Middle Bank was added to the survey due to fishing effort expanding to the Eastern Scotian Shelf [@robert_scallop_1985]. As on Sable/Western Bank, the survey domain consisted of 10' grid cells with at least five days of fishing. The time frame of the commercial fishery logbook data used for the 1983--1985 surveys is unclear, but logbook data from the 1985 fishing season were used for the 1986 survey. A stratified survey design was used with stratification based on commercial fishery logbook catch. A catch percentage was calculated for each grid cell by dividing the catch in the cell by the total commercial fishery catch on the bank. In 1984, the Middle Bank survey used two strata. The High stratum consisted of the grid cells that contained greater than or equal to 7% of the commercial fishery logbook catch on the bank, and covered 60% of the survey domain, so 12 of the 20 stations were randomly allocated to High strata. The remaining 8 stations were randomly allocated to the Low stratum (<7% of the catch, and covering the remaining 40% of the survey domain). This design was used between 1984 and 1988, with a total of 6 to 20 stations surveyed per year.

There was no survey between 1989 and 1991 [@robert_scallop_1991]. In 1992, eight tows were conducted in a survey that was stratified based on catch (as above) [@robert_scallop_1993]. Due to low stock levels and minimal fishing activity the survey was cancelled in 1993 [@robert_status_1994].

For the 1994 survey, exploratory tows were added to the catch-stratified survey within an Exploratory stratum due to limited fishing activity in 1993 to improve coverage; 12 tows were conducted [@robert_scallop_1996]. This survey was included in the comparative survey between the CCGS E.E. Prince and the FV Cape Keltic. From 1994--1996, the survey of SFA 25A-Mid used the same twelve stations. In 1997, three additional stations were added and this survey design has not changed since; the same fifteen stations have been used since 1996 as a fixed station survey design (Table \@ref(tab:strata-tab), Figure \@ref(fig:map-mid)). 

#### Banquereau Bank (SFA 25B)

The first survey on Banquereau Bank was an extension of the survey that was taking place on Sable/Western Bank in 1985. Over the next two decades there were a few years (1987, 1988, 1999) with limited and irregular surveys that employed a simple random sampling design that was informed by historical catch rates (Table \@ref(tab:strata-tab)). 

In absence of new knowledge of scallop distribution, the 2006 survey repeated 15 of the 18 survey tows from 1999, plus an additional 3 exploratory tows. The stations sampled in 2012 were randomly assigned within a survey domain informed by the distribution of commercial fishing effort (time frame unknown). These stations were repeated in 2019 with three additional exploratory stations (Figure \@ref(fig:map-ban)). 

In SFA 25B, Sea scallops and Iceland scallops both occur in harvestable quantities. In 2006, 2012, and 2019, both Sea scallops and Icelandic scallops were measured and enumerated separately but with the same onboard procedures to provide abundance estimates for both scallop species. 

# Estimation methods

## Meat weight-shell height relationship

During the DFO Maritimes Offshore Scallop Survey a subset of tows are selected for detailed sampling of meat weights (g) and shell heights (mm). The relationship between meat weight-to-shell height (MWSH) is modelled and used to convert length data to weight (biomass). The old MWSH model involved a two-step approach that is described in @hubley_georges_2014. Two statistical models were involved in this approach and it was not possible to propagate error or fully evaluate model diagnostics o. Here, we present a new one-step model based on the MWSH model used for other scallop stocks [@nasmith_scallop_2016; @hennen_shell_2012].

The new model used for the analysis is a generalized mixed effects model that is fit annually to the detailed meat weight-shell height data (Equation 2), where $wmw$ represents wet meat weight (g) and $sh$ is shell height (mm) of sampled scallop $i$ from a sampled tow location $l$ with a given depth. Shell height was log-transformed and centred at 100 mm, while depth was centred at the median depth of the sampled tows for each stock. Tow location $l$ was treated as a random intercept. Only years with detailed samples from at least two tows were modelled. 


$$log(wmw_{i,l}) \sim Gamma(\mu, \phi)$$
$$E(log(wmw_{i,l})) = \mu$$
$$var(log(wmw_{i,l})) = \frac{\mu}{\phi}$$
$$log(wmw_{i,l}) = log(sh_{i,l}) + depth_l + tow_l$$ 
$$tow_l \sim N(0, \sigma^2_{tow})$$

Here $\mu$ is the mean and $\phi$ is a shape parameter of the Gamma distribution, while $\sigma^2_{tow}$ is the variance of the tow random effect. More complex mixed effects models were tested (e.g., enabling the shell height ‘slope’ to vary by tow, models using all years of data with a year effect) but were not pursued due to convergence issues, while models without a random effect had unacceptable residual patterns.

The model fits to the data indicate the model framework is appropriate for these data for each of these scallop stocks (Figures \@ref(fig:mwsh-sab-1)--\@ref(fig:mwsh-gbb-1)). In some areas and years, the residuals for small (< 70 mm) and large (> 140 mm) shell heights had a small negative bias, but overall these residuals indicated no serious violations of the underlying model assumptions (Figures \@ref(fig:mwsh-sab-rs)--\@ref(fig:mwsh-gbb-rm)). This bias would have no impact on the biomass estimates for recruit sized scallop (see Section 1 for the definition of recruit and fully-recruited size classes) and would have a very small impact on the biomass estimates for fully-recruited scallop. For scallop over 140 mm in most stocks, this residual bias was either minimal (residual < 0.05 on the log scale) or the proportion of the population affected was small (usually < 3% of fully-recruited scallop). Thus, this small bias would have little impact on the biomass estimates for the majority of the stocks in most years. 

However, for SFA 26C the bias is somewhat larger than for the other stocks; in 4 years the median of the residuals for scallop with a shell height above 140 mm was below -0.1 (log scale). In these years the median proportion of scallop with a shell height greater than 140 mm was 0.15, so the overall fully-recruited biomass estimates in these years may be slightly overestimated (< 5%) in SFA 26C. In SFA 26B, the residuals were positive for larger sized scallop in several years (Figure \@ref(fig:mwsh-bbn-rm)). For this stock, this would lead to an underestimate of the biomass of the larger scallop in these years. For all of the model areas, meat weight tended to decline with depth in most years (Figures \@ref(fig:mwsh-sab-depth)--\@ref(fig:mwsh-gbb-depth)).

The MWSH model enables the estimation of scallop meat weight at a given shell height. To represent change in the model fit between years, we predict the meat weight of a 100 mm shell height scallop each year at the median depth of all sampled tows; this index, the weight of a 100 mm scallop, is referred to as scallop condition. We compared the scallop condition for each bank with the condition index estimated from the old MWSH model [@hubley_georges_2014]. Within SFA 25, the new estimates of condition are slightly higher using the new model (Figure \@ref(fig:cfts-25)). In SFA 25A-Sab, the new model condition is 2% higher (calculated as the median of annual differences), in SFA 25A-Mid it is 7% higher, and in SFA 25B it is 3% higher (Figure \@ref(fig:cfts-25)). In SFA 26A and 26B, the new model condition estimates were also higher (Figure \@ref(fig:cfts-26)), mainly due to the estimates in more recent years (1% and 6% medians, respectively). Condition using the new model was 4% lower (median difference) for SFA 26C (Figure \@ref(fig:cfts-26)). In SFA 27B, the new model condition estimates were 1% higher (median) than those from the previous model (Figure \@ref(fig:cfts-27)). Note that the new model could not estimate condition for years with fewer than two sampled tows, resulting in some years without estimates; there were five such years for SFA 25A-Mid, three years for SFA 25B, two years for SFA 26B, two years for SFA 26C, and six years for SFA 27B. 


## Shell height-at-age

The relationship between shell height and age has historically been described using von Bertalanffy (vonB) growth models. Scallop ages can be estimated by counting growth rings on their shells. Age analyses have been documented previously for SFAs 26A and 27A. In the 2014 assessment, incremental ageing was undertaken for four scallop shells collected during the 2012 survey [@hubley_georges_2014]. @hubley_georges_2014 attributed differences between their vonB parameters and previous results to spatial variability in growth rates [@hubley_browns_2011]. Age data for scallop shells from SFA 25 have not been documented previously.

For this framework, new samples from SFA 25A-Sab (95 shells from 19 tows, collected in 2016) and SFA 26A Brown Bank North (201 shells from 28 tows, collected in 2011 and 2012) were incrementally aged (Table \@ref(tab:age-summary)) using the shell analysis methods of @hart_estimating_2009. Shells collected from SFA 26A in 2012 were selected to facilitate comparison with the shells from the same year aged by @hubley_georges_2014, however the same shells were not re-aged. Each growth increment between shell rings was measured to the nearest mm, resulting in 383 and 804 measurements for SFA 25A-Sab and SFA 26A, respectively. As such, more measurements were available for increments of age 2–3 than those of older ages (and larger shell height); measurements were obtained for ages up to 10 (Table \@ref(tab:age-inc)). For a given age increment, scallop from SFA 26A were approximately 5–15 mm larger than from SFA 25A-Sab (Table \@ref(tab:age-inc)). 

VonB growth models were developed using nonlinear least squares (NLS) and included random effects to account for the repeated measurements of individual scallop.

In Equation 3, $L_t$ is the length of scallop of age $t$, $L_{\infty}$ is a model parameter that estimates the maximum shell height, $K$ is a model parameter that estimates the rate of increase in shell height at young ages, $t_0$ is a model parameter that estimates the age in which scallop shell height is zero, $l_{\infty,l}$ is the random effect based on location $l$$ for the maximum shell height parameter, $k_t$ is the random effect for the rate parameter, and $t$ is the age of the scallop. Starting values for the model were $L_\infty$ = 150, $K$ = 0.3 and $t_0$ = 0. Confidence intervals (95%) were calculated using bootstrapping for the NLS models. 

$$L_t \sim N(\mu,\phi)$$
$$E(L_t) = \mu$$
$$ var(L_t) = \phi^2$$
$$l_{\infty,l} ~ N(0,\sigma^2_{l_{\infty,l}})$$
$$L_{t} = (L_\infty - l_{\infty,j})(1-e^{-(K-k_j)(t-t_0)})$$
$$k_{t} ~ N(0,\sigma^2_{k_t})$$
For SFA 25A-Sab, the growth parameters based on increment measurements were $L_{\infty}$ = 159.2, $K$ = 0.2, and $t_0$ = 0.2 (Figure \@ref(fig:vb-sab)) The model residuals indicate that the model fits the data appropriately (Figure \@ref(fig:resid-sab)). For SFA 26A, the growth parameters based on increment measurements were $L_{\infty}$ = 164.4, $K$ = 0.2, and $t_0$ = -0.2 (Figure \@ref(fig:vb-bbn)). The model residuals indicate that the model fits the data appropriately (Figure \@ref(fig:resid-bbn)). The parameters from this analysis differ from previous SFA 26A vonB estimates ($L_{\infty}$ = 148, $K$ = 0.19, $t_0$ = 0.11); the current model suggests growth is higher and the maximum shell height is larger than the previous analysis [@hubley_georges_2014].


## Recruit and fully-recruited sizes

To understand the population dynamics of the scallop stocks in SFAs 25, 26, and 27B, survey indices are calculated using size-based categories. The stock assessment models require a biomass estimate and growth rate for fully-recruited scallops (scallops that are landed by the fishery), and recruit size scallops (scallops that will be fully-recruited size within one year). While survey data provide information on the overall size structure of the scallop populations, the minimum fully-recruited size depends on the size of the scallops that are landed by the fishery and the minimum recruit size depends on the annual growth rate of scallop shells. The size at which scallops recruit to the fishery and their size one year prior form a “recruit size range” used in DFO Maritimes Science analyses and this range has varied between offshore scallop stocks (Table \@ref(tab:rec-size)). This range has traditionally varied across offshore scallop stocks and could change over time in response to stock or fishery dynamics. 

For the two stocks for which models are being developed as part of this Framework, SFA 25A-Sab and SFA 26A [@keith_framework_nodate], the recruit size range can be evaluated due to the availability of the new shell height-at-age relationships (Section 4.2), combined with information from the Port Sampling program (Section 2.2) and the application of MWSH models (Section 4.1). For the remaining stocks (without new shell height-at-age information), only the overlap of the fishery with the current size categories can be explored.

The first step in this analysis is to estimate the shell heights of scallop targeted by the fishery. The Port Sampling data provide a sample of the scallop meat weights landed by the fishery.  These meat weights can be converted to shell heights using the MWSH models developed for each stock. Given the known seasonal variability in scallop meat weight [@hennen_shell_2012; @sarro_spatial_2009], this analysis used port sampling data from two time periods: year-round, and from April to August (inclusive) only. This shorter period of time corresponds to the period in which most fishing activity occurs, is similar to the timing of the annual surveys (mid-late May and August), and is prior to the fall spawning period when meat weights typically decline and after the meat weight increase peaks in the spring [@hennen_shell_2012; @sarro_spatial_2009].

The shell heights of meats landed in SFA 25A-Sab were estimated to range between 65 and 195 mm (Figure \@ref(fig:sh-ps-sab)) and over 98% of landings were of scallops greater than 90 mm in shell height (Figures \@ref(fig:prop-ps-sab) and \@ref(fig:propss-ps-sab)). The shell heights of meats landed in SFA 25A-Mid were estimated to range between 70 and 160 mm (Figure \@ref(fig:sh-ps-mid)) and over 85% of landings were of scallops greater than 90 mm in shell height (Figures \@ref(fig:prop-ps-mid) and \@ref(fig:propss-ps-mid)). The shell heights of meats landed in SFA 25B were estimated to range between 80 and 175 mm (Figure \@ref(fig:sh-ps-ban)) and over 96% of landings were of scallops greater than 90 mm in shell height (Figures \@ref(fig:prop-ps-ban) and \@ref(fig:propss-ps-ban)). 

The shell heights of meats landed in SFA 26A were estimated to range between 65 and 195 mm (Figure \@ref(fig:sh-ps-bbn)) and over 96% of landings were of scallops greater than 95 mm in shell height (Figures \@ref(fig:prop-ps-bbn) and \@ref(fig:propss-ps-bbn)). The shell heights of meats landed in SFA 26B were estimated to range between 75 and 185 mm (Figure \@ref(fig:sh-ps-bbs)) and over 98% of landings were of scallops greater than 95 mm in shell height (Figures \@ref(fig:prop-ps-bbs) and \@ref(fig:propss-ps-bbs)). The shell heights of meats landed in SFA 26C were estimated to range between 65 and 195 mm (Figure \@ref(fig:sh-ps-ger)) and over 92% of landings were of scallops greater than 105 mm in shell height (Figures \@ref(fig:prop-ps-ger) and \@ref(fig:propss-ps-ger)).

The shell heights of meats landed in SFA 27B were estimated to range between 65 and 175 mm (Figure \@ref(fig:sh-ps-gbb)) and over 98% of landings were of scallops greater than 95 mm in shell height (Figures \@ref(fig:prop-ps-gbb) and \@ref(fig:propss-ps-gbb)).

The next step in the process is to explore the size-selectivity of the fishery by comparing the estimated shell height distribution in the fishery (using data from April to August) with the shell height distribution in the survey for each year that both data types are available. This is undertaken to determine whether the fishery is targeting a range of scallop shell heights that differs from the shell height distribution of the scallop population.  Here we are making the assumption that the shell height distribution observed using the survey gear is representative of the actual shell height of the scallop population. 

For SFA 25A-Mid and 25B, there were relatively few years with port sampling data and survey detailed sampling data during the April to August window (Figures \@ref(fig:sh-sel-mid), \@ref(fig:sh-sel-ban), A13, and A14). Given the paucity of data for these stocks, there is insufficient evidence to suggest revising the existing minimum fully-recruited size (90 mm).

For SFA 26B, there was only one year with both port sampling and survey detailed sampling data to perform the selectivity analysis in the April to August window (Figures \@ref(fig:sh-sel-bbs) and A15), however the results support the continued use of the 95 mm minimum fully-recruited size. 

For SFA 26C, the minimum size of scallop landings has tended to be higher than for other stocks (of all stocks, SFA 26C had the lowest percentage of landings below 100 mm). However, in some years, over 5% of landings from April to August were of scallops below 100 mm in shell height (Figures \@ref(fig:sh-ps-ger), \@ref(fig:propss-ps-ger), \@ref(fig:sh-sel-ger), and A16). Based on the survey detailed sampling and fishery port sampling data available currently, the selectivity pattern is unclear, so the minimum fully-recruited size should remain unchanged at 105 mm. As more data become available over time, the minimum fully-recruited size for SFA 26C should be revisited in case there is a consistent shift in the fishery selectivity.

For SFA 27B, the fishery primarily targets scallop larger than 100 mm, but there are some removals of scallop in the 90--100 mm size ranges in several years. This variability suggests that the existing minimum fully-recruited size of 95 mm is reasonable (Figures \@ref(fig:sh-sel-gbb) and A17). 

For both SFA 25A-Sab (Figures \@ref(fig:sh-sel-sab) and A18) and SFA 26A stocks (Figures \@ref(fig:sh-sel-bbn) and A19), indices of fully-recruited scallop are being used in an assessment model that assumes knife-edged selectivity; the recruits are not subjected to fishing mortality while the fully-recruited scallop are available to the fishery [@keith_framework_nodate]. For SFA 25A-Sab, the median proportion of scallop less than 90 mm that were landed by the fishery was 0.016. The proportion of the stock that the survey observed in the recruit size categories had minimal influence on this proportion. Scallop greater than 90 mm in size were landed by the fishery in SFA 25A-Sab, so retaining the existing minimum fully-recruited size of 90 mm is recommended. Similarly for SFA 26A, the median proportion of scallop less than 90 mm that were landed by the fishery was 0.006 (for April to August only) or 0.005 (year-round). The proportion of the stock that the survey observed in the recruit size categories had minimal influence on this proportion. Scallop greater than 90 mm in size were landed by the fishery, so retaining the existing minimum fully-recruited size of 90 mm for SFA 26A is also recommended.

For the stocks with new shell height-at-age information, SFAs 25A-Sab and 26A, the size of scallops one year prior to fishery recruitment can also be estimated; the vonB growth curves (Section 4.2) can be used to estimate the size of a 90 mm scallop in the previous year. For SFA 25A-Sab, a scallop with a 90 mm shell height was estimated to be 4.46 years of age. The estimated minimum shell height of recruit scallop one year prior (at age 3.46) was 74.96 mm (Figure \@ref(fig:vb-sab)). For SFA 26A, a scallop with a 90 mm shell height was 3.81 years of age. The estimated minimum shell height of recruit scallop one year prior (at age 2.81) was 73.66 mm (Figure \@ref(fig:vb-bbn)).

Scallop in the survey are measured in 5 mm size bins, as such the recruit size range should be a multiple of 5.  Based on the above analysis, the recruit size range used for both SFA 25A-Sab and SFA 26A was determined to be 75-90 mm shell height (Table \@ref(tab:rec-size)).

To evaluate the impact of the new recruit size range on survey indices for SFA 25A-Sab and SFA 26A, recruit abundance and biomass estimates (per tow) were calculated using the 75–90 mm range, and the previously used range (80–90 mm for SFA 25A-Sab and 85–95 mm for SFA 26A). For SFA 25A-Sab (Figure \@ref(fig:rec-comp-sab)) and SFA 26A-BBn (Figure \@ref(fig:rec-comp-bbn)), the range of 75–90 mm resulted in higher abundance and biomass estimates of recruits than the previously used range.


# Stock Indicators

Science advice relies on the development of indices which provide an understanding of the stock status and population dynamics. For stocks that require Science advice, but there is no analytical assessment model, the indices are used directly to guide the advice and management decisions. Alternatively, when analytical stock assessment models are used, these indices become the input data that underlie the modelled stock status indicators. For scallop stocks in the Maritime Region, the primary indices that inform science advice are the biomass and abundance indices of recruit and fully-recruited scallop [@dfo_scallop_2023; @dfo_stock_2023-1; @dfo_stock_2023-2]. Indices of recruit and fully-recruited growth and a proxy index for natural mortality (all three size classes) are also input to the analytical assessment models. The natural mortality index and indices of pre-recruit abundance and biomass are also used as contextual information outside of the stock assessment model framework.

## Abundance and Biomass Indices

Abundance and biomass estimates for the stocks SFA 25A-Sab, SFA 26A, SFA 26B, and SFA 27B are estimated using stratified estimates based on the current survey stratification (see Section 3.4). SFA 25A-Mid uses a fixed station design and SFA 25B has been sampled infrequently using various survey designs; these two areas use simple random survey estimation methods (for SFA 25A-Mid, the fixed design precludes the development of statistically valid estimates of variability for the empirical indices and, as such, error bars are not shown for this area). Finally, SFA 26C currently uses a sampling with partial replacement design and the survey indices derived for this area account for this sampling scheme. The survey indices were calculated using R version 4.1.2 using unpublished R packages called _PEDstrata_ for the stratified estimates and and _SPR_ for sampling with partial replacement. 

In SFA 25A-Sab, the abundance and biomass survey indices indicate that fully-recruited scallop have declined steadily since peaking in 2005, and there was a concomitant decline in the recruit indices throughout this period, although in recent years the fully-recruited index has continued to decline despite both the pre-recruit and recruit indices being elevated (Figures \@ref(fig:rec-comp-sab) and \@ref(fig:sts-25)). In SFA 25A-Mid, the abundance and biomass survey indices indicate that abundance was elevated for a brief period in the mid-1990s corresponding to a period in which the recruit abundance was elevated (Figures \@ref(fig:sts-25)). In SFA 25B, there are very few years of data making the observations difficult to interpret; there was a large recruitment event observed in 1999 but otherwise no obvious trends are observed  (Figure \@ref(fig:sts-25)).

In SFA 26A, two large recruitment events are evident, one in the early 2000s and a second event approximately a decade later (Figures \@ref(fig:rec-comp-bbn) and \@ref(fig:sts-26)). The first large recruitment event led to the highest values of fully-recruited scallop in the time series, the second recruitment event also resulted in an increase in the fully-recruited index, though it was more muted (Figures \@ref(fig:rec-comp-bbn) and \@ref(fig:sts-26)). In SFA 26B, a large recruitment event was also observed in the early 2000s and this was followed by a brief period in which the fully-recruited abundance index was elevated (Figure \@ref(fig:sts-26)). There is also an increase in the pre-recruit index around 2010, but this seems to have had a relatively minor impact on the recruit or fully-recruited indices (Figure \@ref(fig:sts-26)). In SFA 26C, the recruit and fully-recruited indices were elevated in the early-mid 2000s, but since the survey switched to a lined survey dredge in 2008 there has been little variability in the indices, though the fully-recruited indices have been in decline over the last decade, with the 2022 fully-recruited indices being the lowest since the lined survey dredge was in use (Figure \@ref(fig:sts-26)).

In SFA 27B, the recruit and fully-recruited indices were elevated throughout the mid-2000s and again in the late 2010s, in both cases increases in the recruit index resulted in increases in the fully-recruited indices (Figure \@ref(fig:sts-27)).

## Shell Height Frequency

While not an index of stock status, the shell height frequencies provide an additional means of understanding the population dynamics of a stock at a more granular level than the abundance and biomass indices. The use of a 38 mm liner in the survey dredge ensures consistent selectivity of scallops in 5 mm size bins of 40 mm and above. While the survey does catch scallops below 40 mm in size, quantitative conclusions cannot be made regarding the frequency of scallops in these smaller bins as they are smaller than the liner mesh size and thus not reliably caught. Given the challenges of interpreting the shell height frequency figures for stocks in which a large recruitment event has occurred, additional figures are available in Appendix A to show the shell height frequencies of scallop 70 mm and larger in size.

In SFA 25A-Sab, the shell height frequencies have historically shown the growth of scallop from pre-recruit to fully-recruited size, but since 2016 few individuals are being observed once they reach approximately 85 mm in size (Figure \@ref(fig:shf-sab)). In SFA 25A-Mid, growth from larger pre-recruit to fully-recruited sizes has been observed, but the survey appears to have had challenges with observing the smaller pre-recruit sizes (Figure \@ref(fig:shf-mid)). In SFA 25B, there are insufficient data to track scallop growth over time (Figure \@ref(fig:shf-ban)).

In SFA 26A, the shell height frequencies have historically shown the growth of scallop from pre-recruit to fully-recruited size, but since 2016 pre-recruit scallop have not been tracked to fully-recruited sizes in later years (Figure \@ref(fig:shf-bbn)). In both SFA 26B and SFA 26C, several years with large numbers of pre-recruits have been observed but these do not tend to be observed again in appreciable numbers the following year (Figures \@ref(fig:shf-bbs) and \@ref(fig:shf-ger)). However, when looking at the data using only scallop > 70mm in size, there is evidence that the survey is able to track growth from the larger pre-recruit sizes to fully-recruited size in both areas (Figures A3 and A4).

In SFA 27B the extremely large recruitment event in 2014 makes interpretation of the trends difficult (Figure \@ref(fig:shf-gbb)), but using the data from 70mm+ only the growth of scallop from large pre-recruits through to fully-recruited sizes is evident, especially in recent years (Figure A5).

## Growth

Annual observed growth rates are calculated for recruit and fully-recruited size classes following @hubley_georges_2014. The calculation involves vonB growth parameters, so growth can only be calculated for SFA 25A-Sab and SFA 26A. The growth rate of fully-recruited ($g_{fr,t-1}$) and recruit ($g_{r,t-1}$) scallops are calculated as the ratio between the expected average meat weight weight (see page 4 in Hubley et al. 2014) of fully-recruited ($\bar{w}_{fr,t}$) or recruit sized scallops ($\bar{w}_{r,t}$) in the current year's survey ($t$) and the observed average meat weight of fully-recruited or recruit sized scallops in the previous year $(t-1)$:

<!-- \begin{align}  -->
$$g_{fr,t-1} = \frac{\bar{w}_{fr,t}}{\bar{w}_{fr,t-1}}$$
$$g_{r,t-1} = \frac{\bar{w}_{r,t}}{\bar{w}_{r,t-1}}$$
<!-- \end{align} -->

The growth rates can vary substantially from year to year, but no temporal trends in growth are evident for either stock (Figures \@ref(fig:growth-25) and \@ref(fig:growth-26)). Growth rates for SFA 26A using the new MWSH model and new vonB growth parameters presented in this document are higher than growth rates calculated using the previous MWSH model and vonB parameters from @hubley_georges_2014, but the variability between years is similar (Figure \@ref(fig:growth-26)). 

## Natural Mortality

Empty paired and hinged scallop shells, known as “clappers”, are counted during the survey and a clapper index is calculated for pre-recruit, recruit, and fully-recruited scallop; with the clapper index for recruit and fully-recruited scallop used in the stock assessment models to inform natural mortality [@keith_framework_nodate; @hubley_georges_2014]. The clapper index is calculated using the equation:

$$PC_t = \frac{NC_t}{NL_t + NC_t} * 100$$
Where $PC_t$ is the percentage of clappers, $NC_{t}$ is the number of clappers, $NL_{t}$ is the number of live scallop and $t$ is year. For stocks in SFA 25, the percentage of clappers  has been below 10% for all size classes (Figure \@ref(fig:cts-25)), with long term medians for the fully-recruited size class in SFAs 25A-Mid, 25A-Sab, and 25B of 0.4%, 2.3% and 2.0%, respectively (Table \@ref(tab:tab-sts)). For stocks in SFA 26, the percentage of clappers has been below 20% for all size classes (Figure \@ref(fig:cts-26)), with long term medians for the fully-recruited size class in SFAs 26A, 26B, and 26C of 2.0%, 2.4% and 1.7%, respectively (Table \@ref(tab:tab-sts)). For SFA 27B, the percentage of clappers has reached approximately 40% in all size classes at least once during the time series, however recent years have been below 20% (Figure \@ref(fig:cts-27)). The long term median for the fully-recruited size class in SFA 27B is 5.7% (Table \@ref(tab:tab-sts)). 

## Relative Fishing Mortality

Annual estimates of relative fishing mortality ($RF_t$) were calculated by comparing the annual landings $C_t$ to the survey biomass estimates $B_t$ (where $t$ is year);

$$RF_t = \frac{C_{t}}{B_{t}}$$


The surveys of SFA 25 and SFA 26 normally occur in mid-late May, while the survey of SFA 27B occurs in August, thus the fishery landings are summarized in terms of a survey year, from June to May of the following year for SFA 25 and 26 and September to August for SFA 27B. For example, in SFA 27B, the removals from September 2019 to August 2020 are treated as year 2019 removals for this calculation. The survey biomass was not corrected for catchability of the survey gear.

Relative fishing mortality has fluctuated over time, but has generally been higher for the SFA 27B and 26A stocks than for the SFAs 25, 26B and 26C stocks (Figure \@ref(fig:relf)). 

# Conclusions

This document summarizes the historical fishery and survey data used for the provision of stock assessment advice in SFAs 25, 26, and 27B. A new MWSH model was developed for use in for SFAs 25, 26, and 27B, and was used to calculate biomass and condition in these areas. New shell height-at-age data were available for SFA 25A-Sab and SFA 26A, and provided new growth curves for both of these areas. In SFA 26A, the ageing methods resulted in higher growth estimates than were observed from a more limited sample size of scallop aged in @hubley_georges_2014. To the best of our knowledge this is the first time shell height-at-age data have been published for SFA 25A-Sab. Port sampling data were combined with the new MWSH model to estimate the size classes of scallop targeted by the fishery. This analysis indicated that the fishery rarely landed scallop meats from scallops smaller than 90 mm in size for the majority of the stocks, although larger scallop have been targeted historically in SFA 26C. For SFA 25A and SFA 26A, the port sampling data were combined with the new growth curves to define size categories for fully-recruited, recruited, and pre-recruit scallop. In both areas, this analysis indicated that scallop with a shell height between 75 and 89 mm in size grow sufficiently over the course of a year to enter the fully-recruited size class in the following year. Stock indicators were provided for each of the stocks. For the stocks with survey data collected annually, the survey is able to track the growth of scallop from pre-recruits over 40 mm in shell height to fully-recruit scallop and the indicators presented here have utility for the provision of science advice.

# Other Considerations

The shell height-at-age analysis was performed for only the stocks in which a stock assessment model is being developed. Ideally, age information would be available for each of the stocks (and for multiple years) to better understand scallop shell growth variability. As shown here, size-at-age data, port sampling data, and MWSH data can be combined to inform the recruit size categories and to explore the size-selectivity of the fishery.

Gear selectivity (and catchability) influences the understanding of overall scallop biomass and is an integral component of the models used to provide scallop advice in the Maritimes Region [@hubley_georges_2014; @mcdonald_explicit_2021; @mcdonald_incorporating_2022]. Unfortunately, data to inform an analysis of catchability using the survey gear are not available at this time. Catchability is a function of the vessel, fishing gear, scallop size and density, and bottom habitat. For scallop dredge fisheries, the vessel effects are often less influential than in trawl fisheries; as a result, much of the focus on catchability estimates focus on the gear configuration, scallop size and density, and the bottom habitat [@miller_estimation_2019; @roman_selectivity_2019]. Selectivity studies have been undertaken on sea scallop in other jurisdictions, but without dedicated studies using the dredges used in the Canadian Offshore Scallop fishery, we must rely on these studies from other jurisdictions [@miller_estimation_2019; @roman_selectivity_2019]. Unfortunately, these studies provide extremely wide bounds on the potential range of catchability for sea scallop fisheries [@miller_estimation_2019]. Catchability and selectivity studies within Canadian waters would likely improve the understanding of scallop productivity in Canada.
