---
output: html_document
editor_options: 
  chunk_output_type: console
---
\clearpage

# Tables {-}

```{r include=F, echo=F}
require(tidyverse)
require(csasdown)
require(kableExtra)
require(officedown)
require(officer)
require(flextable)

# These are the 4 tables I want to make.
# clean things up...
bias.sab.clean <- bias.sab[,-ncol(bias.sab)]
bias.sab.clean[,c(2,4,5,6)] <- round(bias.sab.clean[,c(2,4,5,6)],digits=2)
bias.sab.clean[,c(1,3)] <- round(bias.sab.clean[,c(1,3)],digits=0)
# Now get beter names
names(bias.sab.clean) <- c("Biomass retro","Relative Biomass retro",
                           "Recruit retro","Relative Recruit retro",
                           "Natural Mortality retro","Relative Natural Mortality retro")
                           
# Same for bbn....
bias.bbn.clean <- bias.bbn[,-ncol(bias.bbn)]
bias.bbn.clean[,c(2,4,5,6)] <- round(bias.bbn.clean[,c(2,4,5,6)],digits=2)
bias.bbn.clean[,c(1,3)] <- round(bias.bbn.clean[,c(1,3)],digits=0)
# Now get beter names
names(bias.bbn.clean) <- c("Biomass retro","Relative Biomass retro",
                           "Recruit retro","Relative Recruit retro",
                           "Natural Mortality retro","Relative Natural Mortality retro")
# Now transpose the model parameter table
sab.10.parm.table <- data.frame(value = t(sab.10.parm.table))

bbn.20.parm.table <-  data.frame(value = t(bbn.20.parm.table))


sab.bias.table <- csas_table(bias.sab.clean,
                             caption ="Annual retrospecitve results for SFA 25a.  Positive values indicate the retrospective
                              model estimates were higher than that base model. The Biomass retro and Recruit retro are in tonnes.
                             The relative metrics are proportional differences between the retrospective model and the base model.
                             The year represents the terminal year used to compare with the base model.")

bbn.bias.table <- csas_table(bias.bbn.clean,
                             caption ="Annual retrospecitve results for SFA 26a.  Positive values indicate the retrospective
                              model estimates were higher than that base model. The Biomass retro and Recruit retro are in tonnes.
                             The relative metrics are proportional differences between the retrospective model and the base model.
                             The year represents the terminal year used to compare with the base model.")

sab.param.table <- csas_table(sab.10.parm.table,caption="Selected parameter estimates from SEAM in SFA-25a")
bbn.param.table <- csas_table(bbn.20.parm.table,caption="Selected parameter estimates from SEAM in SFA-26a")

# sab.bias.table <- kableExtra::kbl(bias.sab.clean, booktabs = TRUE, escape =F, format = 'pipe',
#                              caption ="Annual retrospecitve results for SFA 25a.  Positive values indicate the retrospective
#                               model estimates were higher than that base model. The Biomass retro and Recruit retro are in tonnes. 
#                              The relative metrics are proportional differences between the retrospective model and the base model.  
#                              The year represents the terminal year used to compare with the base model.")
# 
# bbn.bias.table <- kableExtra::kbl(bias.bbn.clean, booktabs = TRUE, escape =F, format = 'pipe',
#                              caption ="Annual retrospecitve results for SFA 26a.  Positive values indicate the retrospective
#                               model estimates were higher than that base model. The Biomass retro and Recruit retro are in tonnes. 
#                              The relative metrics are proportional differences between the retrospective model and the base model.  
#                              The year represents the terminal year used to compare with the base model.")
# 
# sab.param.table <- kableExtra::kbl(sab.10.parm.table, booktabs = TRUE, escape =F, format = 'pipe',
#                                    caption="Selected parameter estimates from SEAM in SFA-25a")
# bbn.param.table <- kableExtra::kbl(bbn.20.parm.table, booktabs = TRUE, escape =F, format = 'pipe',
#                                    caption="Selected parameter estimates from SEAM in SFA-26a")
# strata <- kableExtra::kbl(strata, align = "l", valign = "t") %>%
#   kableExtra::collapse_rows(columns = 1:4, valign = "top")

# ageing_bbn <- read.csv("Y:/Offshore/Assessment/Framework/SFA_25_26_2024/DataInputs/Ageing/BBn/summary_stats.csv")
# ageing_sab <- read.csv("Y:/Offshore/Assessment/Framework/SFA_25_26_2024/DataInputs/Ageing/Sab/summary_stats.csv")
# ageing_bbn$`Management Unit` <- "Browns Bank North"
# ageing_sab$`Management Unit` <- "Sable Bank"
# ageing <- rbind(ageing_sab, ageing_bbn)
# ageing <- dplyr::select(ageing, -X)
# ageing <- data.frame(ageing$`Management Unit`, ageing[,1:(ncol(ageing)-1)])
# names(ageing)[1:2] <- c("Management Unit", "Model")
# ageing1 <- unique(dplyr::select(ageing, Model, Formula))
# ageing2 <- dplyr::select(ageing, -Formula)
# ageing2$AIC <- round(ageing2$AIC, 0)
# ageing2$r.sq <- round(ageing2$r.sq, 3)
# ageing2$scale.est <- round(ageing2$scale.est, 2)
# ageing2[,c("H10", "H5", "H2", "K_maxR", "K_avgFR", "K_2_to_5")] <- round(ageing2[,c("H10", "H5", "H2", "K_maxR", "K_avgFR", "K_2_to_5")], 1)
# ageing2$`Management Unit`[ageing2$`Management Unit`=="Sable Bank"] <- c("Sable Bank", NA, NA)
# ageing2$`Management Unit`[ageing2$`Management Unit`=="Browns Bank North" & !is.na(ageing2$`Management Unit`)] <- c("Browns Bank North", NA, NA)
# ageing3 <- ageing2[,c(1:2,9:7)]
# ageing4 <- ageing2[,c(1:2,10:15)]
# ageing2 <- ageing2[,c(1:6)]

opts <- options(knitr.kable.NA = "")

```



```{r sab-param-table,include=T,echo=F}
csas_table(sab.10.parm.table,caption="Selected parameter estimates from SEAM in SFA-25a")
```


\newpage
```{r bbn-param-table,include=T,echo=F}
csas_table(bbn.20.parm.table,caption="Selected parameter estimates from SEAM in SFA-26a")
```


\newpage
```{r sab-bias-table,include=T,echo=F}
csas_table(bias.sab.clean,caption ="Annual retrospecitve results for SFA 25a.  Positive values indicate the retrospective
                              model estimates were higher than that base model. The Biomass retro and Recruit retro are in tonnes.
                             The relative metrics are proportional differences between the retrospective model and the base model.
                             The year represents the terminal year used to compare with the base model.")
```


\newpage
```{r bbn-bias-table,include=T,echo=F}
csas_table(bias.bbn.clean, caption ="Annual retrospecitve results for SFA 26a.  Positive values indicate the retrospective
                              model estimates were higher than that base model. The Biomass retro and Recruit retro are in tonnes.
                             The relative metrics are proportional differences between the retrospective model and the base model.
                             The year represents the terminal year used to compare with the base model.")
```



