---
output:
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---
\clearpage
\newpage

# Tables {-}

```{r include=F, echo=F}

# These are the tables I want to make.
# clean things up...
# Parameter tables 
# First Sable and BSSM, here pulling this for parameters with only a single estimate
parameters.bssm <- c("K","S","$\\frac{1}{\\kappa_{tau}^2}$","$\\frac{1}{\\kappa_{rho}^2}$", "$q$", "$\\sigma$")
parameters.seam <- c("$\\sigma_{\\epsilon}$", "$\\sigma_{\\upsilon}$",  "$R_0$", "$B_0$",
                     "$p_I$" ,"$p_{IR}$", "$\\psi_B$","$\\lambda_B$" , "$\\psi_R$", "$\\lambda_R$", "$\\psi_m$","$\\lambda_m$", "$S$")
# parameters.sab.seam <- c("$\\sigma_{\\epsilon}$", "$\\sigma_{\\upsilon}$", "$B_0$", "$R_0$", "$m_0$", 
#                      "$p_I$" ,"$p_{IR}$", "$\\psi_B$", "$\\psi_R$", "$\\psi_m$","$\\lambda_B$", "$\\lambda_R$", "$\\lambda_m$", "$S$")

extract.bssm <- which(rownames(sab.bssm.mod.out$summary) %in% c("sigma","S","q","ikappa.rho2","ikappa.tau2",'K'))

sab.bssm.parm.table <- data.frame(sab.bssm.mod.out$summary[extract.bssm,c("mean","sd")])
rownames(sab.bssm.parm.table) <- parameters.bssm
names(sab.bssm.parm.table) <- c("Estimate","Standard Error")
sab.bssm.parm.table$Estimate <- as.character(round(sab.bssm.parm.table$Estimate,digits=2))
sab.bssm.parm.table$Estimate[c(1,3,4)] <- substr(sab.bssm.parm.table$Estimate[c(1,3,4)],start = 1,stop = 3)
sab.bssm.parm.table$`Standard Error`<- as.character(round(sab.bssm.parm.table$`Standard Error`,digits=2))
sab.bssm.parm.table$`Standard Error`[c(1,3,4)]<- substr(sab.bssm.parm.table$`Standard Error`[c(1,3,4)],start=1,stop=3)




# SEAM...  get these from sdrep so we can get the standard errors reported as well.
sab.10.parm.table <- summary(sab.10$sdrep)
# Names we want to extract...
extract <- rownames(sab.10.parm.table)[c(1:12,23)]
sab.10.parm.table <- data.frame(sab.10.parm.table[extract,])
rownames(sab.10.parm.table) <- parameters.seam
names(sab.10.parm.table) <- c("Estimate","Standard Error")
sab.10.parm.table$Estimate <- as.character(round(sab.10.parm.table$Estimate,digits=2))
sab.10.parm.table$Estimate[-c(1,2)] <- substr(sab.10.parm.table$Estimate[-c(1,2)],1,4)
sab.10.parm.table$Estimate[c(3:6,8,10,12)] <- substr(sab.10.parm.table$Estimate[c(3:6,8,10,12)],1,3)
sab.10.parm.table$Estimate[c(7,9,11,13)] <- substr(sab.10.parm.table$Estimate[c(7,9,11,13)],1,4)
sab.10.parm.table$`Standard Error`<- as.character(round(sab.10.parm.table$`Standard Error`,digits=3))
sab.10.parm.table$`Standard Error`[-c(1:2)]<- substr(sab.10.parm.table$`Standard Error`[-c(1:2)],1,4)


# Now BBn and BSSM, here pulling this for parameters with only a single estimate
extract.bssm <- which(rownames(bbn.bssm.mod.out$summary) %in% c("sigma","S","q","ikappa.rho2","ikappa.tau2",'K'))
bbn.bssm.parm.table <- data.frame(bbn.bssm.mod.out$summary[extract.bssm,c("mean","sd")])
rownames(bbn.bssm.parm.table) <- parameters.bssm
names(bbn.bssm.parm.table) <- c("Estimate","Standard Error")
bbn.bssm.parm.table$Estimate <- as.character(round(bbn.bssm.parm.table$Estimate,digits=2))
bbn.bssm.parm.table$Estimate[c(1,3,4)] <- substr(bbn.bssm.parm.table$Estimate[c(1,3,4)],start = 1,stop = 3)
bbn.bssm.parm.table$`Standard Error`<- as.character(round(bbn.bssm.parm.table$`Standard Error`,digits=2))
bbn.bssm.parm.table$`Standard Error`[c(3,4)]<- substr(bbn.bssm.parm.table$`Standard Error`[c(3,4)],start=1,stop=3)
bbn.bssm.parm.table$`Standard Error`[1]<- substr(bbn.bssm.parm.table$`Standard Error`[1],start=1,stop=2)

# BBn
bbn.20.parm.table <- summary(bbn.20$sdrep)
# Names we want to extract...
extract <- rownames(bbn.20.parm.table)[c(1:12,33)]
bbn.20.parm.table <- data.frame(bbn.20.parm.table[extract,])
rownames(bbn.20.parm.table) <- parameters.seam
names(bbn.20.parm.table) <- c("Estimate","Standard Error")
bbn.20.parm.table$Estimate <- as.character(round(bbn.20.parm.table$Estimate,digits=2))
bbn.20.parm.table$Estimate[-c(1,2)] <- substr(bbn.20.parm.table$Estimate[-c(1,2)],1,4)
bbn.20.parm.table$Estimate[c(3:6,8,10,12)] <- substr(bbn.20.parm.table$Estimate[c(3:6,8,10,12)],1,3)
bbn.20.parm.table$Estimate[c(7,9,11,13)] <- substr(bbn.20.parm.table$Estimate[c(7,9,11,13)],1,4)
bbn.20.parm.table$`Standard Error`<- as.character(round(bbn.20.parm.table$`Standard Error`,digits=3))
bbn.20.parm.table$`Standard Error`[-c(1:2)]<- substr(bbn.20.parm.table$`Standard Error`[-c(1:2)],1,4)


# BSSM bias table...

bias.sab.clean <- bias.sab[,-ncol(bias.sab)]
bias.sab.clean[,c(2,4,5,6)] <- round(bias.sab.clean[,c(2,4,5,6)],digits=2)
bias.sab.clean[,c(1,3)] <- round(bias.sab.clean[,c(1,3)],digits=0)
# Now get beter names
names(bias.sab.clean) <- c("$BD_{fr,t,retro}$"," $RBD_{fr,t,retro}$",
                           "$BD_{r,t,retro}$","$RBD_{r,t,retro}$",
                           "$MD_{t,retro}$","$RMD{t,retro}$")

bias.sab.bssm.clean <- bias.bssm.sab[,-ncol(bias.bssm.sab)]
bias.sab.bssm.clean[,c(2,4,5,6)] <- round(bias.sab.bssm.clean[,c(2,4,5,6)],digits=2)
bias.sab.bssm.clean[,c(1,3)] <- round(bias.sab.bssm.clean[,c(1,3)],digits=0)
# Now get beter names
names(bias.sab.bssm.clean) <- c("$BD_{fr,t,retro}$"," $RBD_{fr,t,retro}$",
                           "$BD_{r,t,retro}$","$RBD_{r,t,retro}$",
                           "$MD_{t,retro}$","$RMD_{t,retro}$")

                      
# Same for bbn....
bias.bbn.clean <- bias.bbn[,-ncol(bias.bbn)]
bias.bbn.clean[,c(2,4,5,6)] <- round(bias.bbn.clean[,c(2,4,5,6)],digits=2)
bias.bbn.clean[,c(1,3)] <- round(bias.bbn.clean[,c(1,3)],digits=0)
# Now get beter names
names(bias.bbn.clean) <- c("$BD_{fr,t,retro}$"," $RBD_{fr,t,retro}$",
                           "$BD_{r,t,retro}$","$RBD_{r,t,retro}$",
                           "$MD_{t,retro}$","$RMD_{t,retro}$")

bias.bbn.bssm.clean <- bias.bssm.bbn[,-ncol(bias.bssm.bbn)]
bias.bbn.bssm.clean[,c(2,4,5,6)] <- round(bias.bbn.bssm.clean[,c(2,4,5,6)],digits=2)
bias.bbn.bssm.clean[,c(1,3)] <- round(bias.bbn.bssm.clean[,c(1,3)],digits=0)
# Now get beter names
names(bias.bbn.bssm.clean) <- c("$BD_{fr,t,retro}$"," $RBD_{fr,t,retro}$",
                           "$BD_{r,t,retro}$","$RBD_{r,t,retro}$",
                           "$MD_{t,retro}$","$RMD_{t,retro}$")


# Clean up the decision tables from SEBDAM
bbn.dt$table$`Biomass change (%)` <- round(bbn.dt$table$`Biomass change (%)`,digits=1)
bbn.dt$table$`Biomass change (tonnes)` <- round(bbn.dt$table$`Biomass change (tonnes)`,digits=0)
sab.dt$table$`Biomass change (%)` <- round(sab.dt$table$`Biomass change (%)`,digits=1)
sab.dt$table$`Probability of Decline` <- round(sab.dt$table$`Probability of Decline`,digits=2)

sab.bssm.dt$`Biomass (tonnes)` <- prettyNum(sab.bssm.dt$`Biomass (tonnes)`,big.mark = ',')
bbn.bssm.dt$`Biomass (tonnes)` <- prettyNum(bbn.bssm.dt$`Biomass (tonnes)`,big.mark = ',')

opts <- options(knitr.kable.NA = "")

```


```{r sfa-25-bssm-param-table,include=T,echo=F}
csas_table(sab.bssm.parm.table,caption="Parameter predictions and their standard errors from BSSM in SFA-25a for parameters which do not vary annually. $K$ is a biomass scaling parameter that is used to assist with model convergence. $S$ is referred to as the 'dissolution rate' for the clapper model. The precision parameter for the fully-recruited clapper process equation is $\\frac{1}{\\kappa_{tau}^2}$, while $\\frac{1}{\\kappa_{rho}^2}$ is the precision parameter for the recruit clapper process equation. The catchabilty is $q$ and the process error standard deviation is $\\sigma$.")
```

\newpage
```{r sfa-26-bssm-param-table,include=T,echo=F}
csas_table(bbn.bssm.parm.table,caption="Parameter predictions and their standard errors from BSSM in SFA-65a for parameters which do not vary annually. $K$ is a biomass scaling parameter that is used to assist with model convergence. $S$ is referred to as the 'dissolution rate' for the clapper model. The precision parameter for the fully-recruited clapper process equation is $\\frac{1}{\\kappa_{tau}^2}$, while $\\frac{1}{\\kappa_{rho}^2}$ is the precision parameter for the recruit clapper process equation. The catchabilty is $q$ and the process error standard deviation is $\\sigma$.")
```


\newpage
```{r sfa-25-param-table,include=T,echo=F}
csas_table(sab.10.parm.table,caption="Parameter predictions and their standard errors from SEAM in SFA-25a, all parameter predictions are on the log scale except $p_I$ and $p_{IR}$ which are on the logit scale.  The standard deviation for the observation equation of fully-recruited biomass is $\\sigma_{\\epsilon}$. The standard deviation for the observation equation of recruit biomass is $\\sigma_{\\upsilon}$. The estimated intial value for fully recruited biomass, recruit biomass, and natural mortality are represented by $B_0$, $R_0$, and $m_0$ respectively. The probability of encountering fully-recruited scallop and recruit scallop are represented by $p_I$ and $p_{IR}$. The random field range for fully-recruited biomass, recruit biomass, and natural mortality are $\\psi_B$, $\\psi_R$, and $\\psi_m$, while the random field spatial standard deviations are $\\lambda_B$, $\\lambda_R$ and $\\lambda_m$.  Finally, the clapper catachability parameter is $S$.")
```


\newpage
```{r sfa-26-param-table,include=T,echo=F}
csas_table(bbn.20.parm.table,caption="Parameter predictions and their standard errors from SEAM in SFA-26a, all parameter predictions are on the log scale except $p_I$ and $p_{IR}$ which are on the logit scale. The standard deviation for the observation equation of fully-recruited biomass is $\\sigma_{\\epsilon}$. The standard deviation for the observation equation of recruit biomass is $\\sigma_{\\upsilon}$. The estimated intial value for fully recruited biomass, recruit biomass, and natural mortality are represented by $B_0$, $R_0$, and $m_0$ respectively. The probability of encountering fully-recruited scallop and recruit scallop are represented by $p_I$ and $p_{IR}$. The random field range for fully-recruited biomass, recruit biomass, and natural mortality are $\\psi_B$, $\\psi_R$, and $\\psi_m$, while the random field spatial standard deviations are $\\lambda_B$, $\\lambda_R$ and $\\lambda_m$.  Finally, the clapper catachability parameter is $S$.")
```


\newpage
```{r sfa-25-bssm-bias-table,include=T,echo=F}
csas_table(bias.sab.bssm.clean,caption ="Annual retrospective results from BSSM in SFA 25A. Positive values indicate the retrospective model predictions were higher than that full model.
                                           The Fully-recruited Biomass ($BD_{fr,t,retro}$) and Recruit Biomass ($BD_{r,t,retro}$) retrospectives are in tonnes.
                                          The natural mortality retrospective (instantaneous) is $MD_{t,retro}$. The relative metrics, $RBD_{fr,t,retro}$, $RBD_{r,t,retro}$, and $RMD_{t,retro}$                                            are the proportional differences between the retrospective model and the full model for fully-recruited biomass, recruit biomass, and natural mortality                                                    respectively. The year represents the terminal year used to compare with the full model.")

```


\newpage
```{r sfa-25-bias-table,include=T,echo=F}
csas_table(bias.sab.clean,caption ="Annual retrospective results from SEAM in SFA 25A. Positive values indicate the retrospective
                              model predictions were higher than that full model. The Fully-recruited Biomass ($BD_{fr,t,retro}$) and Recruit Biomass ($BD_{r,t,retro}$) retrospectives are in tonnes.
                              The natural mortality retrospective (instantaneous) is $MD_{t,retro}$. The relative metrics, $RBD_{fr,t,retro}$, $RBD_{r,t,retro}$, and $RMD_{t,retro}$ are the
                              proportional differences between the retrospective model and the full model for fully-recruited biomass, recruit biomass, and natural mortality respectively.
                              The year represents the terminal year used to compare with the full model.")
```


\newpage
```{r sfa-26-bssm-bias-table,include=T,echo=F}
csas_table(bias.bbn.bssm.clean,caption ="Annual retrospective results from BSSM in SFA 26A. Positive values indicate the retrospective
                              model predictions were higher than that full model. The Fully-recruited Biomass ($BD_{fr,t,retro}$) and Recruit Biomass ($BD_{r,t,retro}$) retrospectives are in tonnes.
                              The natural mortality retrospective (instantaneous) is $MD_{t,retro}$. The relative metrics, $RBD_{fr,t,retro}$, $RBD_{r,t,retro}$, and $RMD_{t,retro}$ are the
                              proportional differences between the retrospective model and the full model for fully-recruited biomass, recruit biomass, and natural mortality respectively.
                              The year represents the terminal year used to compare with the full model.")

```


\newpage
```{r sfa-26-bias-table,include=T,echo=F}
csas_table(bias.bbn.clean, caption ="Annual retrospective results from SEAM in SFA 26A. Positive values indicate the retrospective
                              model predictions were higher than that full model. The Fully-recruited Biomass ($BD_{fr,t,retro}$) and Recruit Biomass ($BD_{r,t,retro}$) retrospectives are in tonnes.
                              The natural mortality retrospective (instantaneous) is $MD_{t,retro}$. The relative metrics, $RBD_{fr,t,retro}$, $RBD_{r,t,retro}$, and $RMD_{t,retro}$ are the
                              proportional differences between the retrospective model and the full model for fully-recruited biomass, recruit biomass, and natural mortality respectively.
                              The year represents the terminal year used to compare with the full model.")
```


\newpage
```{r sfa-25-bssm-dt,include=T,echo=F}
csas_table(sab.bssm.dt, caption ="Decision table using the 2022 BSSM output for SFA 25A to estimate fully-recruited biomass in 2023 using the no growth scenario.")
```



\newpage
```{r sfa-25-seam-dt,include=T,echo=F}
csas_table(sab.dt$table, caption ="Decision table using the 2022 SEAM output for SFA 25A to estimate fully-recruited biomass in 2023 using the no growth scenario.")
```


\newpage
```{r sfa-26-bssm-dt,include=T,echo=F}
csas_table(bbn.bssm.dt, caption ="Decision table using the 2022 BSSM output for SFA 26A to estimate fully-recruited biomass in 2023 using the no growth scenario.")
```


\newpage
```{r sfa-26-seam-dt,include=T,echo=F}
csas_table(bbn.dt$table, caption ="Decision table using the 2022 SEAM output for SFA 26A to estimate fully-recruited biomass in 2023 using the no growth scenario.")
```
